import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// 6061 Aluminium Alloy
INDUCTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('aluminium') * 10144)
    .inputs(ore('dustTinyMagnesium') * 8)
    .inputs(ore('dustTinySilicon') * 4)
    .inputs(ore('dustTinyCopper') * 1)
    .inputs(ore('dustTinyChrome') * 1)
    .fluidOutputs(fluid('aluminium_alloy_6061') * 10368)
    .duration(1440)
    .EUt(VA[MV])
    .buildAndRegister()

// Magnalium
INDUCTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('aluminium') * 10848)
    .inputs(ore('dustTinyZinc') * 17)
    .inputs(ore('dustTinyMagnesium') * 20)
    .inputs(ore('dustTinyCopper') * 4)
    .inputs(ore('dustTinyChrome') * 1)
    .fluidOutputs(fluid('aluminium_alloy_7075') * 11520)
    .duration(1600)
    .EUt(VA[MV])
    .buildAndRegister()

INDUCTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('aluminium') * 7472)
    .inputs(ore('dustTinyMagnesium') * 30)
    .inputs(ore('dustTinyManganese') * 3)
    .fluidOutputs(fluid('aluminium_alloy_mg_6') * 8000)
    .duration(1120)
    .EUt(VA[MV])
    .buildAndRegister()

// Magnalium
INDUCTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('aluminium') * 2736)
    .inputs(metaitem('ingotMagnesium'))
    .fluidOutputs(fluid('magnalium') * 2880)
    .duration(400)
    .EUt(VA[LV])
    .buildAndRegister()
    .EUt(VA[LV])
    .buildAndRegister();


INDUCTION_FURNACE.recipeBuilder()
        .fluidInputs(fluid('aluminium') * 26576)
        .inputs(ore('dustTinyCopper') * 45)
        .inputs(ore('dustTinyManganese') * 18)
        .inputs(ore('dustTinyVanadium') * 1)
        .inputs(ore('dustTinyZirconium') * 2)
        .inputs(ore('dustTinyTitanium') * 1)
        .fluidOutputs(fluid('aluminium_alloy_2219') * 27648)
        .duration(3840)
        .EUt(VA[MV])
        .buildAndRegister()

INDUCTION_FURNACE.recipeBuilder()
        .fluidInputs(fluid('aluminium') * 32192)
        .inputs(ore('dustTinyCopper') * 36)
        .inputs(ore('dustTinyLithium') * 90)
        .inputs(ore('dustTinyManganese') * 18)
        .inputs(ore('dustTinySilver') * 3)
        .inputs(ore('dustTinyZirconium') * 1)
        .fluidOutputs(fluid('aluminium_alloy_2195') * 34560)
        .duration(4800)
        .EUt(VA[MV])
        .buildAndRegister()

INDUCTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('aluminium') * 15920)
    .inputs(ore('dustTinyScandium') * 2)
    .inputs(ore('dustTinyZirconium') * 2)
    .inputs(ore('dustTinyErbium') * 1)
    .fluidInputs(fluid('argon') * 4000)
    .fluidOutputs(fluid('scandium_alloy') * 16000)
    .duration(4440)
    .EUt(VA[EV])
    .buildAndRegister()
