import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// 6061 Aluminium Alloy
// 97.6% Al 1.1% Mg 0.64% Si 0.36% Cu 0.30% Cr
INDUCTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('nitrogen') * 1000)
    .fluidInputs(fluid('aluminium') * 10144)
    .inputs(ore('dustTinyMagnesium') * 8)
    .inputs(ore('dustTinySilicon') * 4)
    .inputs(ore('dustTinyCopper') * 1)
    .inputs(ore('dustTinyChrome') * 1)
    .fluidOutputs(fluid('aluminium_alloy_6061') * 10368)
    .EUt(VA[MV])
    .duration(9600)
    .buildAndRegister()

INDUCTION_FURNACE.recipeBuilder()
    .notConsumable(fluid('argon') * 1000)
    .fluidInputs(fluid('aluminium') * 10144)
    .inputs(ore('dustTinyMagnesium') * 8)
    .inputs(ore('dustTinySilicon') * 4)
    .inputs(ore('dustTinyCopper') * 1)
    .inputs(ore('dustTinyChrome') * 1)
    .fluidOutputs(fluid('aluminium_alloy_6061') * 10368)
    .EUt(VA[MV])
    .duration(9600)
    .buildAndRegister()

// 7075 Aluminium Alloy
// 90.6% Al 5.5% Zn 2.4% Mg 1.3% Cu 0.26% Cr
INDUCTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('nitrogen') * 1000)
    .fluidInputs(fluid('aluminium') * 10848)
    .inputs(ore('dustTinyZinc') * 17)
    .inputs(ore('dustTinyMagnesium') * 20)
    .inputs(ore('dustTinyCopper') * 4)
    .inputs(ore('dustTinyChrome') * 1)
    .fluidOutputs(fluid('aluminium_alloy_7075') * 11520)
    .EUt(VA[MV])
    .duration(9600)
    .buildAndRegister()

INDUCTION_FURNACE.recipeBuilder()
    .notConsumable(fluid('argon') * 1000)
    .fluidInputs(fluid('aluminium') * 10848)
    .inputs(ore('dustTinyZinc') * 17)
    .inputs(ore('dustTinyMagnesium') * 20)
    .inputs(ore('dustTinyCopper') * 4)
    .inputs(ore('dustTinyChrome') * 1)
    .fluidOutputs(fluid('aluminium_alloy_7075') * 11520)
    .EUt(VA[MV])
    .duration(9600)
    .buildAndRegister()

INDUCTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('aluminium') * 7472)
    .inputs(ore('dustTinyMagnesium') * 30)
    .inputs(ore('dustTinyManganese') * 3)
    .fluidOutputs(fluid('aluminium_alloy_mg_6') * 8000)
    .EUt(VA[MV])
    .buildAndRegister()

// Magnalium
INDUCTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('aluminium') * 2736)
    .inputs(ore('ingotMagnesium'))
    .fluidOutputs(fluid('magnalium') * 2880)
    .EUt(VA[LV])
    .buildAndRegister();


INDUCTION_FURNACE.recipeBuilder()
        .fluidInputs(fluid('aluminium') * 26576)
        .inputs(ore('dustTinyCopper') * 45)
        .inputs(ore('dustTinyManganese') * 18)
        .inputs(ore('dustTinyVanadium') * 1)
        .inputs(ore('dustTinyZirconium') * 2)
        .inputs(ore('dustTinyTitanium') * 1)
        .fluidOutputs(fluid('aluminium_alloy_2219') * 27648)
        .EUt(VA[MV])
        .duration(9600)
        .buildAndRegister()

INDUCTION_FURNACE.recipeBuilder()
        .fluidInputs(fluid('aluminium') * 32192)
        .inputs(ore('dustTinyCopper') * 36)
        .inputs(ore('dustTinyLithium') * 90)
        .inputs(ore('dustTinyManganese') * 18)
        .inputs(ore('dustTinySilver') * 3)
        .inputs(ore('dustTinyZirconium') * 1)
        .fluidOutputs(fluid('aluminium_alloy_2195') * 34560)
        .EUt(VA[MV])
        .duration(9600)
        .buildAndRegister()