import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// Lead-Tin Soldering Alloy
RESISTANCE_FURNACE.recipeBuilder()
    .inputs(metaitem('dustTin') * 6)
    .inputs(metaitem('dustLead') * 3)
    .inputs(metaitem('dustAntimony'))
    .notConsumable(metaitem('susy:clay_graphite_crucible'))
    .fluidOutputs(fluid('soldering_alloy') * 1440)
    .temperature(904)
    .EUt(VA[LV])
    .buildAndRegister()

INDUCTION_FURNACE.recipeBuilder()
    .inputs(metaitem('dustTin') * 6)
    .inputs(metaitem('dustLead') * 3)
    .inputs(metaitem('dustAntimony'))
    .fluidOutputs(fluid('soldering_alloy') * 1440)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

RESISTANCE_FURNACE.recipeBuilder()
    .inputs(metaitem('dustTin') * 4)
    .inputs(metaitem('dustBismuth') * 6)
    .notConsumable(metaitem('susy:clay_graphite_crucible'))
    .fluidOutputs(fluid('lead_free_solder') * 1440)
    .temperature(544)
    .EUt(VA[MV])
    .buildAndRegister()

INDUCTION_FURNACE.recipeBuilder()
    .inputs(metaitem('dustTin') * 4)
    .inputs(metaitem('dustBismuth') * 6)
    .fluidOutputs(fluid('lead_free_solder') * 1440)
    .duration(60)
    .EUt(VA[MV])
    .buildAndRegister()

RESISTANCE_FURNACE.recipeBuilder()
    .inputs(ore('dustIndium') * 3)
    .inputs(ore('dustTinySilver'))
    .notConsumable(metaitem('susy:clay_graphite_crucible'))
    .fluidOutputs(fluid('cryogenic_solder') * 432)
    .temperature(1235)
    .EUt(VA[MV])
    .buildAndRegister()

INDUCTION_FURNACE.recipeBuilder()
    .inputs(ore('dustIndium') * 3)
    .inputs(ore('dustTinySilver'))
    .fluidOutputs(fluid('cryogenic_solder') * 432)
    .duration(60)
    .EUt(VA[MV])
    .buildAndRegister()

