BR = recipemap('batch_reactor')
ELECTROLYTIC_CELL = recipemap('electrolytic_cell')

BR.recipeBuilder()
    .inputs(ore('dustThalliumRichFlue'))
    .fluidInputs(fluid('sulfuric_acid') * 100)
    .outputs(metaitem('dustAsh'))
    .fluidOutputs(fluid('impure_thallium_sulfate_solution') * 100)
    .EUt(30)
    .duration(20)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSalt') * 2)
    .fluidInputs(fluid('impure_thallium_sulfate_solution') * 1000)
    .outputs(metaitem('dustThalliumIChloride') * 2)
    .fluidOutputs(fluid('acidic_wastewater') * 1000)
    .EUt(30)
    .duration(20)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustThalliumIChloride') * 4)
    .fluidInputs(fluid('diluted_sulfuric_acid') * 2000)
    .fluidOutputs(fluid('thallium_sulfate_solution') * 1000) // 1 Tl2SO4, 1 H2O, 2 HCl 
    .EUt(30)
    .duration(20)
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .notConsumable(ore('stickPlatinum'))
    .notConsumable(metaitem('graphite_electrode'))
    .fluidInputs(fluid('thallium_sulfate_solution') * 1000)
    .outputs(metaitem('dustThallium'))
    .fluidOutputs(fluid('hydrogen_chloride') * 2000)
    .fluidOutputs(fluid('sulfuric_acid') * 1000)
    .fluidOutputs(fluid('oxygen') * 1000)