BR = recipemap('batch_reactor')
ROASTER = recipemap('roaster')
CRYSTALLIZER = recipemap('crystallizer')
ELECTROLYTIC_CELL = recipemap('electrolytic_cell')
VACUUM_DT = recipemap('vacuum_distillation')

// From zinc pyrometallurgy
BR.recipeBuilder()
    .inputs(ore('dustZincFlue'))
    .fluidInputs(fluid('sulfuric_acid') * 1000)
    .outputs(metaitem('dustAsh'))
    .fluidOutputs(fluid('impure_cadmium_sulfate_solution') * 1000)
    .EUt(30)
    .duration(20)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSalt') * 2)
    .fluidInputs(fluid('impure_cadmium_sulfate_solution') * 10000)
    .outputs(metaitem('dustThalliumIChloride') * 2)
    .fluidOutputs(fluid('cadmium_sulfate_solution') * 10000)
    .EUt(30)
    .duration(20)
    .buildAndRegister()

// From zinc hydrometallurgy
BR.recipeBuilder()
    .fluidInputs(fluid('sulfuric_acid') * 1000)
    .fluidInputs(fluid('water') * 1000)
    .inputs(ore('dustCopperCadmiumResidue') * 30)
    .fluidOutputs(fluid('cadmium_sulfate_solution') * 1000)
    .fluidOutputs(fluid('hydrogen') * 2000)
    .outputs(metaitem('dustCopper') * 2)
    .EUt(30)
    .duration(160)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustZinc'))
    .fluidInputs(fluid('cadmium_sulfate_solution') * 1000)
    .chancedOutput(metaitem('sponge.cadmium'), 9000, 0)
    .fluidOutputs(fluid('wastewater') * 1000)
    .EUt(30)
    .duration(160)
    .buildAndRegister()

// Electrorefining
BR.recipeBuilder()
    .inputs(metaitem('sponge.cadmium'))
    .fluidInputs(fluid('sulfuric_acid') * 1000)
    .fluidInputs(fluid('air') * 4000)
    .fluidOutputs(fluid('purified_cadmium_solution') * 1000)
    .EUt(30)
    .duration(160)
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .notConsumable(ore('stickLead'))
    .notConsumable(ore('plateAluminium'))
    .fluidInputs(fluid('purified_cadmium_solution') * 1000)
    .outputs(metaitem('dustCadmium'))
    .fluidOutputs(fluid('oxygen') * 1000)
    .fluidOutputs(fluid('sulfuric_acid') * 1000)
    .EUt(30)
    .duration(160)
    .buildAndRegister()

// CdO

ROASTER.recipeBuilder()
    .inputs(ore('dustCadmium'))
    .fluidInputs(fluid('oxygen') * 1000)
    .outputs(metaitem('dustCadmiumOxide') * 2)
    .EUt(120)
    .duration(80)
    .buildAndRegister()

// Cd(NO3)2

BR.recipeBuilder()
    .inputs(ore('dustCadmiumOxide') * 2)
    .fluidInputs(fluid('nitric_acid') * 2000)
    .outputs(metaitem('dustAnhydrousCadmiumNitrate') * 9)
    .fluidOutputs(fluid('water') * 1000)
    .EUt(120)
    .duration(80)
    .buildAndRegister()

// Cd(NO3)2 * (H2O)4

CRYSTALLIZER.recipeBuilder()
    .inputs(ore('dustAnhydrousCadmiumNitrate') * 9)
    .fluidInputs(fluid('demineralized_water') * 4000)
    .outputs(metaitem('dustCadmiumNitrateTetrahydrate') * 21)
    .EUt(120)
    .duration(160)
    .buildAndRegister()

// Cd(OH)2

BR.recipeBuilder()
    .inputs(ore('dustCadmiumNitrateTetrahydrate') * 21)
    .fluidInputs(fluid('sodium_hydroxide') * 864)
    .outputs(metaitem('dustRawCadmiumHydroxide') * 5)
    .outputs(metaitem('dustSodiumNitrate') * 10)
    .fluidOutputs(fluid('dense_steam') * 5000)
    .EUt(120)
    .duration(80)
    .buildAndRegister()

VACUUM_DT.recipeBuilder()
    .inputs(ore('dustRawCadmiumHydroxide'))
    .outputs(metaitem('dustCadmiumHydroxide'))
    .EUt(120)
    .duration(80)
    .buildAndRegister()
