import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

MIXER.recipeBuilder()
    .inputs(ore('dustImpureCinnabar') * 8)
    .fluidInputs(fluid('distilled_water') * 2000)
    .fluidOutputs(fluid('impure_cinnabar_slurry') * 2000)
    .EUt(VA[HV])
    .duration(80)
    .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
    .fluidInputs(fluid('impure_cinnabar_slurry') * 2000)
    .notConsumable(metaitem('dustPotassiumButylXanthate'))
    .notConsumable(metaitem('dustLeadNitrate') * 9)
    .fluidOutputs(fluid('pegmatite_tailing_slurry') * 1000)
    .fluidOutputs(fluid('cinnabar_slurry') * 1000)
    .EUt(VA[HV])
    .duration(80)
    .buildAndRegister()

CLARIFIER.recipeBuilder()
    .fluidInputs(fluid('cinnabar_slurry') * 1000)
    .outputs(metaitem('dustCinnabar') * 16)
    .fluidOutputs(fluid('wastewater') * 1000)
    .EUt(VA[LV])
    .duration(20)
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustCinnabar'))
    .fluidInputs(fluid('oxygen') * 2000)
    .fluidOutputs(fluid('mercury') * 1000)
    .fluidOutputs(fluid('sulfur_dioxide') * 1000)
    .duration(60)
    .EUt(VA[LV])
    .buildAndRegister()

ELECTROLYZER.recipeBuilder()
    .notConsumable(metaitem('stickIron'))
    .notConsumable(metaitem('graphite_electrode'))
    .notConsumable(fluid('water') * 1000)
    .inputs(ore('dustMercuryIiChloride') * 3)
    .fluidOutputs(fluid('chlorine') * 2000)
    .fluidOutputs(fluid('mercury') * 1000)
    .duration(120)
    .EUt(VA[MV])
    .buildAndRegister()