import static prePostInit.Recipemaps.*
import globals.Carbons
import static globals.SinteringGlobals.*
import static gregtech.api.GTValues.*
import gregtech.api.recipes.ingredients.GTRecipeItemInput;

// Zincite Dust * 1
mods.gregtech.electric_blast_furnace.removeByInput(120, [metaitem('dustSphalerite')], [fluid('oxygen') * 3000])

// Zinc ore beneficiation
MIXER.recipeBuilder()
        .inputs(ore('dustImpureSphalerite') * 4)
        .fluidInputs(fluid('distilled_water') * 2000)
        .fluidOutputs(fluid('impure_sphalerite_slurry') * 2000)
        .EUt(VA[HV])
        .duration(80)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .fluidInputs(fluid('impure_sphalerite_slurry') * 16000)
        .notConsumable(metaitem('dustSodiumEthylXanthate'))
        .notConsumable(fluid('cresol') * 100)
        .notConsumable(fluid('soda_ash_solution') * 1000)
        .fluidOutputs(fluid('galena_slurry') * 3000)
        .fluidOutputs(fluid('unprocessed_sphalerite_slurry') * 16000)
        .EUt(VA[HV])
        .duration(80)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .fluidInputs(fluid('unprocessed_sphalerite_slurry') * 16000)
        .notConsumable(metaitem('dustPotassiumAmylXanthate'))
        .notConsumable(fluid('soda_ash_solution') * 1000)
        .fluidOutputs(fluid('sphalerite_slurry') * 16000)
        .outputs(metaitem('dustGraniteTailings') * 16)
        .EUt(VA[HV])
        .duration(200)
        .buildAndRegister()

CLARIFIER.recipeBuilder()
        .fluidInputs(fluid('sphalerite_slurry') * 16000)
        .fluidOutputs(fluid('wastewater') * 16000)
        .outputs(metaitem('dustSphalerite') * 64)
        .EUt(VA[LV])
        .duration(20)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustImpureSmithsonite') * 4)
        .fluidInputs(fluid('water') * 2000)
        .fluidOutputs(fluid('impure_smithsonite_slurry') * 2000)
        .EUt(VA[HV])
        .duration(80)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .fluidInputs(fluid('impure_smithsonite_slurry') * 16000)
        .notConsumable(metaitem('dustSodiumEthylXanthate'))
        .notConsumable(fluid('cresol') * 100)
        .notConsumable(fluid('soda_ash_solution') * 1000)
        .fluidOutputs(fluid('smithsonite_slurry') * 16000)
        .EUt(VA[HV])
        .duration(80)
        .buildAndRegister()

CLARIFIER.recipeBuilder()
        .fluidInputs(fluid('smithsonite_slurry') * 16000)
        .fluidOutputs(fluid('wastewater') * 16000)
        .outputs(metaitem('dustSmithsonite') * 64)
        .EUt(VA[LV])
        .duration(20)
        .buildAndRegister()

// Ore pretreatment to form oxide concentrate
ROASTER.recipeBuilder()
        .inputs(ore('dustSphalerite') * 1)
        .fluidInputs(fluid('oxygen') * 2000)
        .fluidOutputs(fluid('zinc_flue_gas') * 1000)
        .outputs(metaitem('dustZincite') * 2)
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()

FLUIDIZED_BR.recipeBuilder()
		.notConsumable(metaitem('springKanthal'))
        .inputs(ore('dustSphalerite') * 8)
        .fluidInputs(fluid('oxygen') * 16000)
        .fluidOutputs(fluid('zinc_flue_gas') * 8000)
        .outputs(metaitem('dustZincite') * 16)
        .EUt(VA[MV])
        .duration(160)
        .buildAndRegister()     

// Cadmium/Thallium chain for pyrometallurgy start
SIFTER.recipeBuilder()
        .notConsumable(metaitem('item_filter'))
        .fluidInputs(fluid('zinc_flue_gas') * 1000)
        .chancedOutput(metaitem('dustZincFlue'), 1000, 250)
        .fluidOutputs(fluid('sulfur_dioxide') * 1000)
        .EUt(VA[MV])
        .duration(20)
        .buildAndRegister()  

ROASTER.recipeBuilder()
        .inputs(ore('dustSmithsonite') * 1)
        .fluidOutputs(fluid('carbon_dioxide') * 1000)
        .outputs(metaitem('dustZincite') * 2)
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()

FLUIDIZED_BR.recipeBuilder()
		.notConsumable(metaitem('springKanthal'))
        .inputs(ore('dustSmithsonite') * 8)
        .fluidOutputs(fluid('carbon_dioxide') * 8000)
        .outputs(metaitem('dustZincite') * 16)
        .EUt(VA[MV])
        .duration(160)
        .buildAndRegister()

// Conversion to metal via pyrometallurgy
for (combustible in Carbons.combustibles()) {
    ROASTER.recipeBuilder()
            .inputs(ore('dustZincite') * 2)
            .inputs(ore(combustible.name) * combustible.equivalent(1))
            .outputs(metaitem(combustible.byproduct))
            .fluidOutputs(fluid('crude_zinc') * 216)
            .fluidOutputs(fluid('carbon_monoxide') * 1000)
            .EUt(VA[LV])
            .duration(160 * combustible.duration)
            .buildAndRegister()
}

for (highPurityCombustible in Carbons.highPurityCombustibles()) {
        ROASTER.recipeBuilder()
            .inputs(ore('dustZincOxide') * 2)
            .inputs(ore(highPurityCombustible.name) * highPurityCombustible.equivalent(1))
            .outputs(metaitem('dustZinc'))
            .fluidOutputs(fluid('carbon_monoxide') * 1000)
            .EUt(VA[LV])
            .duration(160 * highPurityCombustible.duration)
            .buildAndRegister()
}

SOLIDIFIER.recipeBuilder()
        .notConsumable(metaitem('shape.mold.ingot'))
        .fluidInputs(fluid('crude_zinc') * 216)
        .outputs(metaitem('ingotZinc'))
        .EUt(VA[ULV])
        .duration(20)
        .buildAndRegister()

SOLIDIFIER.recipeBuilder()
        .notConsumable(metaitem('shape.mold.ingot'))
        .fluidInputs(fluid('cadmium_rich_zinc') * 180)
        .outputs(metaitem('ingotZinc'))
        .EUt(VA[ULV])
        .duration(20)
        .buildAndRegister()

HIGH_TEMP_DT.recipeBuilder()
        .fluidInputs(fluid('crude_zinc') * 2160)
        .chancedOutput(metaitem('dustIron'), 200, 100)
        .fluidOutputs(fluid('cadmium_rich_zinc') * 2160)
        .fluidOutputs(fluid('copper') * 36)
        .fluidOutputs(fluid('lead') * 72)
        .fluidOutputs(fluid('tin') * 36)
        .EUt(VA[MV])
        .duration(300)
        .buildAndRegister()

HIGH_TEMP_DT.recipeBuilder()
        .fluidInputs(fluid('cadmium_rich_zinc') * 2160)
        .fluidOutputs(fluid('zinc') * 2160)
        .fluidOutputs(fluid('cadmium') * 144)
        .EUt(VA[HV])
        .duration(300)
        .buildAndRegister()

// Hydrometallurgical method
CHEMICAL_BATH.recipeBuilder()
        .inputs(ore('dustZincite') * 2)
        .fluidInputs(fluid('sulfuric_acid') * 1000)
        .fluidOutputs(fluid('zinc_leach') * 1000)
        .outputs(metaitem('dustZincLeachResidue'))
        .EUt(VA[LV])
        .duration(160)
        .buildAndRegister()

FLUID_HEATER.recipeBuilder()
        .fluidInputs(fluid('sulfuric_acid') * 1000)
        .fluidOutputs(fluid('hot_sulfuric_acid') * 1000)
        .EUt(VA[ULV])
        .duration(50)
        .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
        .inputs(ore('dustZincLeachResidue'))
        .fluidInputs(fluid('hot_sulfuric_acid') * 125)
        .fluidOutputs(fluid('hot_zinc_leach') * 125)
        .chancedOutput(metaitem('dustLeadSilicaResidue'), 500, 500)
        .EUt(VA[LV])
        .duration(160)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .inputs(ore('dustLeadSilicaResidue'))
        .chancedOutput(metaitem('dustSiliconDioxide'), 6000, 0)
        .chancedOutput(metaitem('dustAnglesite'), 4000, 0)
        .EUt(VA[LV])
        .duration(160)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustSphalerite') * 1)
        .fluidInputs(fluid('hot_zinc_leach') * 8000)
        .outputs(metaitem('dustSulfur') * 1)
        .fluidOutputs(fluid('reduced_zinc_leach') * 8000)
        .EUt(VA[HV])
        .duration(50)
        .buildAndRegister()

AUTOCLAVE.recipeBuilder()
        .fluidInputs(fluid('oxygen') * 1000)
        .fluidInputs(fluid('reduced_zinc_leach') * 16000)
        .fluidOutputs(fluid('zinc_leach') * 16000)
        .outputs(metaitem('dustIronIiiOxide') * 5)
        .EUt(VA[LV])
        .duration(400)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('distilled_water') * 1000)
        .inputs(ore('dustZinc') * 1)
        .fluidOutputs(fluid('zinc_cementation_slurry') * 1000)
        .EUt(VA[LV])
        .duration(160)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('zinc_leach') * 1000)
        .fluidInputs(fluid('zinc_cementation_slurry') * 100)
        .fluidOutputs(fluid('precipitated_zinc_leach') * 1000)
        .outputs(metaitem('dustCopperCadmiumResidue') * 1)
        .EUt(VA[LV])
        .duration(160)
        .buildAndRegister()

FLUID_HEATER.recipeBuilder()
        .fluidInputs(fluid('precipitated_zinc_leach') * 1000)
        .fluidOutputs(fluid('hot_precipitated_zinc_leach') * 1000)
        .EUt(VA[LV])
        .duration(100)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('hot_precipitated_zinc_leach') * 1000)
        .fluidInputs(fluid('zinc_cementation_slurry') * 40)
        .fluidOutputs(fluid('reprecipitated_zinc_leach') * 1000)
        .outputs(metaitem('dustCobaltResidue') * 1)
        .EUt(VA[LV])
        .duration(160)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('sulfuric_acid') * 1000)
        .inputs(ore('dustCobaltResidue') * 20)
        .fluidOutputs(fluid('zinc_leach') * 1000)
        .outputs(metaitem('dustCobalt') * 1)
        .EUt(VA[LV])
        .duration(160)
        .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
        .notConsumable(metaitem('plateLead') * 4)
        .notConsumable(metaitem('plateAluminium') * 4)
        .circuitMeta(1)
        .fluidInputs(fluid('sulfuric_acid') * 50)
        .fluidInputs(fluid('distilled_water') * 50)
        .fluidInputs(fluid('reprecipitated_zinc_leach') * 1000)
        .outputs(metaitem('dustZinc'))
        .chancedOutput(metaitem('dustZinc'), 2500, 500)
        .fluidOutputs(fluid('hydrogen') * 100)
        .fluidOutputs(fluid('oxygen') * 1050)
        .fluidOutputs(fluid('sulfuric_acid') * 1050)
        .EUt(VA[MV])
        .duration(200)
        .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
        .notConsumable(metaitem('plateLead') * 4)
        .notConsumable(metaitem('plateAluminium') * 4)
        .circuitMeta(2)
        .fluidInputs(fluid('sulfuric_acid') * 50)
        .fluidInputs(fluid('distilled_water') * 50)
        .fluidInputs(fluid('reprecipitated_zinc_leach') * 1000)
        .outputs(metaitem('dustHighPurityZinc'))
        .fluidOutputs(fluid('hydrogen') * 100)
        .fluidOutputs(fluid('oxygen') * 1050)
        .fluidOutputs(fluid('sulfuric_acid') * 1050)
        .EUt(VA[MV])
        .duration(200)
        .buildAndRegister()

// From lead processing
SIFTER.recipeBuilder()
        .notConsumable(metaitem('item_filter'))
        .fluidInputs(fluid('zinc_oxide_fume_gas') * 1000)
        .chancedOutput(metaitem('dustZincOxideFume'), 1000, 0)
        .fluidOutputs(fluid('carbon_monoxide') * 1000)
        .EUt(VA[MV])
        .duration(160)
        .buildAndRegister()

carbons = new ItemStack[]{
        metaitem('dustCarbon'),
        metaitem('dustHighPurityCarbon'),
        metaitem('dustCoke')
}

for (fuel in rotary_kiln_fuels) {
	for (comburent in rotary_kiln_comburents) {
		ROTARY_KILN.recipeBuilder()
			.inputs(ore('dustZincOxideFume') * 2)
			.input(new GTRecipeItemInput(carbons, 1))
			.outputs(metaitem('dustWaelzOxide'))
			.outputs(metaitem('dustWaelzSlag'))
			.fluidInputs(fluid(fuel.name) * fuel.amountRequired)
			.fluidInputs(fluid(comburent.name) * comburent.amountRequired)
			.fluidOutputs(fluid(fuel.byproduct) * fuel.byproductAmount)
			.duration(fuel.duration + comburent.duration)
			.EUt(VA[MV])
			.buildAndRegister()
	}
}

CENTRIFUGE.recipeBuilder()
        .inputs(ore('dustWaelzSlag'))
        .chancedOutput(metaitem('dustHematite'), 5000, 0)
        .chancedOutput(metaitem('dustQuicklime') * 2, 2500, 0)
        .chancedOutput(metaitem('dustSiliconDioxide') * 3, 2500, 0)
        .EUt(VA[LV])
        .duration(40)
        .buildAndRegister()

ELECTROLYZER.recipeBuilder()
        .notConsumable(metaitem('graphite_electrode'))
        .notConsumable(metaitem('stickZinc'))
        .fluidInputs(fluid('zinc_chloride') * 432)
        .fluidOutputs(fluid('chlorine') * 2000)
        .outputs(metaitem('dustZinc'))
        .EUt(VA[LV])
        .duration(300)
        .buildAndRegister()

// Compounds
ROASTER.recipeBuilder()
        .inputs(ore('dustAnyPurityZinc'))
        .fluidInputs(fluid('oxygen') * 1000)
        .outputs(metaitem('dustZincOxide') * 2)
        .duration(300)
        .EUt(VA[LV])
        .buildAndRegister()
