import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// Silver Sulfadiazine

    // N-acetylsulfanilyl chloride

    BR.recipeBuilder()
        .fluidInputs(fluid('gtfo_aniline') * 1000)
        .fluidInputs(fluid('gtfo_acetic_anhydride') * 1000)
        .fluidOutputs(fluid('acetanilide_solution') * 1000)
        .duration(100) 
        .EUt(VA[LV])
        .buildAndRegister()

    DISTILLERY.recipeBuilder()
        .fluidInputs(fluid('acetanilide_solution') * 1000)
        .outputs(metaitem('dustAcetanilide') * 19)
        .fluidOutputs(fluid('acetic_acid') * 1000)
        .duration(100) 
        .EUt(VA[LV])
        .buildAndRegister()

    ROASTER.recipeBuilder()
        .inputs(ore('dustAcetanilide') * 19)
        .fluidInputs(fluid('chlorosulfuric_acid') * 2000)
        .outputs(metaitem('dustNAcetylsulfanilylChloride') * 22)
        .fluidOutputs(fluid('diluted_hydrochloric_acid') * 2000)
        .fluidOutputs(fluid('sulfur_trioxide') * 1000)
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister()

    // Guanidinium nitrate

    BR.recipeBuilder()
        .inputs(ore('dustCalciumCyanamide') * 4)
        .fluidInputs(fluid('carbon_dioxide') * 1000)
        .fluidInputs(fluid('water') * 2000)
        .fluidOutputs(fluid('cyanamide_slurry') * 1000)
        .duration(100)
        .EUt(VA[LV])
        .buildAndRegister()

    SIFTER.recipeBuilder()
        .fluidInputs(fluid('cyanamide_slurry') * 1000)
        .outputs(metaitem('dustCalcite') * 5)
        .fluidOutputs(fluid('crude_cyanamide_solution') * 1000)
        .duration(100)
        .EUt(VA[LV])
        .buildAndRegister()

    ION_EXCHANGE.recipeBuilder()
        .notConsumable(metaitem('beads.strong_acidic_cation_exchange'))
        .fluidInputs(fluid('crude_cyanamide_solution') * 1000)
        .fluidInputs(fluid('diluted_sulfuric_acid') * 100)
        .fluidOutputs(fluid('cyanamide_solution') * 1000)
        .fluidOutputs(fluid('wastewater') * 100)
        .EUt(VA[MV])
        .duration(100)
        .buildAndRegister()

    CRYSTALLIZER.recipeBuilder()
        .inputs(ore('dustTinySodiumHydroxide'))
        .fluidInputs(fluid('cyanamide_solution') * 2000)
        .outputs(metaitem('dustDicyanamide') * 10)
        .fluidOutputs(fluid('wastewater') * 2000)
        .EUt(VA[LV])
        .duration(100)
        .buildAndRegister()

    AUTOCLAVE.recipeBuilder()
        .inputs(ore('dustDicyanamide') * 10)
        .fluidInputs(fluid('ammonium_nitrate_solution') * 2000)
        .fluidOutputs(fluid('guanidinium_nitrate_solution') * 2000)
        .EUt(VA[LV])
        .duration(100)
        .buildAndRegister()

    CRYSTALLIZER.recipeBuilder()
        .notConsumable(ore('springKanthal'))
        .fluidInputs(fluid('guanidinium_nitrate_solution') * 2000)
        .outputs(metaitem('dustGuanidiniumNitrate') * 14)
        .fluidOutputs(fluid('wastewater') * 2000)
        .EUt(VA[MV])
        .duration(100)
        .buildAndRegister()

    // Malondialdehyde/tetramethoxypropane

    CSTR.recipeBuilder()
        .fluidInputs(fluid('gtfo_hydrogen_cyanide') * 50)
        .fluidInputs(fluid('methanol') * 200)
        .fluidInputs(fluid('hydrogen_chloride') * 50)
        .fluidOutputs(fluid('crude_trimethyl_orthoformate') * 100)
        .duration(5)
        .EUt(VA[MV])
        .buildAndRegister()

    DT.recipeBuilder()
        .fluidInputs(fluid('crude_trimethyl_orthoformate') * 1000)
        .outputs(metaitem('dustAmmoniumChloride') * 6)
        .fluidOutputs(fluid('trimethyl_orthoformate') * 1000)
        .fluidOutputs(fluid('methanol') * 1000)
        .duration(100)
        .EUt(VA[LV])
        .buildAndRegister()

    BR.recipeBuilder()
        .inputs(ore('dustAnyPurityPotassium'))
        .fluidInputs(fluid('methanol') * 1000)
        .outputs(metaitem('dustPotassiumMethoxide') * 6)
        .fluidOutputs(fluid('hydrogen') * 1000)
        .duration(80)
        .EUt(VA[LV])
        .buildAndRegister()

    BR.recipeBuilder()
        .inputs(ore('dustPotassiumMethoxide') * 6)
        .fluidInputs(fluid('acetylene') * 1000)
        .fluidInputs(fluid('methanol') * 2000)
        .fluidOutputs(fluid('crude_methyl_vinyl_ether') * 2000)
        .duration(100)
        .EUt(VA[LV])
        .buildAndRegister()

    DT.recipeBuilder()
        .fluidInputs(fluid('crude_methyl_vinyl_ether') * 2000)
        .outputs(metaitem('dustPotassiumHydroxide') * 6)
        .fluidOutputs(fluid('methanol') * 1000)
        .fluidOutputs(fluid('methyl_vinyl_ether') * 1000)
        .duration(100)
        .EUt(VA[LV])
        .buildAndRegister()

    BR.recipeBuilder()
        .notConsumable(ore('dustIronIiiChloride') * 4)
        .fluidInputs(fluid('trimethyl_orthoformate') * 1000)
        .fluidInputs(fluid('methyl_vinyl_ether') * 1000)
        .fluidOutputs(fluid('tetramethoxypropane') * 1000)
        .duration(40)
        .EUt(VA[LV])
        .buildAndRegister()

    // 2-Aminopyrimidine

    BR.recipeBuilder()
        .inputs(ore('dustGuanidiniumNitrate') * 14)
        .fluidInputs(fluid('tetramethoxypropane') * 1000)
        .outputs(metaitem('dustTwoAminopyrimidine') * 12)
        .fluidOutputs(fluid('methanol') * 4000)
        .fluidOutputs(fluid('nitric_acid') * 1000)
        .duration(100)
        .EUt(120)
        .buildAndRegister()

// Final synthesis

LCR.recipeBuilder()
    .inputs(ore('dustNAcetylsulfanilylChloride') * 22)
    .inputs(ore('dustTwoAminopyrimidine') * 12)
    .fluidInputs(fluid('sodium_hydroxide_solution') * 3000)
    .outputs(metaitem('dustSodiumSulfadiazine') * 32)
    .fluidOutputs(fluid('acidic_wastewater') * 4000)
    .duration(100)
    .EUt(120)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumSulfadiazine') * 27)
    .fluidInputs(fluid('silver_nitrate_solution') * 1000)
    .outputs(metaitem('dustSilverSulfadiazine') * 27)
    .fluidOutputs(fluid('sodium_nitrate_solution') * 1000)
    .duration(100)
    .EUt(120)
    .buildAndRegister()
