import supersymmetry.api.items.ItemMassRegistry

// the numbers here are all completely vibes-based
ItemMassRegistry.setMass(metaitem('susy:solar_furnace'), 120000)
ItemMassRegistry.setMass(item('susy:epoxy_solar_furnace_mirror'), 2400)
ItemMassRegistry.setMass(item('susy:steel_solar_furnace_mirror'), 12800)
ItemMassRegistry.setMass(item('susy:solar_furnace_redirecting_mirror'), 6000)
ItemMassRegistry.setMass(item('susy:solar_furnace_crucible'), 45000)
ItemMassRegistry.setMass(item('susy:heliostat'), 7200)
ItemMassRegistry.setMass(metaitem('platinum_bushing'), 7020)
ItemMassRegistry.setMass(metaitem('stainless_steel_bushing'), 1980)
ItemMassRegistry.setMass(metaitem('platinum_rhodium_bushing'), 6800)
ItemMassRegistry.setMass(metaitem('susy:simple_condenser'), 12490)
ItemMassRegistry.setMass(metaitem('graphite_electrode'), 3417)
ItemMassRegistry.setMass(metaitem('susy:air_disperser'), 2485)
ItemMassRegistry.setMass(metaitem('susy:oxygen_sensor'), 348)
ItemMassRegistry.setMass(metaitem('susy:astronaut_helmet'), 12461)
ItemMassRegistry.setMass(metaitem('susy:astronaut_chestplate'), 41213)
ItemMassRegistry.setMass(metaitem('susy:astronaut_leggings'), 24867)
ItemMassRegistry.setMass(metaitem('susy:astronaut_boots'), 10782)
ItemMassRegistry.setMass(metaitem('mask.simple_solar_panel'), 984)
ItemMassRegistry.setMass(metaitem('circuit.electronic'), 2561)
ItemMassRegistry.setMass(metaitem('circuit.good_electronic'), 8113)
ItemMassRegistry.setMass(metaitem('circuit.basic_integrated'), 842)
ItemMassRegistry.setMass(metaitem('circuit.good_integrated'), 2710)
ItemMassRegistry.setMass(metaitem('circuit.advanced_integrated'), 6781)
ItemMassRegistry.setMass(metaitem('circuit.microprocessor'), 20)
ItemMassRegistry.setMass(metaitem('circuit.processor'), 134)
ItemMassRegistry.setMass(metaitem('circuit.assembly'), 794)
ItemMassRegistry.setMass(metaitem('circuit.workstation'), 2278)
ItemMassRegistry.setMass(metaitem('circuit.mainframe'), 26741)
ItemMassRegistry.setMass(metaitem('circuit.nano_processor'), 156)
ItemMassRegistry.setMass(metaitem('circuit.nano_assembly'), 971)
ItemMassRegistry.setMass(metaitem('circuit.nano_computer'), 2647)
ItemMassRegistry.setMass(metaitem('circuit.nano_mainframe'), 31841)
ItemMassRegistry.setMass(metaitem('susy:drum.pe'), 12701)
ItemMassRegistry.setMass(metaitem('susy:drum.pp'), 15789)
ItemMassRegistry.setMass(metaitem('susy:drum.ptfe'), 16642)
ItemMassRegistry.setMass(metaitem('susy:drum.uhmwpe'), 19784)
ItemMassRegistry.setMass(metaitem('susy:electrolytic_cell'), 94820)
ItemMassRegistry.setMass(metaitem('susy:industrial_sifter'), 75840)
ItemMassRegistry.setMass(metaitem('susy:pressure_swing_adsorber'), 67810)
ItemMassRegistry.setMass(metaitem('susy:fluid_samples_storage'), 8471)
ItemMassRegistry.setMass(metaitem('susy:restrictive_filter'), 942)
ItemMassRegistry.setMass(metaitem('susy:airlock'), 26710)
ItemMassRegistry.setMass(metaitem('susy:data_card.master_blueprint'), 1672)
ItemMassRegistry.setMass(metaitem('susy:rocket_configurer'), 674)
ItemMassRegistry.setMass(metaitem('susy:solar_panel.lv'), 5487)
ItemMassRegistry.setMass(metaitem('susy:solar_panel.mv'), 6914)
ItemMassRegistry.setMass(metaitem('susy:solar_panel.moon'), 21784)
ItemMassRegistry.setMass(metaitem('susy:quarry'), 7348110)
ItemMassRegistry.setMass(metaitem('susy:reaction_furnace'), 78971)
ItemMassRegistry.setMass(metaitem('susy:dumper'), 15746)
ItemMassRegistry.setMass(metaitem('susy:lunar_bucket_wheel_excavator'), 17874205)
ItemMassRegistry.setMass(metaitem('susy:lunar_launch_complex'), 29874812)
ItemMassRegistry.setMass(metaitem('susy:mixer_settler_v2'), 58743567)
ItemMassRegistry.setMass(metaitem('susy:phase_separator'), 18540)
ItemMassRegistry.setMass(metaitem('susy:high_pressure_cryogenic_distillation_plant'), 267840)
ItemMassRegistry.setMass(metaitem('susy:clarifier'), 187415)
ItemMassRegistry.setMass(metaitem('susy:redstone_controller'), 4581)
ItemMassRegistry.setMass(metaitem('susy:froth_flotation_tank'), 297810)
ItemMassRegistry.setMass(item('susy:spacecraft_instrument', 10), 1500000)

def tiers = [
    [tierName: 'lv', massMult: 2],
    [tierName: 'mv', massMult: 1.4],
    [tierName: 'hv', massMult: 3],
    [tierName: 'ev', massMult: 1],
    [tierName: 'iv', massMult: 5]
]

// GT machines already have masses defined, susy ones don't
tiers.each { tier ->
    ItemMassRegistry.setMass(metaitem('susy:roaster.' + tier.tierName), (int) Math.round(27811 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:vacuum_chamber.' + tier.tierName), (int) Math.round(59412 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:continuous_stirred_tank_reactor.' + tier.tierName), (int) Math.round(25745 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:fixed_bed_reactor.' + tier.tierName), (int) Math.round(24842 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:trickle_bed_reactor.' + tier.tierName), (int) Math.round(31784 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:crystallizer.' + tier.tierName), (int) Math.round(34674 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:bubble_column_reactor.' + tier.tierName), (int) Math.round(45812 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:dryer.' + tier.tierName), (int) Math.round(34571 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:uv_light_box.' + tier.tierName), (int) Math.round(47845 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:cvd.' + tier.tierName), (int) Math.round(57841 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:ion_implanter.' + tier.tierName), (int) Math.round(47846 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:batch_reactor.' + tier.tierName), (int) Math.round(36481 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:ion_exchange_column.' + tier.tierName), (int) Math.round(42484 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:zone_refiner.' + tier.tierName), (int) Math.round(39850 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:tube_furnace.' + tier.tierName), (int) Math.round(34781 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:sputter_deposition.' + tier.tierName), (int) Math.round(59910 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:fluid_compressor.' + tier.tierName), (int) Math.round(37419 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:fluid_decompressor.' + tier.tierName), (int) Math.round(37420 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:weapons_factory.' + tier.tierName), (int) Math.round(67841 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:electrostatic_separator.' + tier.tierName), (int) Math.round(26840 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:polishing_machine.' + tier.tierName), (int) Math.round(36897 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:textile_spinner.' + tier.tierName), (int) Math.round(29441 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:resistance_furnace.' + tier.tierName), (int) Math.round(34815 * tier.massMult))
    ItemMassRegistry.setMass(metaitem('susy:ald.' + tier.tierName), (int) Math.round(78421 * tier.massMult))
    if (tier.tierName == 'lv' || tier.tierName == 'mv' || tier.tierName == 'hv' || tier.tierName == 'ev') {
        ItemMassRegistry.setMass(metaitem('susy:latex_collector.' + tier.tierName), (int) Math.round(39841 * tier.massMult))
        ItemMassRegistry.setMass(metaitem('susy:vulcanizing_press.' + tier.tierName), (int) Math.round(34849 * tier.massMult))
        ItemMassRegistry.setMass(metaitem('susy:incinerator.' + tier.tierName), (int) Math.round(25718 * tier.massMult))
        ItemMassRegistry.setMass(metaitem('susy:screen_printer.' + tier.tierName), (int) Math.round(48410 * tier.massMult))
    }
}

