import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// Methanol

FIXED_BR.recipeBuilder()
    .fluidInputs(fluid('hydrogen_rich_syngas') * 4800)
    .fluidInputs(fluid('carbon_monoxide') * 500)
    .notConsumable(metaitem('catalystBedCopperZincChromiumOxide'))
    .fluidOutputs(fluid('methanol') * 1000)
    .duration(4)
    .EUt(40)
    .buildAndRegister()

FIXED_BR.recipeBuilder()
    .fluidInputs(fluid('carbon_monoxide') * 1000)
    .fluidInputs(fluid('hot_hp_hydrogen') * 4000)
    .notConsumable(metaitem('catalystBedCopperZincChromiumOxide'))
    .fluidOutputs(fluid('methanol') * 1000)
    .duration(4)
    .EUt(40)
    .buildAndRegister()

FIXED_BR.recipeBuilder()
    .fluidInputs(fluid('monoxide_rich_syngas') * 5000)
    .notConsumable(metaitem('catalystBedCopperZincChromiumOxide'))
    .fluidOutputs(fluid('methanol') * 1000)
    .duration(4)
    .EUt(40)
    .buildAndRegister()

FIXED_BR.recipeBuilder()
    .fluidInputs(fluid('carbon_dioxide') * 1000)
    .fluidInputs(fluid('hot_hp_hydrogen') * 6000)
    .notConsumable(metaitem('catalystBedCopperZincChromiumOxide'))
    .fluidOutputs(fluid('methanol') * 1000)
    .fluidOutputs(fluid('dense_steam') * 1000)
    .duration(8)
    .EUt(40)
    .buildAndRegister()

// Ethanol

DT.recipeBuilder()
    .fluidInputs(fluid('impure_ethanol') * 2000)
    .outputs(metaitem('dustWood'))
    .fluidOutputs(fluid('fusel_oil') * 20)
    .fluidOutputs(fluid('water') * 1280)
    .fluidOutputs(fluid('ethanol_water_azeotrope') * 700)
    .duration(50)
    .EUt(VA[LV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('ethanol_water_azeotrope') * 700)
    .fluidInputs(fluid('toluene') * 10)
    .fluidOutputs(fluid('ethanol') * 630)
    .duration(250)
    .EUt(VA[ULV])
    .buildAndRegister()

SIEVE_DT.recipeBuilder()
    .fluidInputs(fluid('ethanol_water_azeotrope') * 700)
    .notConsumable(fluid('toluene') * 10)
    .fluidOutputs(fluid('water') * 70)
    .fluidOutputs(fluid('ethanol') * 630)
    .duration(50)
    .EUt(VA[LV])
    .buildAndRegister()

SIFTER.recipeBuilder()
    .fluidInputs(fluid('ethanol_water_azeotrope') * 1000)
    .inputs(ore('dustMolecularSieveA'))
    .fluidOutputs(fluid('ethanol') * 900)
    .outputs(metaitem('dustWetMolecularSieveA'))
    .EUt(VA[LV])
    .duration(200)
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('fusel_oil') * 1000)
    .fluidOutputs(fluid('isoamyl_alcohol') * 615)
    .fluidOutputs(fluid('n_butanol') * 10)
    .fluidOutputs(fluid('isobutyl_alcohol') * 155)
    .fluidOutputs(fluid('water') * 110)
    .fluidOutputs(fluid('n_propanol') * 10)
    .fluidOutputs(fluid('ethanol_water_azeotrope') * 100)
    .duration(50)
    .EUt(VA[LV])
    .buildAndRegister()

    // Ethanol from ethylene

    CHEMICAL_BATH.recipeBuilder()
        .fluidInputs(fluid('phosphoric_acid') * 500)
        .inputs(ore('dustSilicaGel'))
        .outputs(metaitem('dustPhosphoricAcidSilicaGel'))
        .duration(80)
        .EUt(VA[LV])
        .buildAndRegister()

    FLUIDIZED_BR.recipeBuilder()
        .fluidInputs(fluid('ethylene') * 50)
        .fluidInputs(fluid('dense_steam') * 50)
        .notConsumable(metaitem('dustPhosphoricAcidSilicaGel'))
        .fluidOutputs(fluid('ethanol') * 50)
        .duration(5)
        .EUt(VA[HV])
        .buildAndRegister()

    FIXED_BR.recipeBuilder()
        .fluidInputs(fluid('gtfo_acetaldehyde') * 100)
        .fluidInputs(fluid('hydrogen') * 100)
        .notConsumable(ore('catalystBedSupportedPlatinum'))
        .fluidOutputs(fluid('ethanol') * 100)
        .duration(5)
        .EUt(VA[LV])
        .buildAndRegister()

// C3 alcohols

    // n-Propanol

    BR.recipeBuilder()
        .inputs(ore('dustDicobaltOctacarbonyl') * 18)
        .fluidInputs(fluid('hydrogen') * 2000)
        .fluidInputs(fluid('carbon_monoxide') * 1000)
        .fluidInputs(fluid('ethylene') * 1000)
        .fluidOutputs(fluid('propanal_mixture') * 1000)
        .EUt(VA[HV])
        .duration(80)
        .buildAndRegister()

    DISTILLERY.recipeBuilder()
        .fluidInputs(fluid('propanal_mixture') * 1000)
        .outputs(metaitem('dustDicobaltOctacarbonyl') * 18)
        .fluidOutputs(fluid('propionaldehyde') * 800)
        .EUt(VA[HV])
        .duration(80)
        .buildAndRegister()

    FIXED_BR.recipeBuilder()
        .fluidInputs(fluid('propionaldehyde') * 50)
        .fluidInputs(fluid('hydrogen') * 100)
        .notConsumable(metaitem('catalystBedSupportedPlatinum'))
        .fluidOutputs(fluid('n_propanol') * 50)
        .EUt(VA[HV])
        .duration(4)
        .buildAndRegister()

    // Isopropyl alcohol (IPA)

    CSTR.recipeBuilder()
        .fluidInputs(fluid('propene') * 50)
        .fluidInputs(fluid('water') * 100)
        .fluidInputs(fluid('sulfuric_acid') * 50)
        .fluidOutputs(fluid('hydrated_propene') * 150)
        .duration(3)
        .EUt(VA[MV])
        .buildAndRegister();

    SIEVE_DT.recipeBuilder()
        .notConsumable(fluid('cyclohexane') * 100)
        .fluidInputs(fluid('hydrated_propene') * 3000)
        .fluidOutputs(fluid('diluted_sulfuric_acid') * 2000)
        .fluidOutputs(fluid('isopropyl_alcohol') * 1000)
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister();

    TBR.recipeBuilder()
        .notConsumable(ore('dustActivatedRaneyNickel'))
        .fluidInputs(fluid('acetone') * 50)
        .fluidInputs(fluid('hydrogen') * 100)
        .fluidOutputs(fluid('isopropyl_alcohol_solution') * 100)
        .duration(10)
        .EUt(VA[MV])
        .buildAndRegister();

    SIEVE_DT.recipeBuilder()
        .notConsumable(fluid('cyclohexane') * 100)
        .fluidInputs(fluid('isopropyl_alcohol_solution') * 2000)
        .fluidOutputs(fluid('water') * 1000)
        .fluidOutputs(fluid('isopropyl_alcohol') * 1000)
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister();

// C4 alcohols

    // n-Butanol

    FIXED_BR.recipeBuilder()
        .notConsumable(metaitem('catalystBedSupportedPlatinum'))
        .fluidInputs(fluid('butyraldehyde') * 50)
        .fluidInputs(fluid('hydrogen') * 100)
        .fluidOutputs(fluid('n_butanol') * 50)
        .duration(5)
        .EUt(VA[MV])
        .buildAndRegister()

    // Isobutyl alcohol

    BR.recipeBuilder()
        .fluidInputs(fluid('isobutyraldehyde') * 1000)
        .fluidInputs(fluid('hydrogen') * 2000)
        .notConsumable(metaitem('catalystBedSupportedPlatinum'))
        .fluidOutputs(fluid('isobutyl_alcohol') * 1000)
        .EUt(VA[HV])
        .duration(80)
        .buildAndRegister()

// n-Pentanol

REACTION_FURNACE.recipeBuilder()
    .inputs(metaitem('dustDicobaltOctacarbonyl') * 18)
    .fluidInputs(fluid('hot_hp_hydrogen') * 2000)
    .fluidInputs(fluid('carbon_monoxide') * 1000)
    .fluidInputs(fluid('one_butene') * 1000)
    .fluidOutputs(fluid('pentanal_mixture') * 1000)
    .EUt(VA[HV])
    .duration(80)
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('pentanal_mixture') * 1000)
    .outputs(metaitem('dustDicobaltOctacarbonyl') * 18)
    .fluidOutputs(fluid('valeraldehyde') * 800)
    .EUt(VA[HV])
    .duration(80)
    .buildAndRegister()

FIXED_BR.recipeBuilder()
    .fluidInputs(fluid('valeraldehyde') * 50)
    .fluidInputs(fluid('hydrogen') * 100)
    .notConsumable(metaitem('catalystBedSupportedPlatinum'))
    .fluidOutputs(fluid('n_pentanol') * 50)
    .EUt(VA[HV])
    .duration(4)
    .buildAndRegister()

// Isodecanol

FIXED_BR.recipeBuilder()
    .notConsumable(metaitem('catalystBedSupportedPolyphosphoricAcid'))
    .fluidInputs(fluid('propene') * 150)
    .fluidOutputs(fluid('tripropylene') * 50)
    .duration(5)
    .EUt(VA[LV])
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .inputs(metaitem('dustDicobaltOctacarbonyl') * 18)
    .fluidInputs(fluid('hot_hp_hydrogen') * 2000)
    .fluidInputs(fluid('carbon_monoxide') * 1000)
    .fluidInputs(fluid('tripropylene') * 1000)
    .fluidOutputs(fluid('isodecanal_mixture') * 1000)
    .EUt(VA[HV])
    .duration(80)
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('isodecanal_mixture') * 1000)
    .outputs(metaitem('dustDicobaltOctacarbonyl') * 18)
    .fluidOutputs(fluid('isodecanal') * 500)
    .EUt(VA[HV])
    .duration(80)
    .buildAndRegister()

FIXED_BR.recipeBuilder()
    .fluidInputs(fluid('isodecanal') * 50)
    .fluidInputs(fluid('hydrogen') * 100)
    .notConsumable(metaitem('catalystBedSupportedPlatinum'))
    .fluidOutputs(fluid('isodecanol') * 50)
    .EUt(VA[HV])
    .duration(4)
    .buildAndRegister()

// Fatty alcohols (Ziegler-Alfol process)

CSTR.recipeBuilder()
    .fluidInputs(fluid('triethylaluminium') * 25)
    .fluidInputs(fluid('ethylene') * 300)
    .fluidInputs(fluid('diethyl_ether') * 50)
    .fluidOutputs(fluid('alfol_trialkylaluminium_mixture') * 50)
    .duration(10)
    .EUt(VA[LV])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .fluidInputs(fluid('alfol_trialkylaluminium_mixture') * 1000)
    .fluidInputs(fluid('oxygen') * 3000)
    .fluidOutputs(fluid('aluminium_alkoxide_solution') * 1000)
    .duration(500)
    .EUt(VA[LV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('aluminium_alkoxide_solution') * 1000)
    .outputs(metaitem('dustAluminiumAlkoxideMixture'))
    .fluidOutputs(fluid('diethyl_ether') * 1000)
    .duration(500)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustAluminiumAlkoxideMixture'))
    .fluidInputs(fluid('water') * 3000)
    .outputs(metaitem('dustAluminiumHydroxide') * 7)
    .fluidOutputs(fluid('ziegler_alfol_mixture') * 3000)
    .duration(500)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder() //SCHULZ FLORY DISTRIBUTION, p = 0.73, ROUNDED TO NEAREST 5s, TRUNCATED
    .fluidInputs(fluid('ziegler_alfol_mixture') * 1000)
    .fluidOutputs(fluid('n_hexadecanol') * 30)
    .fluidOutputs(fluid('n_tetradecanol') * 45)
    .fluidOutputs(fluid('n_dodecanol') * 60)
    .fluidOutputs(fluid('n_decanol') * 90)
    .fluidOutputs(fluid('n_octanol') * 115)
    .fluidOutputs(fluid('n_hexanol') * 150)
    .fluidOutputs(fluid('n_butanol') * 215)
    .fluidOutputs(fluid('ethanol') * 295)
    .duration(166)
    .EUt(VA[LV])
    .buildAndRegister()