import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// Formic acid

BR.recipeBuilder()
    .inputs(ore('dustAnyPuritySodium'))
    .fluidInputs(fluid('methanol') * 1000)
    .outputs(metaitem('dustSodiumMethoxide') * 6)
    .fluidOutputs(fluid('hydrogen') * 1000)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

BCR.recipeBuilder()
    .inputs(ore('dustSodiumMethoxide'))
    .fluidInputs(fluid('polyethylene_glycol') * 50)
    .fluidInputs(fluid('methanol') * 1000)
    .fluidInputs(fluid('carbon_monoxide') * 1000)
    .fluidOutputs(fluid('methyl_formate_solution') * 1000)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

CSTR.recipeBuilder()
    .notConsumable(ore('springCupronickel'))
    .fluidInputs(fluid('methyl_formate_solution') * 300)
    .fluidInputs(fluid('sulfuric_acid') * 50)
    .fluidOutputs(fluid('neutralized_methyl_formate_solution') * 300)
    .duration(4)
    .EUt(VA[LV])
    .buildAndRegister()

CSTR.recipeBuilder()
    .fluidInputs(fluid('water') * 150)
    .fluidInputs(fluid('neutralized_methyl_formate_solution') * 50)
    .fluidInputs(fluid('sulfuric_acid') * 50)
    .fluidOutputs(fluid('hydrolyzed_methyl_formate_solution') * 200)
    .duration(4)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('hydrolyzed_methyl_formate_solution') * 4000)
    .chancedOutput(metaitem('dustSodiumSulfate'), 5250, 0)
    .fluidOutputs(fluid('sulfuric_acid') * 1000)
    .fluidOutputs(fluid('polyethylene_glycol') * 50)
    .fluidOutputs(fluid('formic_acid_water_azeotrope') * 1000)
    .fluidOutputs(fluid('water') * 2600)
    .fluidOutputs(fluid('methanol') * 600)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

VACUUM_DT.recipeBuilder()
    .fluidInputs(fluid('formic_acid_water_azeotrope') * 1000)
    .fluidOutputs(fluid('formic_acid') * 600)
    .fluidOutputs(fluid('water') * 400)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

// Acetic acid (biological)

FERMENTER.recipeBuilder()
    .fluidInputs(fluid('ethanol') * 8000)
    .fluidInputs(fluid('oxygen') * 4000)
    .fluidOutputs(fluid('vinegar') * 16000)
    .duration(2400)
    .EUt(16)
    .buildAndRegister()

FERMENTER.recipeBuilder()
    .fluidInputs(fluid('ethanol') * 8000)
    .fluidInputs(fluid('air') * 12000)
    .fluidOutputs(fluid('vinegar') * 16000)
    .duration(2400)
    .EUt(16)
    .buildAndRegister()

FERMENTER.recipeBuilder()
    .fluidInputs(fluid('impure_ethanol') * 16000)
    .fluidInputs(fluid('oxygen') * 4000)
    .fluidOutputs(fluid('vinegar') * 16000)
    .duration(2400)
    .EUt(16)
    .buildAndRegister()

FERMENTER.recipeBuilder()
    .fluidInputs(fluid('impure_ethanol') * 16000)
    .fluidInputs(fluid('air') * 12000)
    .fluidOutputs(fluid('vinegar') * 16000)
    .duration(2400)
    .EUt(16)
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('vinegar') * 2000)
    .outputs(metaitem('dustWood'))
    .fluidOutputs(fluid('acetic_acid') * 400)
    .fluidOutputs(fluid('water') * 1600)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('gtfo_apple_cider') * 2000)
    .fluidOutputs(fluid('acetic_acid') * 400)
    .fluidOutputs(fluid('water') * 1600)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

// Acetic acid (chemical)

FIXED_BR.recipeBuilder()
    .fluidInputs(fluid('ethylene') * 100)
    .fluidInputs(fluid('oxygen') * 100)
    .notConsumable(ore('catalystBedPlatinum'))
    .fluidOutputs(fluid('gtfo_acetaldehyde') * 100)
    .duration(10)
    .EUt(VA[LV])
    .buildAndRegister()

FIXED_BR.recipeBuilder()
    .fluidInputs(fluid('gtfo_acetaldehyde') * 100)
    .fluidInputs(fluid('oxygen') * 100)
    .notConsumable(ore('catalystBedCobalt'))
    .fluidOutputs(fluid('acetic_acid') * 100)
    .duration(10)
    .EUt(VA[LV])
    .buildAndRegister()

// Cativa Process

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('hexachloroiridic_acid_solution') * 2000)
    .outputs(metaitem('dustHexachloroiridicAcid'))
    .fluidOutputs(fluid('water') * 2000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

LCR.recipeBuilder()
    .fluidInputs(fluid('methanol') * 1000)
    .fluidInputs(fluid('carbon_monoxide') * 1000)
    .fluidOutputs(fluid('acetic_acid') * 1000)
    .notConsumable(ore('dustCativaCatalyst'))
    .duration(20)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustHexachloroiridicAcid') * 9)
    .fluidInputs(fluid('potassium_iodide_solution') * 4000)
    .outputs(metaitem('dustIridiumIodide') * 5)
    .fluidOutputs(fluid('potassium_chloride_solution') * 4000)
    .fluidOutputs(fluid('hydrogen_chloride') * 2000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('phosphorus_trichloride') * 1000)
    .fluidInputs(fluid('chlorobenzene') * 3000)
    .inputs(ore('dustAnyPuritySodium') * 6)
    .outputs(metaitem('dustTriphenylphosphine'))
    .outputs(metaitem('dustSalt') * 12)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustTriphenylphosphine'))
    .fluidInputs(fluid('chlorine') * 2000)
    .outputs(metaitem('dustTriphenylphosphineDichloride'))
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

LCR.recipeBuilder()
    .inputs(ore('dustTriphenylphosphineDichloride') * 2)
    .inputs(ore('dustTriphenylphosphine'))
    .fluidInputs(fluid('hydroxylamine') * 1000)
    .fluidInputs(fluid('hydrogen_chloride') * 1000)
    .outputs(metaitem('dustBistriphenylphosphineiminiumChloride'))
    .outputs(metaitem('dustTriphenylphosphineOxide'))
    .fluidOutputs(fluid('hydrogen_chloride') * 4000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustIridiumIodide') * 5)
    .fluidInputs(fluid('dimethylformamide') * 1000)
    .fluidInputs(fluid('carbon_monoxide') * 1000)
    .fluidOutputs(fluid('cativa_catalyst_preparation') * 1000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('cativa_catalyst_preparation') * 500)
    .inputs(ore('dustBistriphenylphosphineiminiumChloride'))
    .fluidOutputs(fluid('cativa_catalyst_solution') * 500)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

DRYER.recipeBuilder()
    .fluidInputs(fluid('cativa_catalyst_solution') * 1000)
    .outputs(metaitem('dustCativaCatalyst') * 10)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

// Fatty acids

    // Oleic/linoleic acid

    AUTOCLAVE.recipeBuilder()
        .fluidInputs(fluid('distilled_water') * 3000)
        .fluidInputs(fluid('seed_oil') * 1000)
        .fluidOutputs(fluid('glycerol') * 1000)
        .fluidOutputs(fluid('fatty_acid_solution') * 3000)
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()

    CRYSTALLIZER.recipeBuilder()
        .fluidInputs(fluid('fatty_acid_solution') * 1000)
        .fluidInputs(fluid('methanol') * 1000)
        .inputs(ore('dustUrea'))
        .fluidOutputs(fluid('oleic_acid_solution') * 1000)
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()

    CRYSTALLIZER.recipeBuilder()
        .fluidInputs(fluid('oleic_acid_solution') * 1000)
        .outputs(metaitem('dustOleicAcid'))
        .fluidOutputs(fluid('methanol') * 1000)
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()

    // Liquid Oleic Acid * 144
    mods.gregtech.extractor.removeByInput(30, [metaitem('dustOleicAcid')], null)

    EXTRACTOR.recipeBuilder()
        .inputs(ore('dustOleicAcid'))
        .fluidOutputs(fluid('oleic_acid') * 1000)
        .duration(5)
        .EUt(VA[LV])
        .buildAndRegister()

    MIXER.recipeBuilder()
        .fluidInputs(fluid('sodium_hydroxide_solution') * 1000)
        .inputs(ore('dustOleicAcid'))
        .fluidOutputs(fluid('alkaline_sodium_oleate_solution') * 1000)
        .EUt(VA[LV])
        .duration(80)
        .buildAndRegister()

    // Coconut acids (majority saturated)

    furnace.add(metaitem('gregtechfoodoption:component.coconut'), metaitem('copra'))

    EXTRACTOR.recipeBuilder()
        .inputs(metaitem('copra'))
        .fluidOutputs(fluid('coconut_oil') * 50)
        .EUt(VA[LV])
        .duration(80)
        .buildAndRegister()

    AUTOCLAVE.recipeBuilder()
        .fluidInputs(fluid('distilled_water') * 3000)
        .fluidInputs(fluid('coconut_oil') * 1000)
        .fluidOutputs(fluid('glycerol') * 1000)
        .fluidOutputs(fluid('coconut_acid') * 3000)
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()
    
    SIEVE_DT.recipeBuilder()
        .fluidInputs(fluid('dense_steam') * 1000)
        .fluidInputs(fluid('coconut_acid') * 1000)
        .fluidOutputs(fluid('oleic_acid') * 75)
        .fluidOutputs(fluid('palmitic_acid') * 105)
        .fluidOutputs(fluid('myristic_acid') * 175)
        .fluidOutputs(fluid('lauric_acid') * 485)
        .fluidOutputs(fluid('capric_acid') * 85)
        .fluidOutputs(fluid('caprylic_acid') * 75)
        .duration(80)
        .EUt(VA[LV])
        .buildAndRegister()
