import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// Ethylene oxide

FIXED_BR.recipeBuilder()
    .fluidInputs(fluid('ethylene') * 50)
    .fluidInputs(fluid('oxygen') * 75)
    .notConsumable(ore('catalystBedSupportedSilver'))
    .fluidOutputs(fluid('impure_ethylene_oxide') * 65)
    .EUt(VA[LV])
    .duration(10)
    .buildAndRegister()

BCR.recipeBuilder()
    .fluidInputs(fluid('impure_ethylene_oxide') * 65)
    .fluidInputs(fluid('water') * 40)
    .fluidOutputs(fluid('ethylene_oxide') * 45)
    .fluidOutputs(fluid('wastewater') * 50)
    .EUt(VA[LV])
    .duration(5)
    .buildAndRegister()

// Propylene oxide

CSTR.recipeBuilder()
    .fluidInputs(fluid('propene') * 100)
    .fluidInputs(fluid('chlorine') * 100)
    .fluidInputs(fluid('water') * 50)
    .fluidOutputs(fluid('propylene_chlorohydrin') * 100)
    .duration(5)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustCalciumHydroxide') * 5)
    .fluidInputs(fluid('propylene_chlorohydrin') * 2000)
    .fluidOutputs(fluid('propylene_oxide_solution') * 2000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('propylene_oxide_solution') * 2000)
    .outputs(metaitem('dustCalciumChloride') * 3)
    .fluidOutputs(fluid('water') * 2000)
    .fluidOutputs(fluid('propylene_oxide') * 2000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

// Epichlorohydrin

CSTR.recipeBuilder()
    .fluidInputs(fluid('glycerol') * 50)
    .fluidInputs(fluid('hydrogen_chloride') * 100)
    .fluidInputs(fluid('acetic_acid') * 10)
    .fluidOutputs(fluid('chlorinated_glycerol') * 160)
    .duration(5)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('chlorinated_glycerol') * 3200)
    .inputs(ore('dustSodiumHydroxide') * 3)
    .fluidOutputs(fluid('epichlorohydrin_solution') * 4200)
    .duration(120)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('epichlorohydrin_solution') * 4200)
    .fluidOutputs(fluid('acetic_acid') * 200)
    .fluidOutputs(fluid('epichlorohydrin') * 1000)
    .fluidOutputs(fluid('water') * 3000)
    .outputs(metaitem('dustSalt') * 2)
    .duration(120)
    .EUt(VA[LV])
    .buildAndRegister()

BCR.recipeBuilder()
    .fluidInputs(fluid('allyl_chloride') * 50)
    .fluidInputs(fluid('hypochlorous_acid') * 50)
    .fluidOutputs(fluid('dichloropropanol_mixture') * 50)
    .duration(5)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('dichloropropanol_mixture') * 1000)
    .inputs(ore('dustSodiumHydroxide') * 3)
    .fluidOutputs(fluid('diluted_epichlorohydrin') * 2000)
    .duration(120)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('diluted_epichlorohydrin') * 2000)
    .fluidOutputs(fluid('epichlorohydrin') * 1000)
    .fluidOutputs(fluid('water') * 1000)
    .outputs(metaitem('dustSalt') * 2)
    .duration(160)
    .EUt(VA[LV])
    .buildAndRegister()

// Glycidol

CSTR.recipeBuilder()
    .fluidInputs(fluid('allyl_alcohol') * 50)
    .fluidInputs(fluid('peracetic_acid_solution') * 50)
    .fluidOutputs(fluid('glycidol_solution') * 150)
    .duration(20)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('glycidol_solution') * 3000)
    .fluidOutputs(fluid('glycidol') * 1000)
    .fluidOutputs(fluid('diluted_acetic_acid') * 2000)
    .duration(20)
    .EUt(VA[LV])
    .buildAndRegister()

// meta-chloroperoxybenzoic acid (mCPBA) for epoxide synthesis

CSTR.recipeBuilder()
    .notConsumable(ore('springCupronickel'))
    .fluidInputs(fluid('benzotrichloride') * 50)
    .fluidInputs(fluid('distilled_water') * 50)
    .fluidOutputs(fluid('benzoyl_chloride') * 50)
    .fluidOutputs(fluid('hydrogen_chloride') * 100)
    .duration(5)
    .EUt(VA[LV])
    .buildAndRegister()

FIXED_BR.recipeBuilder()
    .notConsumable(ore('catalystBedSupportedAluminiumChloride'))
    .fluidInputs(fluid('benzoyl_chloride') * 50)
    .fluidInputs(fluid('chlorine') * 100)
    .fluidOutputs(fluid('meta_chlorobenzoyl_chloride') * 50)
    .fluidOutputs(fluid('hydrogen_chloride') * 50)
    .duration(5)
    .EUt(VA[LV])
    .buildAndRegister()

LCR.recipeBuilder()
    .inputs(ore('dustSodiumHydroxide') * 6)
    .fluidInputs(fluid('meta_chlorobenzoyl_chloride') * 1000)
    .fluidInputs(fluid('hydrogen_peroxide_solution') * 2000)
    .fluidInputs(fluid('hydrochloric_acid') * 1000)
    .outputs(metaitem('dustMetaChloroperoxybenzoicAcid') * 16)
    .fluidOutputs(fluid('salt_water') * 2000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()