import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// Lubricity Surfactants (SDS, Narrow-chain ethoxylates)

CSTR.recipeBuilder()
    .notConsumable(ore('platePolytetrafluoroethylene') * 6)
    .fluidInputs(fluid('sulfur_trioxide') * 50)
    .fluidInputs(fluid('hydrogen_chloride') * 50)
    .fluidOutputs(fluid('chlorosulfuric_acid') * 50)
    .duration(5)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .notConsumable(ore('platePolytetrafluoroethylene') * 6)
    .fluidInputs(fluid('chlorosulfuric_acid') * 1000)
    .fluidInputs(fluid('n_dodecanol') * 1000)
    .outputs(metaitem('dustHydrogenDodecylSulfate'))
    .fluidOutputs(fluid('hydrogen_chloride') * 1000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('n_dodecanol') * 1000)
    .fluidInputs(fluid('oleum') * 3000)
    .outputs(metaitem('dustDodecylsulfuricAcid'))
    .fluidOutputs(fluid('sulfuric_acid') * 2000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(metaitem('dustDodecylsulfuricAcid'))
    .fluidInputs(fluid('sodium_hydroxide_solution') * 1000)
    .fluidOutputs(fluid('sodium_dodecyl_sulfate_solution') * 1000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()
    
DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 1000)
    .outputs(metaitem('dustSodiumDodecylSulfate'))
    .fluidOutputs(fluid('water') * 2000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustTinySodiumHydroxide'))
    .fluidInputs(fluid('ethylene_oxide') * 1000)
    .fluidInputs(fluid('n_butanol') * 1000)
    .fluidOutputs(fluid('two_butoxyethanol') * 1000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

// Antistatic surfactant (dinonylnaphthalene sulfonate)

BR.recipeBuilder()
    .fluidInputs(fluid('naphthalene') * 1000)
    .fluidInputs(fluid('tripropylene') * 2000)
    .notConsumable(fluid('hydrofluoric_acid') * 100)
    .outputs(metaitem('dustDinonylnaphthalene'))
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustDinonylnaphthalene'))
    .fluidInputs(fluid('oleum') * 3000)
    .outputs(metaitem('dustDinonylnaphthaleneSulfonicAcid'))
    .fluidOutputs(fluid('sulfuric_acid') * 2000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .notConsumable(ore('platePolytetrafluoroethylene') * 6)
    .inputs(ore('dustDinonylnaphthalene'))
    .fluidInputs(fluid('chlorosulfuric_acid') * 1000)
    .outputs(metaitem('dustDinonylnaphthaleneSulfonicAcid'))
    .fluidOutputs(fluid('hydrogen_chloride') * 1000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

// Non-ionic surfactants (alkylphenol ethoxylates)

// Triton X-100

BR.recipeBuilder()
    .fluidInputs(fluid('phenol') * 1000)
    .fluidInputs(fluid('diisobutylene') * 1000)
    .notConsumable(fluid('hydrofluoric_acid') * 100)
    .outputs(metaitem('dustFourTertOctylphenol'))
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

POLYMERIZATION_TANK.recipeBuilder()
    .inputs(ore('dustFourTertOctylphenol'))
    .fluidInputs(fluid('ethylene_oxide') * 10000)
    .fluidInputs(fluid('sodium_hydroxide_solution') * 1000)
    .fluidOutputs(fluid('triton_x_one_hundred_solution') * 2000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('triton_x_one_hundred_solution') * 2000)
    .outputs(metaitem('dustSodiumHydroxide') * 3)
    .fluidOutputs(fluid('triton_x_one_hundred') * 1000)
    .fluidOutputs(fluid('water') * 1000)
    .fluidOutputs(fluid('ethylene_oxide') * 500)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

// Novec FC-4430 Fluorosurfactant

    // Fluoromonomer

    BCR.recipeBuilder()
        .fluidInputs(fluid('ethylene_oxide') * 50)
        .fluidInputs(fluid('methylamine') * 50)
        .fluidInputs(fluid('distilled_water') * 50)
        .fluidOutputs(fluid('n_methylethanolamine_solution') * 100)
        .duration(5)
        .EUt(VA[LV])
        .buildAndRegister()

    DT.recipeBuilder()
        .fluidInputs(fluid('n_methylethanolamine_solution') * 100)
        .fluidOutputs(fluid('n_methylethanolamine') * 50)
        .fluidOutputs(fluid('water') * 50)
        .duration(20)
        .EUt(VA[LV])
        .buildAndRegister()

    LCR.recipeBuilder()
        .notConsumable(fluid('acetonitrile') * 1000)
        .inputs(ore('dustPotassiumCarbonate') * 3)
        .fluidInputs(fluid('perfluorobutanesulfonyl_fluoride') * 1000)
        .fluidInputs(fluid('n_methylethanolamine') * 1000)
        .outputs(metaitem('dustPotassiumFluoride') * 2)
        .outputs(metaitem('dustNHydroxyethylNMethylPerfluorobutanesulfonamide'))
        .fluidOutputs(fluid('carbon_dioxide') * 500)
        .duration(400)
        .EUt(VA[LV])
        .buildAndRegister()

    CSTR.recipeBuilder()
        .fluidInputs(fluid('acrylic_acid') * 50)
        .fluidInputs(fluid('thionyl_chloride') * 50)
        .fluidOutputs(fluid('acryloyl_chloride') * 50)
        .fluidOutputs(fluid('hydrogen_chloride_sulfur_dioxide_mixture') * 100)
        .duration(8)
        .EUt(VA[MV])
        .buildAndRegister()

    LCR.recipeBuilder()
        .notConsumable(fluid('pyridine') * 1000)
        .inputs(ore('dustNHydroxyethylNMethylPerfluorobutanesulfonamide'))
        .fluidInputs(fluid('acryloyl_chloride') * 1000)
        .outputs(metaitem('dustNAcryloxyethylNMethylPerfluorobutanesulfonamide'))
        .fluidOutputs(fluid('hydrogen_chloride') * 1000)
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister()

    // Crosslinker

    LCR.recipeBuilder()
        .notConsumable(fluid('pyridine') * 1000)
        .fluidInputs(fluid('polyethylene_glycol') * 5000) // avg chain length: 5 ethylene glycol units
        .fluidInputs(fluid('acryloyl_chloride') * 1000)
        .fluidOutputs(fluid('polyethylene_glycol_diacrylate') * 1000)
        .fluidOutputs(fluid('hydrogen_chloride') * 1000)
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister()

    // Chain transfer agent

    BR.recipeBuilder()
        .inputs(ore('dustSodiumHydrosulfide'))
        .fluidInputs(fluid('glycidol') * 1000)
        .fluidInputs(fluid('distilled_water') * 2000)
        .fluidOutputs(fluid('thioglycerol_solution') * 2000)
        .duration(200)
        .EUt(VA[LV])
        .buildAndRegister()

    DT.recipeBuilder()
        .fluidInputs(fluid('thioglycerol_solution') * 2000)
        .outputs(metaitem('dustSodiumHydroxide') * 3)
        .fluidOutputs(fluid('thioglycerol') * 1000)
        .fluidOutputs(fluid('water') * 1000)
        .duration(20)
        .EUt(VA[LV])
        .buildAndRegister()

    // Polymerization

    POLYMERIZATION_TANK.recipeBuilder()
        .inputs(ore('dustTinyAzobisisobutyronitrile'))
        .inputs(ore('dustNAcryloxyethylNMethylPerfluorobutanesulfonamide'))
        .fluidInputs(fluid('polyethylene_glycol_diacrylate') * 100)
        .fluidInputs(fluid('thioglycerol') * 300)
        .fluidInputs(fluid('butanone') * 1000)
        .fluidOutputs(fluid('nonionic_fluorosurfactant_solution') * 2000)
        .duration(400)
        .EUt(VA[MV])
        .buildAndRegister()

    DT.recipeBuilder()
        .fluidInputs(fluid('nonionic_fluorosurfactant_solution') * 2000)
        .fluidOutputs(fluid('nonionic_fluorosurfactant') * 1000)
        .fluidOutputs(fluid('butanone') * 1000)
        .duration(40)
        .EUt(VA[LV])
        .buildAndRegister()