import static globals.Globals.*

CSTR = recipemap('continuous_stirred_tank_reactor')
TBR = recipemap('trickle_bed_reactor')
FBR = recipemap('fixed_bed_reactor')
BCR = recipemap('bubble_column_reactor')
BR = recipemap('batch_reactor')
FLUIDIZEDBR = recipemap('fluidized_bed_reactor')
DISTILLATION_TOWER = recipemap('distillation_tower')
DISTILLERY = recipemap('distillery')
ROASTER = recipemap('roaster')
CRYSTALLIZER = recipemap('crystallizer')
MIXER = recipemap('mixer')
DRYER = recipemap('dryer')
CHEMICAL_BATH = recipemap('chemical_bath')
LCR = recipemap('large_chemical_reactor')

CSTR.recipeBuilder()
    .notConsumable(ore('platePolytetrafluoroethylene') * 6)
    .fluidInputs(fluid('sulfur_trioxide') * 50)
    .fluidInputs(fluid('hydrogen_chloride') * 50)
    .fluidOutputs(fluid('chlorosulfuric_acid') * 50)
    .duration(5)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

BR.recipeBuilder()
    .notConsumable(ore('platePolytetrafluoroethylene') * 6)
    .fluidInputs(fluid('chlorosulfuric_acid') * 1000)
    .fluidInputs(fluid('n_dodecanol') * 1000)
    .outputs(metaitem('dustDodecanesulfonicAcid'))
    .fluidOutputs(fluid('hydrogen_chloride') * 1000)
    .duration(100)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(metaitem('dustDodecanesulfonicAcid'))
    .fluidInputs(fluid('sodium_hydroxide_solution') * 1000)
    .fluidOutputs(fluid('sodium_dodecyl_sulfate_solution') * 1000)
    .duration(100)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()
    
DRYER.recipeBuilder()
    .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 1000)
    .outputs(metaitem('dustSalt') * 2)
    .fluidOutputs(fluid('sodium_dodecyl_sulfate') * 144)
    .fluidOutputs(fluid('steam') * 1000)
    .duration(100)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(metaitem('dustSodiumDodecylSulfate'))
    .fluidInputs(fluid('toluene') * 100)
    .fluidOutputs(fluid('lubricity_additive') * 100)
    .duration(100)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()