import globals.Globals

CANNER = recipemap('canner')
FLUID_EXTRACTOR = recipemap('extractor')
BR = recipemap('batch_reactor')
BLENDER = recipemap('blender')
MIXER_SETTLER = recipemap('mixer_settler')

FLUID_EXTRACTOR.recipeBuilder()
    .inputs(metaitem('fuelPelletDepletedBismuth'))
    .fluidOutputs(fluid('irradiated_bismuth') * 144)
    .duration(20)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

BR.recipeBuilder()
    .notConsumable(fluid('nitrogen') * 8000)
    .fluidInputs(fluid('sodium_hydroxide') * 432)
    .fluidInputs(fluid('irradiated_bismuth') * 3600)
    .fluidOutputs(fluid('polonium_rich_sodium_hydroxide') * 576)
    .fluidOutputs(fluid('bismuth') * 3456)
    .duration(100)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('nitric_acid') * 7500)
    .fluidInputs(fluid('polonium_rich_sodium_hydroxide') * 576)
    .fluidOutputs(fluid('polonium_concentrate') * 4250)
    .fluidOutputs(fluid('nitrogen_dioxide') * 3250)
    .duration(100)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BLENDER.recipeBuilder()
    .fluidInputs(fluid('dibutyl_butylphosphonate') * 300)
    .fluidInputs(fluid('kerosene') * 700)
    .fluidOutputs(fluid('polonium_extraction_mixture') * 1000)
    .duration(100)
    .EUt(Globals.voltAmps[4])
    .buildAndRegister()

MIXER_SETTLER.recipeBuilder()
    .fluidInputs(fluid('polonium_concentrate') * 12750)
    .fluidInputs(fluid('polonium_extraction_mixture') * 5000)
    .fluidOutputs(fluid('acidic_wastewater') * 12750)
    .fluidOutputs(fluid('polonium_extract') * 5000)
    .requiredCells(6)
    .duration(100)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

MIXER_SETTLER.recipeBuilder()
    .fluidInputs(fluid('polonium_extract') * 5000)
    .fluidInputs(fluid('distilled_water') * 750)
    .fluidOutputs(fluid('polonium_iv_nitrate_solution') * 750)
    .fluidOutputs(fluid('polonium_extraction_mixture') * 5000)
    .requiredCells(2)
    .duration(100)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .fluidInputs(fluid('polonium_iv_nitrate_solution') * 1000)
    .outputs(metaitem('dustPolonium'))
    .fluidOutputs(fluid('dense_steam') * 1000)
    .fluidOutputs(fluid('nitrogen_dioxide') * 4000)
    .fluidOutputs(fluid('oxygen') * 4000)    
    .duration(100)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()
