import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

BR.recipeBuilder()
    .fluidInputs(fluid('silver_nitrate_solution') * 150)
    .fluidInputs(fluid('sodium_borohydride_solution') * 100)
    .fluidInputs(fluid('polyvinylpyrrolidone_solution') * 225)
    .fluidOutputs(fluid('silver_nanoparticle_suspension') * 475)
    .duration(400)
    .EUt(VA[MV])
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('silver_nanoparticle_suspension') * 25)
    .outputs(metaitem('dustTinySilverNanoparticle') * 1)
    .fluidOutputs(fluid('wastewater') * 24)
    .duration(800)
    .EUt(VA[HV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(metaitem('dustPalladium'))
    .fluidInputs(fluid('nitric_acid') * 2000)
    .fluidOutputs(fluid('palladium_nitrate_solution') * 2000)
    .duration(40)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('palladium_nitrate_solution') * 150)
    .fluidInputs(fluid('sodium_borohydride_solution') * 200)
    .fluidInputs(fluid('polyvinylpyrrolidone_solution') * 225)
    .fluidOutputs(fluid('palladium_nanoparticle_suspension') * 575)
    .duration(400)
    .EUt(VA[MV])
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('palladium_nanoparticle_suspension') * 30)
    .outputs(metaitem('dustTinyPalladiumNanoparticle') * 1)
    .fluidOutputs(fluid('wastewater') * 29)
    .duration(800)
    .EUt(VA[HV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(metaitem('dustTinySilverNanoparticle') * 15)
    .inputs(metaitem('dustTinyPalladiumNanoparticle') * 5)
    .fluidInputs(fluid('ethylene_glycol') * 100)
    .fluidInputs(fluid('ethanolamine') * 5)
    .fluidInputs(fluid('water') * 200)
    .fluidInputs(fluid('ethanol') * 200)
    .fluidOutputs(fluid('agpd_conductive_ink') * 500)
    .duration(40)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('nickel_chloride_solution') * 150)
    .fluidInputs(fluid('sodium_borohydride_solution') * 100)
    .fluidInputs(fluid('polyvinylpyrrolidone_solution') * 225)
    .fluidOutputs(fluid('nickel_nanoparticle_suspension') * 480)
    .duration(400)
    .EUt(VA[MV])
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('nickel_nanoparticle_suspension') * 25)
    .outputs(metaitem('dustTinyNickelNanoparticle') * 1)
    .duration(800)
    .EUt(VA[HV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(metaitem('dustTinyNickelNanoparticle') * 15)
    .fluidInputs(fluid('ethylene_glycol') * 100)
    .fluidInputs(fluid('ethanolamine') * 5)
    .fluidInputs(fluid('water') * 200)
    .fluidInputs(fluid('ethanol') * 200)
    .fluidOutputs(fluid('nickel_conductive_ink') * 500)
    .duration(40)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(metaitem('dustTinyCopper') * 5)
    .inputs(metaitem('dustTinyGlass') * 5)
    .fluidInputs(fluid('polyvinylpyrrolidone_solution') * 500)
    .fluidOutputs(fluid('copper_frit_ink') * 500)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(metaitem('dustTinySilver') * 5)
    .inputs(metaitem('dustTinyGlass') * 5)
    .fluidInputs(fluid('polyvinylpyrrolidone_solution') * 500)
    .fluidOutputs(fluid('silver_frit_ink') * 500)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(metaitem('dustTinyRutheniumIvOxide') * 5)
    .inputs(metaitem('dustTinyGlass') * 5)
    .fluidInputs(fluid('polyvinylpyrrolidone_solution') * 500)
    .fluidOutputs(fluid('thick_film_resistor_ink') * 500)
    .duration(50)
    .EUt(VA[MV])
    .buildAndRegister()
