name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.16.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee07179966698e072c9e8986a41577916a13f849feea4fe77fb5c273bbca5fda"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
