name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.16.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb0f151c7fa425d357d99e7f2c12770f34baa9567d25d2457ff6c208680a12ef"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
