import classes.*;
import net.minecraft.init.Blocks;

MINING_DRILL = recipemap('mining_drill')

MINING_DRILL.recipeBuilder()
        .notConsumable(item('susy:deposit_block'))
        .outputs(metaitem('rock.carbon'))
        .duration(20)
        .EUt(30)
        .buildAndRegister()

MINING_DRILL.recipeBuilder()
        .notConsumable(item('susy:deposit_block', 1))
        .outputs(metaitem('rock.carbonate'))
        .duration(20)
        .EUt(30)
        .buildAndRegister()

MINING_DRILL.recipeBuilder()
        .notConsumable(item('susy:deposit_block', 2))
        .outputs(metaitem('rock.clay'))
        .duration(20)
        .EUt(30)
        .buildAndRegister()

MINING_DRILL.recipeBuilder()
        .notConsumable(item('susy:deposit_block', 3))
        .outputs(metaitem('rock.oxide'))
        .duration(20)
        .EUt(30)
        .buildAndRegister()

MINING_DRILL.recipeBuilder()
        .notConsumable(item('susy:deposit_block', 4))
        .outputs(metaitem('rock.phosphate'))
        .duration(20)
        .EUt(30)
        .buildAndRegister()

MINING_DRILL.recipeBuilder()
        .notConsumable(item('susy:deposit_block', 5))
        .outputs(metaitem('rock.precious'))
        .duration(20)
        .EUt(120)
        .buildAndRegister()

MINING_DRILL.recipeBuilder()
        .notConsumable(item('susy:deposit_block', 6))
        .outputs(metaitem('rock.radioactive'))
        .duration(20)
        .EUt(120)
        .buildAndRegister()

MINING_DRILL.recipeBuilder()
        .notConsumable(item('susy:deposit_block', 7))
        .outputs(metaitem('rock.sedimentary'))
        .duration(20)
        .EUt(30)
        .buildAndRegister()

MINING_DRILL.recipeBuilder()
        .notConsumable(item('susy:deposit_block', 8))
        .outputs(metaitem('rock.silicate'))
        .duration(20)
        .EUt(30)
        .buildAndRegister()

MINING_DRILL.recipeBuilder()
        .notConsumable(item('susy:deposit_block', 9))
        .outputs(metaitem('rock.sulfur'))
        .duration(20)
        .EUt(30)
        .buildAndRegister()