ROASTER = recipemap('roaster')
CRACKER = recipemap('cracker')

// Cracking: Ethane, Propane Butane

ROASTER.recipeBuilder()
    .fluidInputs(fluid('ethane') * 1000)
    .fluidInputs(fluid('hot_hp_steam') * 1000)
    .fluidOutputs(fluid('steamcracked_ethane') * 700)
    .duration(300)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .fluidInputs(fluid('propane') * 1000)
    .fluidInputs(fluid('hot_hp_steam') * 1000)
    .fluidOutputs(fluid('steamcracked_propane') * 700)
    .duration(300)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .fluidInputs(fluid('butane') * 1000)
    .fluidInputs(fluid('hot_hp_steam') * 1000)
    .fluidOutputs(fluid('steamcracked_butane') * 700)
    .duration(300)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

CRACKER.recipeBuilder()
    .fluidInputs(fluid('ethane') * 1000)
    .fluidInputs(fluid('hot_hp_steam') * 1000)
    .fluidOutputs(fluid('steamcracked_ethane') * 1000)
    .duration(80)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

CRACKER.recipeBuilder()
    .fluidInputs(fluid('propane') * 1000)
    .fluidInputs(fluid('hot_hp_steam') * 1000)
    .fluidOutputs(fluid('steamcracked_propane') * 1000)
    .duration(80)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

CRACKER.recipeBuilder()
    .fluidInputs(fluid('butane') * 1000)
    .fluidInputs(fluid('hot_hp_steam') * 1000)
    .fluidOutputs(fluid('steamcracked_butane') * 1000)
    .duration(80)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('steamcracked_ethane') * 1000)
    .fluidOutputs(fluid('ethylene') * 200)
    .fluidOutputs(fluid('methane') * 50)
    .fluidOutputs(fluid('hydrogen') * 750)
    .duration(160)
    .EUt(Globals.voltAmps[1] * 2)
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('steamcracked_propane') * 1000)
    .fluidOutputs(fluid('pyrolysis_gasoline') * 25)
    .fluidOutputs(fluid('butadiene') * 25)
    .fluidOutputs(fluid('propene') * 140)
    .fluidOutputs(fluid('ethylene') * 440)
    .fluidOutputs(fluid('methane') * 460)
    .fluidOutputs(fluid('hydrogen') * 1230)
    .duration(160)
    .EUt(Globals.voltAmps[1] * 2)
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('steamcracked_butane') * 1000)
    .fluidOutputs(fluid('pyrolysis_gasoline') * 25)
    .fluidOutputs(fluid('butadiene') * 25)
    .fluidOutputs(fluid('propene') * 110)
    .fluidOutputs(fluid('ethylene') * 450)
    .fluidOutputs(fluid('methane') * 500)
    .fluidOutputs(fluid('hydrogen') * 1250)
    .duration(160)
    .EUt(Globals.voltAmps[1] * 2)
    .buildAndRegister()