import static prePostInit.Recipemaps.*
import globals.Sintering
import globals.Carbons


import static gregtech.api.GTValues.*
import static gregtech.api.unification.material.Materials.*;
import gregtech.api.unification.material.MarkerMaterials;
import static gregtech.api.unification.ore.OrePrefix.dye;

for (highPurityCombustible in Carbons.highPurityCombustibles()) {
    ADVANCED_ARC_FURNACE.recipeBuilder()
        .inputs(ore('dustChromite'))
        .inputs(ore('dustTinyQuicklime'))
        .inputs(ore(highPurityCombustible.name) * highPurityCombustible.equivalent(4))
        .outputs(metaitem('dustFerrochromium') * 3)
        .fluidOutputs(fluid('carbon_monoxide') * 4000)
        .duration(200 * highPurityCombustible.duration)
        .EUt(VA[MV])
        .buildAndRegister()
}

Sintering.nonPlasmaFuels().each { fuel ->
    ROTARY_KILN.recipeBuilder()
        .inputs(ore('dustChromite') * 2)
        .inputs(ore('dustSodaAsh') * 24)
        .fluidInputs(fluid(fuel.name) * fuel.amountRequired)
        .fluidInputs(fluid('oxygen') * 7010)
        .outputs(metaitem('dustSodiumChromateMixture') * 5)
        .fluidOutputs(fluid('carbon_dioxide') * 4000)
        .duration(400)
        .EUt(VA[MV])
        .buildAndRegister()
}

BR.recipeBuilder()
    .inputs(ore('dustSodiumChromateMixture') * 10)
    .fluidInputs(fluid('distilled_water') * 8000)
    .outputs(metaitem('dustIronIiiOxide') * 10)
    .fluidOutputs(fluid('sodium_chromate_solution') * 8000)
    .duration(800)
    .EUt(VA[MV])
    .buildAndRegister()

BCR.recipeBuilder()
    .fluidInputs(fluid('sodium_chromate_solution') * 100)
    .fluidInputs(fluid('sulfur_trioxide') * 50)
    .fluidOutputs(fluid('sodium_dichromate_solution') * 100)
    .duration(5)
    .EUt(VA[MV])
    .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
    .fluidInputs(fluid('sodium_dichromate_solution') * 2000)
    .outputs(metaitem('dustSodiumDichromate') * 11)
    .fluidOutputs(fluid('diluted_sodium_sulfate_solution') * 2000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustAnyPurityCarbon') * 2)
    .inputs(ore('dustSodiumDichromate') * 11)
    .outputs(metaitem('dustChromiumSodaMixture') * 2)
    .fluidOutputs(fluid('carbon_monoxide') * 1000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustChromiumSodaMixture') * 2)
    .fluidInputs(fluid('water') * 1000)
    .outputs(metaitem('dustChromiumIiiOxide') * 5)
    .fluidOutputs(fluid('soda_ash_solution') * 1000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustChromiumIiiHydroxide') * 14)
    .outputs(metaitem('dustChromiumIiiOxide') * 5)
    .fluidOutputs(fluid('dense_steam') * 3000)
    .EUt(VA[MV])
    .duration(100)
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .inputs(ore('dustAnyPurityAluminium') * 2)
    .inputs(ore('dustChromiumIiiOxide') * 5)
    .outputs(metaitem('dustAlumina') * 5)
    .outputs(metaitem('dustChrome') * 2)
    .EUt(VA[MV])
    .duration(100)
    .buildAndRegister()

BCR.recipeBuilder()
    .fluidInputs(fluid('ammonia') * 100)
    .fluidInputs(fluid('diluted_sulfuric_acid') * 100)
    .fluidOutputs(fluid('ammonium_sulfate_solution') * 50)
    .EUt(VA[MV])
    .duration(5)
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('ammonium_sulfate_solution') * 1000)
    .outputs(metaitem('dustAmmoniumSulfate') * 15)
    .fluidOutputs(fluid('water') * 1000)
    .EUt(VA[MV])
    .duration(5)
    .buildAndRegister()

BR.recipeBuilder()
    .circuitMeta(1)
    .inputs(ore('dustFerrochromium') * 3)
    .inputs(ore('dustAmmoniumSulfate') * 15)
    .fluidInputs(fluid('sulfuric_acid') * 6000)
    .fluidInputs(fluid('distilled_water') * 750)
    .fluidOutputs(fluid('hydrogen') * 2000)
    .fluidOutputs(fluid('dissolved_ferrochromium') * 1000)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('dissolved_ferrochromium') * 1000)
    .fluidInputs(fluid('ammonia') * 4000)
    .outputs(metaitem('dustCrudeAmmoniumIronIiSulfate') * 21)
    .fluidOutputs(fluid('ammonium_chrome_alum_solution') * 750)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('dissolved_ferrochromium') * 1000)
    .fluidInputs(fluid('ammonia') * 4000)
    .fluidInputs(fluid('mohr_mother_liquor') * 250)
    .outputs(metaitem('dustCrudeAmmoniumIronIiSulfate') * 21)
    .fluidOutputs(fluid('ammonium_chrome_alum_solution') * 1000)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustCrudeAmmoniumIronIiSulfate') * 21)
    .fluidInputs(fluid('gtfo_heated_water') * 250)
    .fluidOutputs(fluid('crude_ammonium_iron_ii_sulfate_solution') * 250)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
    .fluidInputs(fluid('crude_ammonium_iron_ii_sulfate_solution') * 250)
    .outputs(metaitem('dustAmmoniumIronIiSulfate') * 21)
    .fluidOutputs(fluid('mohr_mother_liquor') * 250)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustAmmoniumIronIiSulfate') * 21)
    .fluidInputs(fluid('gtfo_heated_water') * 1000)
    .fluidOutputs(fluid('ammonium_iron_ii_sulfate_solution') * 1000)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('ammonia_solution') * 2000)
    .fluidInputs(fluid('crude_ammonium_iron_ii_sulfate_solution') * 1000)
    .outputs(metaitem('dustIronIiHydroxide') * 5)
    .fluidOutputs(fluid('ammonium_sulfate_solution') * 2000)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('warm_water') * 1000)
    .fluidInputs(fluid('ammonium_chrome_alum_solution') * 1000)
    .fluidOutputs(fluid('aged_ammonium_chrome_alum_solution') * 2000)
    .EUt(VA[LV])
    .duration(800)
    .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
    .fluidInputs(fluid('aged_ammonium_chrome_alum_solution') * 2000)
    .outputs(metaitem('dustAmmoniumChromeAlum') * 12)
    .fluidOutputs(fluid('chromium_mother_liquor') * 2000)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('gtfo_heated_water') * 1000)
    .inputs(ore('dustAmmoniumChromeAlum') * 16)
    .fluidOutputs(fluid('purified_ammonium_chrome_alum_solution') * 1000)
    .EUt(VA[LV])
    .duration(800)
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .fluidInputs(fluid('purified_ammonium_chrome_alum_solution') * 1000)
    .fluidInputs(fluid('distilled_water') * 400)
    .notConsumable(metaitem('plateStainlessSteel'))
    .notConsumable(metaitem('plateSilver'))
    .notConsumable(metaitem('foilAsbestos') * 4)
    .chancedOutput(metaitem('dustElectrolyticChromium'), 8000, 0)
    .fluidOutputs(fluid('oxygen') * 1200)
    .fluidOutputs(fluid('chromium_anolyte') * 100)
    .fluidOutputs(fluid('chromium_catholyte') * 100)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('warm_water') * 1000)
    .fluidInputs(fluid('chromium_catholyte') * 1000)
    .fluidOutputs(fluid('aged_ammonium_chrome_alum_solution') * 2000)
    .EUt(VA[LV])
    .duration(800)
    .buildAndRegister()

BCR.recipeBuilder()
    .fluidInputs(fluid('chromium_anolyte') * 100)
    .fluidInputs(fluid('sulfur_dioxide') * 150)
    .fluidOutputs(fluid('reduced_chromium_anolyte') * 100)
    .EUt(VA[LV])
    .duration(10)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustFerrochromium') * 3)
    .inputs(ore('dustAmmoniumSulfate') * 15)
    .fluidInputs(fluid('reduced_chromium_anolyte') * 3000)
    .fluidInputs(fluid('sulfuric_acid') * 6000)
    .fluidInputs(fluid('distilled_water') * 750)
    .fluidOutputs(fluid('hydrogen') * 2000)
    .fluidOutputs(fluid('dissolved_ferrochromium') * 2000)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustFerrochromium') * 3)
    .inputs(ore('dustAmmoniumSulfate') * 15)
    .fluidInputs(fluid('chromium_mother_liquor') * 8000)
    .fluidInputs(fluid('sulfuric_acid') * 6000)
    .fluidInputs(fluid('distilled_water') * 750)
    .fluidOutputs(fluid('hydrogen') * 2000)
    .fluidOutputs(fluid('dissolved_ferrochromium') * 2000)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

VACUUM_CHAMBER.recipeBuilder()
    .fluidInputs(fluid('electrolytic_chromium') * 1440)
    .fluidOutputs(fluid('high_purity_chrome') * 1440)
    .fluidOutputs(fluid('oxygen') * 144)
    .EUt(VA[HV])
    .duration(200)
    .buildAndRegister()

ROASTER.recipeBuilder()
    .circuitMeta(1)
    .inputs(ore('dustChromiumTrioxide') * 8)
    .outputs(metaitem('dustChromiumIiiOxide') * 5)
    .fluidOutputs(fluid('oxygen') * 3000)
    .EUt(VA[MV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustChromiumIiiOxide') * 5)
    .fluidInputs(fluid('nitric_acid') * 6000)
    .fluidOutputs(fluid('chromium_iii_nitrate_solution') * 3000)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodaAsh') * 18)
    .fluidInputs(fluid('chromium_iii_nitrate_solution') * 3000)
    .fluidInputs(fluid('distilled_water') * 3000)
    .outputs(metaitem('dustChromiumIiiCarbonate') * 14)
    .fluidOutputs(fluid('sodium_nitrate_solution') * 6000)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()
