import static globals.Globals.*
import static globals.SinteringGlobals.*

BR = recipemap('batch_reactor')
ROASTER = recipemap('roaster')
CENTRIFUGE = recipemap('centrifuge')
ELECTROLYTIC_CELL = recipemap('electrolyzer')
REACTION_FURNACE = recipemap('reaction_furnace')

//FLUORIDE PROCESS (UNIVERSAL, 90%)
BR.recipeBuilder()
        .fluidInputs(fluid('hexafluorosilicic_acid') * 1000)
        .fluidInputs(fluid('salt_water') * 2000)
        .outputs(metaitem('dustSodiumFluorosilicate') * 9)
        .fluidOutputs(fluid('hydrochloric_acid') * 2000)
        .EUt(120)
        .duration(400)
        .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
        .inputs(metaitem('dustEmerald') * 58)
        .inputs(metaitem('dustSodiumFluorosilicate') * 54)
        .outputs(metaitem('dustFusedBeryl') * 23)
        .fluidOutputs(fluid('silicon_tetrafluoride') * 1000)
        .EUt(120)
        .duration(200)
        .buildAndRegister()

//REGENERATION OF SODIUM FLUOROSILICATE
BR.recipeBuilder()
        .inputs(metaitem('dustSodiumFluoride') * 4)
        .fluidInputs(fluid('silicon_tetrafluoride') * 1000)
        .outputs(metaitem('dustSodiumFluorosilicate') * 9)
        .EUt(120)
        .duration(100)
        .buildAndRegister()

//SEPARATION OF SODIUM FLUOROBERYLLATE
CENTRIFUGE.recipeBuilder()
        .inputs(metaitem('dustFusedBeryl') * 23)
        .fluidInputs(fluid('distilled_water') * 6000)
        .outputs(metaitem('dustAlumina') * 10)
        .outputs(metaitem('dustSiliconDioxide') * 45)
        .fluidOutputs(fluid('sodium_fluoroberyllate_solution') * 5400)
        .EUt(120)
        .duration(300)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(metaitem('dustSodiumHydroxide') * 6)
        .fluidInputs(fluid('sodium_fluoroberyllate_solution') * 1000)
        .fluidInputs(fluid('distilled_water') * 3000)
        .outputs(metaitem('dustBerylliumHydroxide') * 5)
        .fluidOutputs(fluid('sodium_fluoride_solution') * 4000)

ROASTER.recipeBuilder()
        .inputs(metaitem('dustBerylliumHydroxide') * 5)
        .outputs(metaitem('dustBerylliumOxide') * 2)
        .fluidOutputs(fluid('steam') * 1000)
        .EUt(120)
        .duration(80)
        .buildAndRegister()

//BERYLLIUM CHLORIDE ROUTE (TAKES LONGER, EV)
REACTION_FURNACE.recipeBuilder()
        .inputs(metaitem('dustBerylliumOxide') * 2)
        .inputs(metaitem('dustCarbon') * 1)
        .fluidInputs(fluid('chlorine') * 2000)
        .outputs(metaitem('dustBerylliumChloride') * 3)
        .fluidOutputs(fluid('carbon_monoxide') * 1000)
        .EUt(Globals.voltAmps[4])
        .duration(240)
        .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
        .notConsumable(metaitem('graphite_electrode'))
        .notConsumable(metaitem('stickAluminum'))
        .notConsumable(fluid('salt') * 432)
        .fluidInputs(fluid('beryllium_chloride') * 432)
        .fluidOutputs(fluid('chlorine') * 2000)
        .outputs(metaitem('dustBeryllium'))
        .EUt(Globals.voltAmps[4])
        .duration(480)
        .buildAndRegister()

//BERYLLIUM FLUORIDE ROUTE (BYPRODUCTS, MV)
BR.recipeBuilder()
        .fluidInputs(fluid('hexafluorosilicic_acid') * 9)
        .fluidInputs(fluid('ammonia') * 6000)
        .fluidInputs(fluid('distilled_water') * 2000)
        .outputs(metaitem('dustSiliconDioxide') * 3)
        .outputs(metaitem('dustAmmoniumFluoride') * 36)
        .EUt(Globals.voltAmps[2])
        .duration(100)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(metaitem('dustAmmoniumFluoride') * 12)
        .outputs(metaitem('dustAmmoniumBifluoride') * 8)
        .fluidOutputs(fluid('ammonia') * 1000)
        .EUt(Globals.voltAmps[2])
        .duration(100)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(metaitem('dustAmmoniumBifluoride') * 16)
        .inputs(metaitem('dustBerylliumHydroxide') * 5)
        .fluidInputs(fluid('distilled_water') * 1000)
        .fluidOutputs(fluid('impure_ammonium_fluoroberyllate_solution') * 1000)
        .EUt(Globals.voltAmps[2])
        .duration(100)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(metaitem('dustTinySodiumHydroxide'))
        .fluidInputs(fluid('impure_ammonium_fluoroberyllate_solution') * 1000)
        .chancedOutput(metaitem('dustTinyChromiumIiiHydroxide'), 200, 0)
        .fluidOutputs(fluid('ammonium_fluoroberyllate_solution') * 1000)
        .EUt(Globals.voltAmps[2])
        .duration(100)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(metaitem("dustChromiumIiiHydroxide") * 14)
        .outputs(metaitem("dustChromiumTrioxide") * 5)
        .fluidOutputs(fluid("steam") * 3000)
        .EUt(Globals.voltAmps[2])
        .duration(100)
        .buildAndRegister()