ROASTER = recipemap('roaster')
EBF = recipemap('electric_blast_furnace')
BR = recipemap('batch_reactor')
DISTILLERY = recipemap('distillery')

ROASTER.recipeBuilder()
        .inputs(ore('dustGypsum') * 8)
        .outputs(metaitem('dustCalciumSulfate') * 6)
        .fluidOutputs(fluid('steam') * 2000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(ore('dustCalciumSulfate') * 6)
        .outputs(metaitem('dustQuicklime') * 2)
        .fluidOutputs(fluid('sulfur_trioxide') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()