import static globals.Globals.*

import static gregtech.api.unification.material.Materials.*;
import gregtech.api.unification.material.MarkerMaterials;
import static gregtech.api.unification.ore.OrePrefix.dye;

ADVANCED_ARC_FURNACE = recipemap('advanced_arc_furnace')
ARC_FURNACE = recipemap('arc_furnace')
BR = recipemap('batch_reactor')
REACTION_FURNACE = recipemap('reaction_furnace')

ARC_FURNACE.recipeBuilder()
.inputs(ore('dustChromite') * 7)
.inputs(ore('dustCarbon') * 4)
.outputs(ore('dustFerrochromium').first() * 3)
.fluidOutputs(fluid('carbon_monoxide') * 4000)
.duration(200)
.EUt(Globals.voltAmps[2])
.buildAndRegister()

ADVANCED_ARC_FURNACE.recipeBuilder()
.inputs(metaitem('dustChromite') * 28)
.inputs(metaitem('dustSodaAsh') * 48)
.fluidInputs(fluid('oxygen') * 14000)
.outputs(metaitem('dustSodiumChromateMixture') * 10)
.fluidOutputs(fluid('carbon_dioxide') * 8000)
.duration(800)
.EUt(Globals.voltAmps[2])
.buildAndRegister()

BR.recipeBuilder()
.inputs(metaitem('dustSodiumChromateMixture') * 10)
.fluidInputs(fluid('distilled_water') * 8000)
.outputs(metaitem('dustIronIiiOxide') * 10)
.fluidOutputs(fluid('sodium_chromate_solution') * 8000)
.duration(800)
.EUt(Globals.voltAmps[2])
.buildAndRegister()

CSTR.recipeBuilder()
.fluidInputs(fluid('sodium_chromate_solution') * 50)
.fluidInputs(fluid('sulfuric_acid') * 50)
.fluidOutputs(fluid('sodium_dichromate_solution') * 50)
.duration(5)
.EUt(Globals.voltAmps[2])
.buildAndRegister()

DISTILLATION_TOWER.recipeBuilder()
.fluidInputs(fluid('sodium_dichromate_solution') * 1000)
.outputs(metaitem('dustSodiumDichromate') * 11)
.fluidOutputs(fluid('sulfuric_acid') * 1000)
.fluidOutputs(fluid('water') * 1000)
.duration(100)
.EUt(Globals.voltAmps[2])
.buildAndRegister()

ROASTER.recipeBuilder()
.inputs(metaitem('dustCarbon') * 2)
.inputs(metaitem('dustSodiumDichromate') * 11)
.outputs(metaitem('dustChromiumSodaMixture') * 2)
.fluidOutputs(fluid('carbon_monoxide') * 1000)
.duration(100)
.EUt(Globals.voltAmps[2])
.buildAndRegister()

BR.recipeBuilder()
.inputs(metaitem('dustChromiumSodaMixture') * 2)
.fluidInputs(fluid('water') * 1000)
.outputs(metaitem('dustChromiumIiiOxide') * 5)
.fluidOutputs(fluid('soda_ash_solution') * 1000)
.duration(100)
.EUt(Globals.voltAmps[2])
.buildAndRegister()

ROASTER.recipeBuilder()
.inputs(metaitem('dustChromiumIiiHydroxide') * 14)
.outputs(metaitem('dustChromiumIiiOxide') * 5)
.fluidOutputs(fluid('steam') * 3000)
.EUt(Globals.voltAmps[2])
.duration(100)
.buildAndRegister()

REACTION_FURNACE.recipeBuilder()
.inputs(metaitem('dustAluminium') * 2)
.inputs(metaitem('dustChromiumIiiOxide') * 5)
.outputs(metaitem('dustAlumina') * 5)
.outputs(metaitem('dustChrome') * 2)
.EUt(Globals.voltAmps[2])
.duration(100)
.buildAndRegister()