FBR = recipemap('fixed_bed_reactor')
BCR = recipemap('bubble_column_reactor')
DISTILLERY = recipemap('distillery')
BATCH_REACTOR = recipemap('batch_reactor')

//SODIUM CYANIDE
FBR.recipeBuilder()
    .notConsumable(metaitem('catalystBedOxidation'))
    .fluidInputs(fluid('methane') * 100)
    .fluidInputs(fluid('ammonia') * 100)
    .fluidInputs(fluid('oxygen') * 150)
    .fluidOutputs(fluid('hydrogen_cyanide') * 100)
    .fluidOutputs(fluid('water') * 300)
    .duration(6)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

BCR.recipeBuilder()
    .fluidInputs(fluid('sodium_hydroxide_solution') * 50)
    .fluidInputs(fluid('hydrogen_cyanide') * 50)
    .fluidOutputs(fluid('sodium_cyanide_solution') * 50)
    .duration(10)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('sodium_cyanide_solution') * 1000)
    .outputs(ore('dustSodiumCyanide').first() * 3)
    .fluidOutputs(fluid('water') * 2000)
    .duration(60)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

//SODIUM THIOSULFATE
BCR.recipeBuilder()
    .fluidInputs(fluid('soda_ash_solution') * 50)
    .fluidInputs(fluid('sulfur_dioxide') * 50)
    .fluidOutputs(fluid('sodium_sulfite_solution') * 50)
    .fluidOutputs(fluid('carbon_dioxide') * 50)
    .duration(6)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .inputs(ore('dustSulfur'))
    .fluidInputs(fluid('sodium_sulfite_solution') * 1000)
    .fluidOutputs(fluid('sodium_thiosulfate_solution') * 1000)
    .duration(120)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

DISTILLERY.recipeBuilder() 
    .fluidInputs(fluid('sodium_thiosulfate_solution') * 1000)
    .outputs(metaitem('dustSodiumThiosulfate') * 7)
    .fluidOutputs(fluid('water') * 1000)
    .duration(120)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

    