import static globals.Globals.*

BATCH_REACTOR = recipemap('batch_reactor')
CSTR = recipemap('continuous_stirred_tank_reactor')
ROASTER = recipemap('roaster')
ELECTROLYTIC_CELL = recipemap('electrolytic_cell')
MACERATOR = recipemap('macerator')
MIXER = recipemap('mixer')

//NATURAL ELECTRUM PURIFICATION VIA PARTING (PRIMITIVE, 67% EFFICIENCY)
BATCH_REACTOR.recipeBuilder()
    .inputs(ore('dustElectrum') * 6) //Change to "natural" electrum
    .fluidInputs(fluid('nitric_acid') * 4000)
    .fluidInputs(fluid('distilled_water') * 1000)
    .outputs(metaitem('dustGold') * 2)
    .fluidOutputs(fluid('silver_nitrate_solution') * 2000)
    .fluidOutputs(fluid('nitric_oxide') * 1000)
    .duration(360)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

//ADD PLACER DEPOSIT GRAVITY SEPARATION

//MILLER PROCESS (UNIVERSAL, 100%)
BATCH_REACTOR.recipeBuilder()
    .fluidInputs(fluid('electrum') * 1000)
    .fluidInputs(fluid('chlorine') * 500)
    .outputs(metaitem('dustSilverChloride'))
    .fluidOutputs(fluids('gold') * 500)
    .duration(120)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

    //ADD MILLER PROCESS FOR OTHER ELECTROREFINING DORES

//CYANIDATION (UNIVERSAL, 100%)
MACERATOR.recipeBuilder()
    .inputs(item('susy:resource_block:11'))
    .outputs(metaitem('dustGoldConcentrate'))
    .duration(120)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustGoldConcentrate') * 4)
    .fluidInputs(fluid('distilled_water') * 6000)
    .fluidOutputs(fluid('gold_ore_slurry') * 1000)
    .duration(480)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .inputs(ore('dustSodiumCyanide') * 24)
    .inputs(ore('dustTinyQuicklime'))
    .fluidInputs(fluid('gold_ore_slurry') * 1000)
    .fluidInputs(fluid('air') * 9570)
    .outputs(metaitem('dustSand') * 16)
    .fluidOutputs(fluid('gold_leach_solution') * 1000)
    .duration(240)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustCoke'))
    .fluidInputs(fluid('air') * 1000)
    .outputs(metaitem('dustActivatedCarbon'))
    .duration(1440)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .inputs(ore('dustActivatedCarbon') * 4)
    .fluidInputs(fluid('gold_leach_solution' * 1000))
    .outputs(metaitem('dustLoadedCarbon') * 4)
    .fluidOutputs(fluid('sodium_hydroxide_solution') * 4000)
    .duration(240)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .inputs(ore('dustTinySodiumCyanide'))
    .inputs(ore('dustTinySodiumHydroxide'))
    .fluidInputs(fluid('distilled_water') * 1000)
    .fluidOutputs(fluid('gold_eluent'))
    .duration(120)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .inputs(ore('dustLoadedActivatedCarbon'))
    .fluidInputs(fluid('gold_eluent') * 1000)
    .outputs(metaitem('dustSpentActivatedCarbon'))
    .fluidOutputs(fluid('gold_elute_solution') * 1000)
    .duration(480)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .inputs(ore('dustSpentActivatedCarbon'))
    .fluidInputs(fluid('hydrochloric_acid') * 50)
    .outputs(metaitem('dustWashedActivatedCarbon'))
    .fluidOutputs(fluid('hydrochloric_acid' * 45))
    .duration(120)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustWashedActivatedCarbon'))
    .fluidInputs(fluid('air') * 100)
    .outputs(metaitem('dustActivatedCarbon'))  
    .duration(120)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()  

ELECTROLYTIC_CELL.recipeBuilder()
    .inputs(ore('fineWireSteel') * 8)
    .notConsumable(ore('plateStainlessSteel') * 8)
    .notConsumable(ore('platePolyethylene') * 8)
    .fluidInputs(fluid('gold_elute_solution') * 1000)
    .outputs(metaitem('fineWireGoldPlatedSteel') * 8)
    .fluidOutputs(fluid('gold_eluent') * 1000)
    .duration(240)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .inputs(ore('findWireGoldPlatedSteel') * 24)
    .fluidInputs(fluid('nitric_acid') * 8000)
    .outputs(metaitem('dustGold') * 3)
    .fluidOutputs(fluid('nitric_oxide') * 2000)
    .fluidOutputs(fluid('wastewater') * 4000)
    .duration(120)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

//PURIFIED GOLD (SPECIALIZED)
CSTR.recipeBuilder()
    .fluidInputs(fluid('hydrochloric_acid') * 150)
    .fluidInputs(fluid('nitric_acid') * 50)
    .fluidOutputs(fluid('aqua_regia') * 50)
    .duration(6)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .inputs(ore('dustGold') * 3)
    .fluidInputs(fluid('aqua_regia') * 4000)
    .fluidOutputs(fluid('chloroauric_acid_solution') * 1000)
    .chancedOutput(metaitem('dustSilverChloride'), 1000, 0)
    .duration(240)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .fluidInputs(fluid('chloroauric_acid_solution') * 1000)
    .outputs(metaitem('dustChloroauricAcid') * 5)
    .fluidOutputs(fluid('steam') * 6500)
    .fluidOutputs(fluid('nitrogen_dioxide') * 1000)
    .fluidOutputs(fluid('oxygen') * 500)
    .duration(240)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .inputs(ore('dustChloroauricAcid') * 5)
    .fluidInputs(fluid('distilled_water') * 1000)
    .fluidInputs(fluid('hydrochloric_acid') * 2000)
    .fluidOutputs(fluid('wohlwill_electrolyte') * 1000)
    .duration(240)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .inputs(ore('plateGold'))
    .fluidInputs(fluid('wohlwill_electrolyte') * 250)
    .notConsumable(metaitem('plateTitanium'))
    .notConsumable(fluid('wohlwill_electrolyte') * 1000)
    .outputs(metaitem('dustHighPurityGold'))
    .outputs(metaitem('gold_anode_slime'))
    .fluidOutputs(fluid('spent_wohlwill_electrolyte') * 250)
    .duration(480)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .inputs(ore('plateGold'))
    .fluidInputs(fluid('wohlwill_electrolyte') * 250)
    .notConsumable(metaitem('plateHighPurityGold'))
    .notConsumable(fluid('wohlwill_electrolyte') * 1000)
    .outputs(metaitem('dustHighPurityGold'))
    .outputs(metaitem('gold_anode_slime'))
    .fluidOutputs(fluid('spent_wohlwill_electrolyte') * 250)
    .duration(560)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .fluidInputs(fluid('spent_wohlwill_electrolyte') * 2000)
    .fluidInputs(fluid('sulfur_dioxide') * 3000)
    .outputs(metaitem('dustGold'))
    .fluidOutputs(fluid('SulfuricPGMSolution') * 1000)
    .duration(120)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

    //Au3+ + 3e- --> Au
    //SO2 + 2H2O --> SO4 2- + 4H+ + 2e-
    //2 Au3+ + 3SO2 + 6H2O --> 3SO4 2- + 12H+
    //in solution containing 2 H+, 8 Cl-, 4 HCl
    //added products: 3 SO4 2-, 12 H+
    //final solution: 12 HCl, 3 H2SO4, 8 H2O

BATCH_REACTOR.recipeBuilder()
    .inputs(ore('dustCalciumHydroxide') * 15)
    .fluidInputs(fluid('SulfuricPGMSolution') * 1000)
    .outputs(metaitem('dustCalciumSulfate') * 18)
    .fluidOutputs(fluid('PGMSolution') * 1000)
    .duration(120)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

//ANODE SLIME PROCESSING
BATCH_REACTOR.recipeBuilder()
    .inputs(metaitem('silver_anode_slime') * 27)
    .fluidInputs(fluid('aqua_regia') * 4000)
    .fluidOutputs(fluid('chloroauric_acid_solution') * 1000)
    .duration(240)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

BATCH_REACTOR.recipeBuilder()
    .inputs(metaitem('gold_anode_slime') * 18)
    .fluidInputs(fluid('nitric_acid') * 2000)
    .outputs(metaitem('PGMSolution') * 1000)
    .fluidOutputs(fluid('silver_nitrate_solution') * 1000)
    .fluidOutputs(fluid('nitrogen_dioxide') * 1000)
    .duration(240)
    .EUt(Globals.voltAmps[2])
    .buildAndRegister()

