EBF = recipemap('electric_blast_furnace')
FBR = recipemap('fluidized_bed_reactor')

EBF.recipeBuilder()
        .inputs(ore('dustCeriumIvOxide') * 12)
        .outputs(metaitem('dustCeriumIiiOxide') * 10)
        .fluidOutputs(fluid('oxygen') * 2000)
        .EUt(1920)
        .blastFurnaceTemp(2273)
        .duration(20)
        .buildAndRegister()

FBR.recipeBuilder()
        .inputs(ore('dustCeriumIiiOxide') * 10)
        .fluidInputs(fluid('water') * 2000)
        .outputs(metaitem('dustCeriumIvOxide') * 12)
        .fluidOutputs(fluid('hydrogen') * 4000)
        .EUt(1920)
        .duration(20)
        .buildAndRegister()