ROASTER = recipemap('roaster')
CENTRIFUGE = recipemap('centrifuge')
MIXER = recipemap('mixer')
DISTILLERY = recipemap('distillery')
CRYSTALLIZER = recipemap('crystallizer')

CENTRIFUGE.recipeBuilder()
        .inputs(metaitem('dustWoodAsh') * 10)
        .outputs(metaitem('dustDarkAsh') * 9)
        .fluidInputs(fluid('water') * 1000)
        .fluidOutputs(fluid('potash_solution') * 1000)
        .EUt(30)
        .duration(120)
        .buildAndRegister()

DISTILLERY.recipeBuilder()
        .fluidInputs(fluid('potash_solution') * 1000)
        .outputs(metaitem('dustPotassiumCarbonate') * 6)
        .fluidOutputs(fluid('water') * 1000)
        .EUt(30)
        .duration(120)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(metaitem('dustPotassiumCarbonate') * 6)
        .fluidInputs(fluid('hydrochloric_acid') * 2000)
        .fluidOutputs(fluid('potassium_chloride_solution') * 2000)
        .fluidOutputs(fluid('carbon_dioxide') * 1000)
        .EUt(30)
        .duration(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(metaitem('dustKainite') * 11)
        .fluidInputs(fluid('water') * 1000)
        .fluidOutputs(fluid('kainite_leach') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
        .fluidInputs(fluid('kainite_leach') * 1000)
        .outputs(metaitem('dustMagnesiumSulfate') * 6)
        .fluidOutputs(fluid('potassium_chloride_solution') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(metaitem('dustCarnallite') * 11)
        .fluidInputs(fluid('water') * 1000)
        .fluidOutputs(fluid('carnallite_leach') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
        .fluidInputs(fluid('carnallite_leach') * 1000)
        .outputs(metaitem('dustMagnesiumChloride') * 3)
        .fluidOutputs(fluid('potassium_chloride_solution') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(metaitem('dustPotassiumSulfate') * 7)
        .inputs(metaitem('dustCarbon') * 2)
        .fluidInputs(fluid('carbon_dioxide') * 2000)
        .outputs(metaitem('dustPotash') * 3)
        .EUt(30)
        .duration(160)
        .buildAndRegister()