ROASTER = recipemap('roaster')
CENTRIFUGE = recipemap('centrifuge')
MIXER = recipemap('mixer')
DISTILLERY = recipemap('distillery')
CRYSTALLIZER = recipemap('crystallizer')
BR = recipemap('batch_reactor')
DISTILLERY = recipemap('distillery')
REACTION_FURNACE = recipemap('reaction_furnace')
FLBR = recipemap('fluidized_bed_reactor')

CENTRIFUGE.recipeBuilder()
        .inputs(metaitem('dustWoodAsh') * 10)
        .outputs(metaitem('dustDarkAsh') * 9)
        .fluidInputs(fluid('water') * 1000)
        .fluidOutputs(fluid('potassium_carbonate_solution') * 1000)
        .EUt(30)
        .duration(120)
        .buildAndRegister()

DISTILLERY.recipeBuilder()
        .fluidInputs(fluid('potassium_carbonate_solution') * 1000)
        .outputs(metaitem('dustPotassiumCarbonate') * 6)
        .fluidOutputs(fluid('water') * 1000)
        .EUt(30)
        .duration(120)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(metaitem('dustPotassiumCarbonate') * 6)
        .fluidInputs(fluid('hydrochloric_acid') * 2000)
        .fluidOutputs(fluid('potassium_chloride_solution') * 2000)
        .fluidOutputs(fluid('carbon_dioxide') * 1000)
        .EUt(30)
        .duration(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(metaitem('dustKainite') * 11)
        .fluidInputs(fluid('water') * 1000)
        .fluidOutputs(fluid('kainite_leach') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
        .fluidInputs(fluid('kainite_leach') * 1000)
        .outputs(metaitem('dustMagnesiumSulfate') * 6)
        .fluidOutputs(fluid('potassium_chloride_solution') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(metaitem('dustCarnallite') * 11)
        .fluidInputs(fluid('water') * 1000)
        .fluidOutputs(fluid('carnallite_leach') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
        .fluidInputs(fluid('carnallite_leach') * 1000)
        .outputs(metaitem('dustMagnesiumChloride') * 3)
        .fluidOutputs(fluid('potassium_chloride_solution') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(metaitem('dustPotassiumSulfate') * 6)
        .outputs(metaitem('dustPotash') * 2)
        .fluidOutputs(fluid('sulfur_trioxide') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(metaitem('dustPotassiumSulfate') * 7)
        .inputs(metaitem('dustCarbon') * 4)
        .outputs(metaitem('dustPotassiumSulfide') * 3)
        .fluidOutputs(fluid('carbon_dioxide') * 4000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(metaitem('dustPotassiumSulfide') * 3)
        .fluidInputs(fluid('oxygen') * 3000)
        .outputs(metaitem('dustPotash') * 3)
        .fluidOutputs(fluid('sulfur_dioxide') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
        .inputs(metaitem('dustSodium'))
        .fluidInputs(fluid('rock_salt') * 288)
        .fluidOutputs(fluid('potassium_salt_mixture') * 1000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

DISTILLERY.recipeBuilder()
        .fluidInputs(fluid('potassium_salt_mixture') * 1000)
        .outputs(metaitem('dustSalt') * 2)
        .fluidOutputs(fluid('potassium') * 144)
        .EUt(30)
        .duration(160)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(metaitem('dustCalciumHydroxide') * 5)
        .fluidInputs(fluid('potassium_carbonate_solution') * 1000)
        .fluidInputs(fluid('water') * 1000)
        .outputs(metaitem('dustCalcite') * 5)
        .fluidOutputs(fluid('potassium_hydroxide_solution') * 2000)
        .EUt(30)
        .duration(160)
        .buildAndRegister()