ROASTER = recipemap('roaster')
ELECTROLYTIC_CELL = recipemap('electrolytic_cell')

ROASTER.recipeBuilder()
        .inputs(metaitem('dustTrona') * 28)
        .outputs(metaitem('dustSodaAsh') * 18)
        .fluidOutputs(fluid('steam') * 5000)
        .fluidOutputs(fluid('carbon_dioxide') * 1000)
        .EUt(30)
        .duration(120)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(metaitem('dustSodaAsh') * 6)
        .inputs(metaitem('dustCarbon') * 2)
        .outputs(metaitem('dustSodium') * 2)
        .fluidOutputs(fluid('carbon_monoxide') * 3000)
        .EUt(30)
        .duration(120)
        .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
        .fluidInputs(fluid('sodium_hydroxide') * 432)
        .notConsumable(metaitem('stickNickel'))
        .notConsumable(metaitem('stickIron'))
        .outputs(metaitem('dustSodium'))
        .fluidOutputs(fluid('oxygen') * 1000)
        .fluidOutputs(fluid('hydrogen') * 1000)
        .duration(200)
        .EUt(Globals.voltAmps[1] * 2)
        .buildAndRegister()