import gregtech.api.GregTechAPI;
import gregtech.api.unification.material.Material;

import static gregtech.api.unification.material.Materials.*;
import static globals.Globals.*

BR = recipemap('batch_reactor')
ROASTER = recipemap('roaster')
DISTILLERY = recipemap('distillery')
REACTION_FURNACE = recipemap('reaction_furnace')
CENTRIFUGE = recipemap('centrifuge')

REACTION_FURNACE.recipeBuilder()
        .inputs(metaitem('dustVanadinite') * 21)
        .inputs(metaitem('dustSalt') * 6)
        .outputs(metaitem('dustSaltRoastedVanadinite') * 27)
        .duration(200)
        .EUt(120)
        .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
        .inputs(metaitem('dustVanadinite') * 42)
        .inputs(metaitem('dustSodaAsh') * 18)
        .outputs(metaitem('dustSodaAshRoastedVanadinite') * 51)
        .fluidOutputs(fluid('carbon_dioxide') * 3000)
        .duration(300)
        .EUt(120)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .inputs(metaitem('dustSodaAshRoastedVanadinite') * 51)
        .fluidInputs(fluid('water') * 6000)
        .fluidOutputs(fluid('sodium_vanadate_solution') * 6000)
        .outputs(metaitem('dustLeachedSaltRoastedVanadinite') * 21)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .inputs(metaitem('dustLeachedSaltRoastedVanadinite') * 21)
        .fluidInputs(fluid('gtfo_heated_water') * 1000)
        .fluidOutputs(fluid('lead_chloride_solution') * 1000)
        .outputs(metaitem('dustLeadOxide') * 18)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .inputs(metaitem('dustSaltRoastedVanadinite') * 27)
        .fluidInputs(fluid('water') * 3000)
        .fluidOutputs(fluid('sodium_vanadate_solution') * 3000)
        .outputs(metaitem('dustLeachedSaltRoastedVanadinite') * 12)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .inputs(metaitem('dustLeachedSaltRoastedVanadinite') * 12)
        .fluidInputs(fluid('gtfo_heated_water') * 3000)
        .fluidOutputs(fluid('lead_chloride_solution') * 3000)
        .outputs(metaitem('dustLeadOxide') * 6)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

DISTILLERY.recipeBuilder()
        .fluidInputs(fluid('lead_chloride_solution') * 1000)
        .fluidOutputs(fluid('water') * 1000)
        .outputs(metaitem('dustLeadChloride') * 3)
        .duration(100)
        .EUt(30)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(metaitem('dustAmmoniumChloride') * 6)
        .fluidInputs(fluid('sodium_vanadate_solution') * 1000)
        .outputs(metaitem('dustAmmoniumMetavanadate') * 9)
        .fluidOutputs(fluid('salt_water') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(metaitem('dustAmmoniumMetavanadate') * 18)
        .outputs(metaitem('dustVanadiumPentoxide') * 7)
        .fluidOutputs(fluid('steam') * 1000)
        .fluidOutputs(fluid('ammonia') * 2000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()