import static globals.Globals.*

ASSEMBLER = recipemap('assembler')
BR = recipemap('batch_reactor')
REACTION_FURNACE = recipemap('reaction_furnace')

// TMPTA

BR.recipeBuilder()
    .fluidInputs(fluid('butyraldehyde') * 1000)
    .fluidInputs(fluid('formaldehyde') * 3000)
    .fluidInputs(fluid('sodium_hydroxide_solution') * 1000)
    .outputs(metaitem('dustTrimethylolpropane'))
    .fluidOutputs(fluid('wastewater') * 1000)
    .duration(200)
    .EUt(120)
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustCopper'))
    .inputs(ore('dustNickel'))
    .fluidInputs(fluid('bromine') * 4000)
    .outputs(metaitem('dustAcrylicCatalyst'))
    .duration(200)
    .EUt(120)
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .notConsumable(ore('dustAcrylicCatalyst'))
    .fluidInputs(fluid('acetylene') * 1000)
    .fluidInputs(fluid('carbon_monoxide') * 1000)
    .fluidInputs(fluid('water') * 1000)
    .fluidOutputs(fluid('acrylic_acid') * 1000)
    .duration(200)
    .EUt(120)
    .buildAndRegister()

BR.recipeBuilder()
    .notConsumable(ore('springCupronickel'))
    .notConsumable(fluid('sulfuric_acid') * 1000)
    .inputs(ore('dustTrimethylolpropane'))
    .fluidInputs(fluid('acrylic_acid') * 3000)
    .fluidOutputs(fluid('trimethylolpropane_triacrylate') * 1000)
    .fluidOutputs(fluid('steam') * 3000)
    .duration(200)
    .EUt(120)
    .buildAndRegister()

// UV initiator, Benzenediazonium tetrafluoroborate

BR.recipeBuilder()
    .inputs(ore('dustSodiumNitrite') * 4)
    .fluidInputs(fluid('hydrogen_chloride') * 2000)
    .fluidInputs(fluid('gtfo_aniline') * 1000)
    .outputs(metaitem('dustBenzenediazoniumChloride'))
    .fluidOutputs(fluid('diluted_saltwater') * 2000)
    .duration(200)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustBenzenediazoniumChloride'))
    .fluidInputs(fluid('trimethylolpropane_triacrylate') * 8000)
    .fluidOutputs(fluid('photoemulsion') * 8000)
    .duration(200)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('foilPlastic'))
    .fluidInputs(fluid('dye_red') * 100)
    .fluidInputs(fluid('photoemulsion') * 500)
    .outputs(metaitem('rubylith_film'))
    .duration(200)
    .EUt(120)
    .buildAndRegister()

ASSEMBLER.recipeBuilder()
    .inputs(ore('foilMylar'))
    .inputs(metaitem('rubylith_film'))
    .fluidInputs(fluid('glue') * 100)
    .outputs(metaitem('rubylith'))
    .duration(200)
    .EUt(120)
    .buildAndRegister()