import static prePostInit.Recipemaps.*
import globals.Carbons
import static gregtech.api.GTValues.*

ELECTROSTATIC_SEPARATOR.recipeBuilder()
    .notConsumable(metaitem('item_filter'))
    .fluidInputs(fluid('molybdenite_flue_gas') * 2000)
    .chancedOutput(metaitem('dustRheniumRichFlue'), 5000, 0)
    .fluidOutputs(fluid('sulfur_dioxide') * 2000)
    .duration(20)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustRheniumRichFlue'))
    .fluidInputs(fluid('distilled_water') * 50)
    .outputs(metaitem('dustAsh'))
    .fluidOutputs(fluid('scrubbed_perrhenate_solution') * 50)
    .duration(20)
    .EUt(VA[LV])
    .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
    .inputs(metaitem('beads.weak_basic_anion_exchange'))
    .fluidInputs(fluid('scrubbed_perrhenate_solution') * 1000)
    .outputs(metaitem('beads.loaded_rhenium_anion_exchange'))
    .fluidOutputs(fluid('wastewater') * 1000)
    .duration(200)
    .EUt(VA[EV])
    .buildAndRegister()
    
BR.recipeBuilder()
    .inputs(metaitem('beads.loaded_rhenium_anion_exchange'))
    .fluidInputs(fluid('ammonia_solution') * 1000)
    .outputs(metaitem('beads.weak_basic_anion_exchange'))
    .fluidOutputs(fluid('ammonium_perrhenate_solution') * 1000)
    .duration(200)
    .EUt(VA[HV])
    .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
    .fluidInputs(fluid('ammonium_perrhenate_solution') * 1000)
    .outputs(metaitem('dustAmmoniumPerrhenate') * 10)
    .fluidOutputs(fluid('wastewater') * 1000)
    .duration(200)
    .EUt(VA[HV])
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .inputs(ore('dustAmmoniumPerrhenate') * 10)
    .fluidInputs(fluid('hydrogen') * 7000)
    .outputs(metaitem('dustRhenium'))
    .fluidOutputs(fluid('dense_steam') * 4000)
    .fluidOutputs(fluid('ammonia') * 1000)
    .duration(200)
    .EUt(VA[EV])
    .buildAndRegister()

