import globals.Globals

BR = recipemap('batch_reactor')
ROASTER = recipemap('roaster')
DISTILLERY = recipemap('distillery')
EBF = recipemap('electric_blast_furnace')
MIXER_SETTLER = recipemap('mixer_settler')

BR.recipeBuilder()
    .inputs(ore('dustThoriumConcentrate'))
    .fluidInputs(fluid('sodium_hydroxide_solution') * 470)
    .outputs(metaitem('dustDigestedThoriumConcentrate'))
    .fluidOutputs(fluid('wastewater') * 470)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustDigestedThoriumConcentrate'))
    .fluidInputs(fluid('nitric_acid') * 470)
    .fluidOutputs(fluid('dissolved_thorium_concentrate') * 705)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

MIXER_SETTLER.recipeBuilder()
    .inputs(ore('dustSmallSodiumHydroxide'))
    .fluidInputs(fluid('dissolved_thorium_concentrate') * 705)
    .fluidInputs(fluid('tributyl_phosphate_extraction_mixture') * 1600)
    .chancedOutput(metaitem('dustMonaReHydroxides'), 500, 0)
    .fluidOutputs(fluid('thorium_extract') * 1600)
    .duration(120)
    .EUt(120)
    .requiredCells(6)
    .buildAndRegister()

MIXER_SETTLER.recipeBuilder()
    .fluidInputs(fluid('thorium_extract') * 1600)
    .fluidInputs(fluid('distilled_water') * 80)
    .fluidOutputs(fluid('tributyl_phosphate_extraction_mixture') * 1600)
    .fluidOutputs(fluid('thorium_nitrate_solution') * 80)
    .duration(120)
    .EUt(120)
    .requiredCells(2)
    .buildAndRegister()

ROASTER.recipeBuilder()
    .fluidInputs(fluid('thorium_nitrate_solution') * 1000)
    .outputs(metaitem('dustThoriumDioxide') * 3)
    .fluidOutputs(fluid('nitrogen_dioxide') * 4000)
    .fluidOutputs(fluid('oxygen') * 2000)
    .fluidOutputs(fluid('dense_steam') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister() 

BR.recipeBuilder()
    .inputs(ore('dustThoriumDioxide') * 3)
    .fluidInputs(fluid('hydrochloric_acid') * 4000)
    .fluidOutputs(fluid('thorium_chloride_solution') * 6000)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('thorium_chloride_solution') * 6000)
    .outputs(metaitem('dustThoriumChloride') * 5)
    .fluidOutputs(fluid('water') * 6000)
    .duration(20)
    .EUt(30)
    .buildAndRegister()

EBF.recipeBuilder()
    .notConsumable(fluid('argon') * 1000)
    .inputs(ore('dustThoriumChloride') * 5)
    .inputs(ore('dustMagnesium') * 2)
    .outputs(metaitem('dustThorium'))
    .fluidOutputs(fluid('magnesium_chloride') * 864)
    .blastFurnaceTemp(1200)
    .duration(100)
    .EUt(Globals.voltAmps[3] * 2)
    .buildAndRegister()