import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// PTFE
BR.recipeBuilder()
    .inputs(metaitem('dustChromiumTrioxide') * 8)
    .fluidInputs(fluid('n_octanol') * 1500)
    .fluidInputs(fluid('sulfuric_acid') * 3000)
    .fluidInputs(fluid('acetone') * 500)
    .fluidOutputs(fluid('caprylic_acid') * 1500)
    .fluidOutputs(fluid('chromium_sulfate_solution') * 500)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(metaitem('dustSodiumHydroxide') * 18)
    .fluidInputs(fluid('chromium_sulfate_solution') * 500)
    .outputs(metaitem('dustChromiumIiiHydroxide') * 14)
    .fluidOutputs(fluid('sodium_sulfate_acetone_solution') * 500)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('sodium_sulfate_acetone_solution') * 1000)
    .outputs(metaitem('dustSodiumSulfate') * 42)
    .fluidOutputs(fluid('water') * 9000)
    .fluidOutputs(fluid('acetone') * 1000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('caprylic_acid') * 1000)
    .fluidInputs(fluid('thionyl_chloride') * 1000)
    .fluidOutputs(fluid('octanoyl_chloride') * 1000)
    .fluidOutputs(fluid('hydrogen_chloride') * 1000)
    .fluidOutputs(fluid('sulfur_dioxide') * 1000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .notConsumable(metaitem('plateNickel'))
    .notConsumable(metaitem('plateCobalt'))
    .fluidInputs(fluid('octanoyl_chloride') * 1000)
    .fluidInputs(fluid('hydrogen_fluoride') * 15000)
    .fluidOutputs(fluid('fluorinated_octanoyl_chloride_mixture') * 1000)
    .fluidOutputs(fluid('hydrogen') * 15000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('fluorinated_octanoyl_chloride_mixture') * 1000)
    .fluidOutputs(fluid('perfluorooctanoyl_fluoride') * 150)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('perfluorooctanoyl_fluoride') * 500)
    .fluidInputs(fluid('water') * 1000)
    .fluidOutputs(fluid('perfluorooctanoic_acid_mixture') * 1500)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('perfluorooctanoic_acid_mixture') * 1500)
    .outputs(metaitem('dustPerfluorooctanoicAcid') * 13)
    .fluidOutputs(fluid('hydrofluoric_acid') * 500)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('ammonia_solution') * 500)
    .inputs(metaitem('dustPerfluorooctanoicAcid') * 13)
    .fluidOutputs(fluid('fluorinated_surfactant_mixture') * 500)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('tetrafluoroethylene') * 1000)
    .fluidInputs(fluid('fluorinated_surfactant_mixture') * 500)
    .fluidOutputs(fluid('tetrafluoroethylene_emulsion') * 1500)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

POLYMERIZATION_TANK.recipeBuilder()
    .fluidInputs(fluid('tetrafluoroethylene_emulsion') * 1500)
    .inputs(ore('dustTinyPotassiumPersulfate'))
    .fluidOutputs(fluid('polytetrafluoroethylene_solution') * 500)
    .duration(200)
    .EUt(240)
    .buildAndRegister()

DRYER.recipeBuilder()
    .fluidInputs(fluid('polytetrafluoroethylene_solution') * 500)
    .outputs(metaitem('dustPolytetrafluoroethylene'))
    .fluidOutputs(fluid('fluorinated_surfactant_mixture') * 500)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

//Source (expanded PTFE): https://www.sciencedirect.com/science/chapter/monograph/abs/pii/B9781437778557000055?via%3Dihub
//Free version: https://sci-hub.st/10.1016/B978-1-4377-7855-7.00005-5
MIXER.recipeBuilder()
    .fluidInputs(fluid('light_naphtha') * 90)//ptfe density is 2200 kg/m^3; 1 dust = 2200/9 = 244 kg; source says 17-22% naphtha by weight (i went with 20) -> 61 kg of naphtha; naphtha density is 0.7 -> 87 l of naphtha; round to 90.
    .inputs(metaitem('dustPolytetrafluoroethylene'))
    .outputs(metaitem('paste.lubricated_ptfe'))
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

FORMING_PRESS.recipeBuilder()
    .inputs(metaitem('paste.lubricated_ptfe'))
    .notConsumable(metaitem('shape.mold.cylinder'))
    .outputs(metaitem('preform.lubricated_ptfe'))
    .duration(50)
    .EUt(VA[LV])
    .buildAndRegister()

EXTRUDER.recipeBuilder()
    .inputs(metaitem('preform.lubricated_ptfe'))
    .notConsumable(metaitem('shape.extruder.foil'))//source says 75 um thick after extrusion
    .outputs(metaitem('foil.extruded_ptfe') * 4)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

ASSEMBLER.recipeBuilder()
    .notConsumable(metaitem('springNichrome') * 2)
    .inputs(metaitem('foil.extruded_ptfe'))
    .outputs(metaitem('foil.stretched_ptfe'))
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

DRYER.recipeBuilder()
    .inputs(metaitem('foil.stretched_ptfe'))
    .outputs(metaitem('foilExpandedPolytetrafluoroethylene'))
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()