import static globals.Globals.*

import gregtech.api.recipes.ModHandler;
import gregtech.api.unification.material.Materials;
import gregtech.api.unification.ore.OrePrefix;
import gregtech.api.unification.stack.UnificationEntry;

MIXER = recipemap('mixer')
FLUID_HEATER = recipemap('fluid_heater')
CENTRIFUGE = recipemap('centrifuge')
GREENHOUSE = recipemap('greenhouse')
COMPRESSOR = recipemap('compressor')
CHEMICAL_BATH = recipemap('chemical_bath')
PYROLYSE_OVEN = recipemap('pyrolyse_oven');

//REMOVALS

// Fertilizer * 4
mods.gregtech.mixer.removeByInput(30, [item('minecraft:dirt'), metaitem('dustWood') * 2, item('minecraft:sand') * 4], [fluid('water') * 1000])
// Fertilizer Solution * 5000
mods.gregtech.mixer.removeByInput(16, [item('minecraft:dye', 15)], [fluid('water') * 5000])
// Greenhouse Glass * 1
mods.gregtech.assembler.removeByInput(24, [metaitem('cupric_hydrogen_arsenite_dust'), item('gregtech:transparent_casing')], null)

//GREENHOUSE

CHEMICAL_BATH.recipeBuilder()
        .inputs(item('gregtech:transparent_casing'))
        .fluidInputs(fluid('dye_green') * 144)
        .outputs(item('gregtechfoodoption:gtfo_glass_casing'))
        .EUt(7)
        .duration(40)
        .buildAndRegister()

//FERTILIZER CHAIN

def nitrogenNutrients = [
        metaitem('dustAmmoniumChloride'),
        metaitem('dustAmmoniumNitrate'),
        metaitem('dustAmmoniumSulfate'),
        metaitem('dustUrea')
];

def potassiumNutrients = [
        metaitem('dustAsh'),
        metaitem('dustCharcoal'),
        metaitem('dustRockSalt'),
        metaitem('dustPotassiumCarbonate'),
        metaitem('dustPotash')
];

def phosphorusNutrients = [
        metaitem('dustCalcite'),
        metaitem('dustChlorapatite'),
        metaitem('dustHydroxyapatite'),
        metaitem('dustFluorapatite'),
        metaitem('dustTricalciumPhosphate'),
        metaitem('dustPhosphorus'),
        item('minecraft:dye', 15)
];

for (p in phosphorusNutrients) {
    for (n in nitrogenNutrients) {
        for (k in potassiumNutrients) {
            MIXER.recipeBuilder()
                    .inputs(p)
                    .inputs(n)
                    .inputs(k)
                    .outputs(metaitem('fertilizer') * 5)
                    .EUt(30)
                    .duration(100)
                    .buildAndRegister()
        }
    }
    MIXER.recipeBuilder()
            .inputs(metaitem('dustSaltpeter') * 2)
            .inputs(p)
            .outputs(metaitem('fertilizer') * 5)
            .EUt(30)
            .duration(100)
            .buildAndRegister()

    MIXER.recipeBuilder()
            .inputs(metaitem('bio_chaff') * 2)
            .inputs(p)
            .outputs(metaitem('fertilizer') * 5)
            .EUt(30)
            .duration(100)
            .buildAndRegister()

    MIXER.recipeBuilder()
            .fluidInputs(fluid('fermented_biomass') * 1000)
            .inputs(p)
            .outputs(metaitem('fertilizer') * 5)
            .EUt(30)
            .duration(100)
            .buildAndRegister()
}

MIXER.recipeBuilder()
        .inputs(metaitem('fertilizer') * 2)
        .fluidInputs(fluid('water') * 1000)
        .fluidOutputs(fluid('gtfo_fertilizer_solution') * 1000)
        .EUt(30)
        .duration(60)
        .buildAndRegister()

COMPRESSOR.recipeBuilder()
        .inputs(ore('treeLeaves') * 16)
        .outputs(metaitem('plant_ball'))
        .EUt(2)
        .duration(300)
        .buildAndRegister()

PYROLYSE_OVEN.recipeBuilder()
        .inputs(item('minecraft:sugar') * 24)
        .outputs(metaitem('dustCharcoal') * 6)
        .fluidOutputs(fluid('steam') * 6000)
        .duration(320)
        .EUt(64)
        .buildAndRegister()

// WEED KILLERS & PESTICIDES

MIXER.recipeBuilder()
        .inputs(metaitem('dustSalt') * 2)
        .fluidInputs(fluid('acetic_acid') * 100)
        .fluidInputs(fluid('gtfo_sodium_stearate') * 100)
        .fluidInputs(fluid('water') * 1000)
        .fluidOutputs(fluid('weed_killer') * 1000)
        .EUt(30)
        .duration(60)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('seed_oil') * 100)
        .fluidInputs(fluid('gtfo_sodium_stearate') * 100)
        .fluidInputs(fluid('water') * 1000)
        .fluidOutputs(fluid('pesticide') * 1000)
        .EUt(30)
        .duration(60)
        .buildAndRegister()

// GREENHOUSE GASES

MIXER.recipeBuilder()
        .fluidInputs(fluid('air') * 1000)
        .fluidInputs(fluid('carbon_dioxide') * 100)
        .fluidOutputs(fluid('greenhouse_gases') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

FLUID_HEATER.recipeBuilder()
        .fluidInputs(fluid('greenhouse_gases') * 1000)
        .fluidOutputs(fluid('warm_greenhouse_gases') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('water') * 40)
        .fluidInputs(fluid('greenhouse_gases') * 1000)
        .fluidOutputs(fluid('cool_greenhouse_gases') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('greenhouse_gases') * 1000)
        .fluidInputs(fluid('water') * 100)
        .fluidOutputs(fluid('humid_greenhouse_gases') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('greenhouse_gases') * 1000)
        .fluidInputs(fluid('sulfuric_acid') * 20)
        .fluidOutputs(fluid('dry_greenhouse_gases') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('warm_greenhouse_gases') * 1000)
        .fluidInputs(fluid('water') * 100)
        .fluidOutputs(fluid('warm_humid_greenhouse_gases') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('warm_greenhouse_gases') * 1000)
        .fluidInputs(fluid('sulfuric_acid') * 20)
        .fluidOutputs(fluid('warm_dry_greenhouse_gases') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('cool_greenhouse_gases') * 1000)
        .fluidInputs(fluid('water') * 100)
        .fluidOutputs(fluid('cool_humid_greenhouse_gases') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('cool_greenhouse_gases') * 1000)
        .fluidInputs(fluid('sulfuric_acid') * 20)
        .fluidOutputs(fluid('cool_dry_greenhouse_gases') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

//THIS IS FOR GREENHOUSES IN OUTER SPACE

MIXER.recipeBuilder()
        .fluidInputs(fluid('nitrogen') * 780)
        .fluidInputs(fluid('oxygen') * 220)
        .fluidOutputs(fluid('earth_like_air') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('earth_like_air') * 1000)
        .fluidInputs(fluid('carbon_dioxide') * 100)
        .fluidOutputs(fluid('greenhouse_gases') * 1000)
        .EUt(30)
        .duration(20)
        .buildAndRegister()

//TREES
GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:sapling'))
        .notConsumable(item('minecraft:dirt'))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('minecraft:log') * 6)
        .outputs(item('minecraft:leaves') * 12)
        .outputs(item('minecraft:sapling') * 2)
        .outputs(item('minecraft:apple') * 1)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:sapling', 1))
        .notConsumable(item('minecraft:dirt'))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('minecraft:log', 1) * 8)
        .outputs(item('minecraft:leaves', 1) * 14)
        .outputs(item('minecraft:sapling', 1) * 2)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:sapling', 2))
        .notConsumable(item('minecraft:dirt'))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('minecraft:log', 2) * 6)
        .outputs(item('minecraft:leaves', 2) * 12)
        .outputs(item('minecraft:sapling', 2) * 2)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:sapling', 3))
        .notConsumable(item('minecraft:dirt'))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 8)
        .outputs(item('minecraft:log', 3) * 24)
        .outputs(item('minecraft:leaves', 3) * 40)
        .outputs(item('minecraft:sapling', 3) * 5)
        .EUt(30)
        .duration(7200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:sapling', 4))
        .notConsumable(item('minecraft:dirt'))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('minecraft:log2') * 6)
        .outputs(item('minecraft:leaves2') * 12)
        .outputs(item('minecraft:sapling', 4) * 2)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:sapling', 5))
        .notConsumable(item('minecraft:dirt'))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 8)
        .outputs(item('minecraft:log2', 1) * 24)
        .outputs(item('minecraft:leaves2', 1) * 40)
        .outputs(item('minecraft:sapling', 5) * 5)
        .outputs(item('minecraft:apple') * 2)
        .EUt(30)
        .duration(7200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtech:rubber_sapling'))
        .notConsumable(item('minecraft:dirt'))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtech:rubber_log') * 6)
        .outputs(item('gregtech:rubber_leaves') * 12)
        .outputs(metaitem('rubber_drop') * 4)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

//FRUIT TREES

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_0') * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_0') * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0') * 2)
        .outputs(metaitem('food.banana') * 4)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_0') * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_0') * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0') * 2)
        .outputs(metaitem('food.banana') * 8)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 2))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_0', 4) * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_0', 4) * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 2) * 2)
        .outputs(metaitem('food.orange') * 4)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 2))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_0', 4) * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_0', 4) * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 2) * 2)
        .outputs(metaitem('food.orange') * 8)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 4))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_0', 8) * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_0', 8) * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 4) * 2)
        .outputs(metaitem('food.mango') * 4)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 4))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_0', 8) * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_0', 8) * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 4) * 2)
        .outputs(metaitem('food.mango') * 8)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 6))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_0', 12) * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_0', 12) * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 6) * 2)
        .outputs(metaitem('food.apricot') * 4)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 6))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_0', 12) * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_0', 12) * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 6) * 2)
        .outputs(metaitem('food.apricot') * 8)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 8))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_1') * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_1') * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 8) * 2)
        .outputs(metaitem('food.lemon') * 5)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 8))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_1') * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_1') * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 8) * 2)
        .outputs(metaitem('food.lemon') * 10)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 10))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_1', 4) * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_1', 4) * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 10) * 2)
        .outputs(metaitem('food.lime') * 6)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 10))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_1', 4) * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_1', 4) * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 10) * 2)
        .outputs(metaitem('food.lime') * 12)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 12))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_1', 8) * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_1', 8) * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 12) * 2)
        .outputs(metaitem('crop.olive') * 20)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_0', 12))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_1', 8) * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_1', 8) * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_0', 12) * 2)
        .outputs(metaitem('crop.olive') * 40)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_1'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_2') * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_2') * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_1') * 2)
        .outputs(metaitem('component.nutmeg') * 10)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('gregtechfoodoption:gtfo_sapling_1'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 4)
        .outputs(item('gregtechfoodoption:gtfo_log_2') * 6)
        .outputs(item('gregtechfoodoption:gtfo_leaves_2') * 12)
        .outputs(item('gregtechfoodoption:gtfo_sapling_1') * 2)
        .outputs(metaitem('component.nutmeg') * 20)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

//VANILLA CROPS

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:cactus'))
        .notConsumable(item('minecraft:sand'))
        .fluidInputs(fluid('warm_dry_greenhouse_gases') * 10000)
        .outputs(item('minecraft:cactus') * 12)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:dye', 3))
        .notConsumable(item('minecraft:log', 3))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:dye', 3) * 15)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:dye', 3))
        .notConsumable(item('minecraft:log', 3))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:dye', 3) * 30)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:reeds'))
        .notConsumable(item('minecraft:sand'))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:reeds') * 40)
        .EUt(30)
        .duration(2400)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:wheat_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:wheat_seeds') * 25)
        .outputs(item('minecraft:wheat') * 30)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:wheat_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:wheat_seeds') * 50)
        .outputs(item('minecraft:wheat') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:wheat_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:wheat_seeds') * 50)
        .outputs(item('minecraft:wheat') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:wheat_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:wheat_seeds') * 75)
        .outputs(item('minecraft:wheat') * 90)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:potato'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:potato') * 30)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:potato'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:potato') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:potato'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:potato') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:potato'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:potato') * 90)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:carrot'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:carrot') * 30)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:carrot'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:carrot') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:carrot'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:carrot') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:carrot'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:carrot') * 90)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:beetroot_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:beetroot') * 30)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:beetroot_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:beetroot') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:beetroot_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:beetroot') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:beetroot_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:beetroot') * 90)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:melon_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:melon_block') * 10)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:melon_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:melon_block') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:melon_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:melon_block') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:melon_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:melon_block') * 30)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:pumpkin_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:pumpkin') * 10)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:pumpkin_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:pumpkin') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:pumpkin_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:pumpkin') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:pumpkin_seeds'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:pumpkin') * 30)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

//GTFO CROPS

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.soy'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.soybean') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.soy'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.soybean') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.soy'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.soybean') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.soy'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.soybean') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.tomato'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.tomato') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.tomato'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.tomato') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.tomato'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.tomato') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.tomato'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.tomato') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.cucumber'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.cucumber') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.cucumber'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.cucumber') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.cucumber'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.cucumber') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.cucumber'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.cucumber') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.onion'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.onion') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.onion'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.onion') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.onion'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.onion') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.onion'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.onion') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.grape'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('food.grapes') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.grape'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('food.grapes') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.grape'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('food.grapes') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.grape'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('food.grapes') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.coffee'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.coffee') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.coffee'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.coffee') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.coffee'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.coffee') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.coffee'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.coffee') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.pea'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.pea') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.pea'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.pea') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.pea'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.pea') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.pea'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.pea') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.bean'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.bean') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.bean'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.bean') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.bean'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.bean') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.bean'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.bean') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.horseradish'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('cool_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.horseradish') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.horseradish'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('cool_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.horseradish') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.horseradish'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('cool_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.horseradish') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.horseradish'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('cool_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.horseradish') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.oregano'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_dry_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.oregano') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.oregano'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_dry_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.oregano') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.oregano'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_dry_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.oregano') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.oregano'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_dry_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.oregano') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.garlic'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.garlic') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.garlic'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.garlic') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.garlic'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.garlic') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.garlic'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('seed.garlic') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.basil'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.basil') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.basil'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.basil') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.basil'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.basil') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.basil'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.basil') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.aubergine'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.aubergine') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.aubergine'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.aubergine') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.aubergine'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.aubergine') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.aubergine'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('crop.aubergine') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.corn.ear'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.corn.ear') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.corn.ear'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.corn.ear') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.corn.ear'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.corn.ear') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.corn.ear'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.corn.ear') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.artichoke'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.artichoke') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.artichoke'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.artichoke') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.artichoke'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.artichoke') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('seed.artichoke'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.artichoke') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.black_pepper'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.black_pepper') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.black_pepper'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.black_pepper') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.black_pepper'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.black_pepper') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.black_pepper'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.black_pepper') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.rice'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.rice') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.rice'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.rice') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.rice'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(3))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.rice') * 40)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(metaitem('component.rice'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(4))
        .fluidInputs(fluid('warm_humid_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('pesticide') * 500)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(metaitem('component.rice') * 60)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:brown_mushroom'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:brown_mushroom') * 10)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:brown_mushroom'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:brown_mushroom') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:red_mushroom'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(1))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:red_mushroom') * 10)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()

GREENHOUSE.recipeBuilder()
        .notConsumable(item('minecraft:red_mushroom'))
        .notConsumable(item('minecraft:dirt'))
        .notConsumable(Globals.circuit(2))
        .fluidInputs(fluid('cool_greenhouse_gases') * 10000)
        .fluidInputs(fluid('water') * 5000)
        .fluidInputs(fluid('weed_killer') * 500)
        .inputs(metaitem('fertilizer') * 2)
        .outputs(item('minecraft:red_mushroom') * 20)
        .EUt(30)
        .duration(1200)
        .buildAndRegister()