import globals.Globals

BR = recipemap('batch_reactor')
REACTION_FURNACE = recipemap('reaction_furnace')
DISTILLERY = recipemap('distillery')

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('dysprosium_chloride_solution') * 6000)
    .outputs(metaitem('dustDysprosiumChloride') * 4)
    .fluidOutputs(fluid('water') * 6000)
    .duration(20)
    .EUt(30)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustDysprosiumChloride') * 4)
    .fluidInputs(fluid('hydrofluoric_acid') * 3000)
    .outputs(metaitem('dustDysprosiumFluoride') * 4)
    .fluidOutputs(fluid('acidic_wastewater') * 9000)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .notConsumable(metaitem('crucible.tantalum'))
    .inputs(ore('dustDysprosiumFluoride') * 8)
    .inputs(ore('dustHighPurityCalcium') * 3)
    .fluidInputs(fluid('helium') * 50)
    .outputs(metaitem('dustFluorite') * 9)
    .outputs(metaitem('dustDysprosium') * 2)
    .duration(200)
    .EUt(Globals.voltAmps[3] * 2)
    .buildAndRegister()