import globals.Globals

BR = recipemap('batch_reactor')
REACTION_FURNACE = recipemap('reaction_furnace')
DISTILLERY = recipemap('distillery')
MIXER_SETTLER = recipemap('mixer_settler')

// Tier 1
BR.recipeBuilder()
    .inputs(ore('dustLanthanumCarbonate') * 14)
    .fluidInputs(fluid('hydrofluoric_acid') * 6000)
    .fluidInputs(fluid('distilled_water') * 3000)
    .outputs(metaitem('dustLanthanumFluoride') * 8)
    .fluidOutputs(fluid('diluted_hydrochloric_acid') * 12000)
    .fluidOutputs(fluid('carbon_dioxide') * 3000)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .notConsumable(metaitem('crucible.tantalum'))
    .inputs(ore('dustLanthanumFluoride') * 8)
    .inputs(ore('dustHighPurityCalcium') * 3)
    .fluidInputs(fluid('argon') * 50)
    .outputs(metaitem('dustLanthanum') * 2)
    .outputs(metaitem('dustFluorite') * 9)
    .duration(200)
    .EUt(960)
    .buildAndRegister()

// Tier 2
MIXER_SETTLER.recipeBuilder()
    .fluidInputs(fluid('distilled_water') * 1000)
    .fluidInputs(fluid('lanthanum_extract') * 10000)
    .fluidOutputs(fluid('lanthanum_nitrate_solution') * 1000)
    .fluidOutputs(fluid('aliquat_336_extraction_mixture') * 10000)
    .duration(80)
    .EUt(120)
    .requiredCells(2)
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('lanthanum_nitrate_solution') * 1000)
    .outputs(metaitem('dustLanthanumNitrate') * 13)
    .fluidOutputs(fluid('water') * 1000)
    .duration(20)
    .EUt(30)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustLanthanumNitrate') * 13)
    .fluidInputs(fluid('hydrofluoric_acid') * 3000)
    .outputs(metaitem('dustLanthanumFluoride') * 4)
    .fluidOutputs(fluid('diluted_nitric_acid') * 6000)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

// Lanthanothermy Recycing
BR.recipeBuilder()
    .inputs(ore('dustLanthanumOxide') * 5)
    .fluidInputs(fluid('hydrofluoric_acid') * 6000)
    .outputs(metaitem('dustLanthanumFluoride') * 8)
    .fluidOutputs(fluid('water') * 9000)
    .duration(80)
    .EUt(60)
    .buildAndRegister()