import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

BR.recipeBuilder()
    .fluidInputs(fluid('ytterbium_amalgam') * 1000)
    .fluidInputs(fluid('hydrochloric_acid') * 5000)
    .outputs(metaitem('dustMercuryIiChloride') * 3)
    .fluidOutputs(fluid('hydrogen') * 5000)
    .fluidOutputs(fluid('ytterbium_chloride_solution') * 5000)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumHydroxide') * 9)
    .fluidInputs(fluid('distilled_water') * 1000)
    .fluidInputs(fluid('ytterbium_chloride_solution') * 5000)
    .outputs(metaitem('dustYtterbiumHydroxide') * 7)
    .fluidOutputs(fluid('diluted_salt_water') * 6000)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustYtterbiumHydroxide') * 14)
    .outputs(metaitem('dustYtterbiumOxide') * 5)
    .fluidOutputs(fluid('dense_steam') * 3000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .notConsumable(metaitem('crucible.tantalum'))
    .inputs(ore('dustYtterbiumOxide') * 5)
    .inputs(ore('dustLanthanum') * 2)
    .outputs(metaitem('dustYtterbium') * 2)
    .outputs(metaitem('dustLanthanumOxide') * 5)
    .duration(200)
    .EUt(VA[HV])
    .buildAndRegister()
