import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

//PRIMITIVE (LV)
AUTOCLAVE.recipeBuilder()
    .inputs(ore('dustBone'))
    .fluidInputs(fluid('water') * 250)
    .outputs(metaitem('dustTricalciumPhosphate') * 13)
    .outputs(metaitem('gregtechfoodoption:fat_ingot'))
    .duration(120)
    .EUt(VA[LV])
    .buildAndRegister()

// Ca3(PO4)2 + 2 H2SO4 → Ca(H2PO4)2 + 2 CaSO4
BR.recipeBuilder()
    .inputs(ore('dustTricalciumPhosphate') * 13)
    .fluidInputs(fluid('sulfuric_acid') * 2000)
    .outputs(metaitem('dustMonocalciumPhosphate') * 15)
    .outputs(metaitem('dustCalciumSulfate') * 12)
    .duration(120)
    .EUt(VA[LV])
    .buildAndRegister()

// Ca(H2PO4)2 → Ca(PO3)2 + 2 H2O
ROASTER.recipeBuilder()
    .inputs(ore('dustMonocalciumPhosphate') * 15)
    .outputs(metaitem('dustCalciumMetaphosphate') * 9)
    .fluidOutputs(fluid('dense_steam') * 2000)
    .duration(120)
    .EUt(VA[LV])
    .buildAndRegister()

// 3 Ca(PO3)2 + 10 C → Ca3(PO4)2 + P4, no CO since 10kL is exceeding 8kL limit in a LV roaster
ROASTER.recipeBuilder()
    .inputs(ore('dustCalciumMetaphosphate') * 27)
    .inputs(ore('dustAnyPurityCarbon') * 10)
    .circuitMeta(1)
    .outputs(metaitem('dustTricalciumPhosphate') * 13)
    .outputs(metaitem('dustPhosphorus') * 4)
    .duration(360)
    .EUt(VA[LV])
    .buildAndRegister()

// 3 Ca(PO3)2 + 10 C → Ca3(PO4)2 + 10 CO + P4
ROASTER.recipeBuilder()
    .inputs(ore('dustCalciumMetaphosphate') * 27)
    .inputs(ore('dustAnyPurityCarbon') * 10)
    .circuitMeta(2)
    .outputs(metaitem('dustTricalciumPhosphate') * 13)
    .outputs(metaitem('dustPhosphorus') * 4)
    .fluidOutputs(fluid('carbon_monoxide') * 10000)
    .duration(360)
    .EUt(VA[LV])
    .buildAndRegister()

// (2 Ca3(PO4)2 + 6 SiO2 + 10 C -> 6 CaSiO3 + 10 CO + P4) / 2
ERF.recipeBuilder()
        .inputs(ore('dustTricalciumPhosphate') * 13)
        .inputs(ore('dustSiliconDioxide') * 9)
        .inputs(ore('dustAnyPurityCarbon') * 5)
        .outputs(metaitem('dustPhosphorus') * 2)
        .outputs(metaitem('dustCalciumMetasilicate') * 15)
        .fluidOutputs(fluid('carbon_monoxide') * 5000)
        .blastFurnaceTemp(1200)
        .duration(240)
        .EUt(VA[MV])
        .buildAndRegister()

// 3 Ca(OH)2 + 2 H3PO4 -> Ca3(PO4)2 + 6H2O
BR.recipeBuilder()
        .inputs(ore('dustCalciumHydroxide') * 15)
        .fluidInputs(fluid('phosphoric_acid') * 2000)
        .outputs(metaitem('dustTricalciumPhosphate') * 13)
        .fluidOutputs(fluid('water') * 6000)
        .duration(200)
        .EUt(VA[LV])
        .buildAndRegister()

//UNIVERSAL (MV)
//REMOVE APATITE RECIPES

// TODO: Fix later, GTFO changed bone china recipes
// Adapt to that in the future
//mods.gregtech.mixer.removeByInput(8, [item('minecraft:clay_ball'), metaitem('dustStone'), metaitem('dustApatite') * 2], null)
//mods.gregtech.blender.removeByInput(8, [item('minecraft:clay_ball'), metaitem('dustStone'), metaitem('dustApatite') * 2], null)

def apatites = [
        metaitem('dustChlorapatite'),
        metaitem('dustHydroxyapatite'),
        metaitem('dustFluorapatite'),
];

for (apatite in apatites) {
    MIXER.recipeBuilder()
        .inputs(apatite * 2)
        .inputs(item('minecraft:clay_ball'))
        .inputs(ore('dustStone'))
        .outputs(metaitem('gregtechfoodoption:bone_china_clay_dust') * 4)
        .duration(40)
        .EUt(VA[ULV])
        .buildAndRegister()
}

//WET PROCESS
BR.recipeBuilder()
    .inputs(ore('dustHydroxyapatite'))
    .fluidInputs(fluid('sulfuric_acid') * 5000)
    .outputs(metaitem('dustCalciumSulfate') * 30)
    .fluidOutputs(fluid('diluted_phosphoric_acid') * 4000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustFluorapatite'))
    .fluidInputs(fluid('sulfuric_acid') * 5000)
    .outputs(metaitem('dustCalciumSulfate') * 30)
    .fluidOutputs(fluid('phosphoric_acid') * 3000)
    .fluidOutputs(fluid('hydrogen_fluoride') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustChlorapatite'))
    .fluidInputs(fluid('sulfuric_acid') * 5000)
    .outputs(metaitem('dustCalciumSulfate') * 30)
    .fluidOutputs(fluid('phosphoric_acid') * 3000)
    .fluidOutputs(fluid('hydrogen_chloride') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('diluted_phosphoric_acid') * 4000)
    .fluidOutputs(fluid('phosphoric_acid') * 3000)
    .fluidOutputs(fluid('water') * 1000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

//SULFURIC ACID REGENERATION
ROASTER.recipeBuilder()
    .inputs(ore('dustCalciumSulfate') * 6)
    .inputs(ore('dustSiliconDioxide') * 3)
    .outputs(metaitem('dustCalciumMetasilicate') * 5)
    .fluidOutputs(fluid('sulfur_trioxide_reaction_mixture') * 1000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .fluidInputs(fluid('sulfur_trioxide_reaction_mixture') * 1000)
    .notConsumable(ore('dustVanadiumPentoxide'))
    .fluidOutputs(fluid('sulfur_trioxide') * 1000)
    .duration(200)
    .EUt(VA[ULV])
    .buildAndRegister()

//THERMAL PROCESS
ERF.recipeBuilder()
    .inputs(ore('dustFluorapatite') * 2)
    .inputs(ore('dustSiliconDioxide') * 27)
    .inputs(ore('dustAnyPurityCarbon') * 15)
    .outputs(metaitem('dustPhosphorus') * 6)
    .outputs(metaitem('dustCalciumMetasilicate') * 45)
    .outputs(metaitem('dustFluorite') * 3)
    .fluidOutputs(fluid('carbon_monoxide') * 15000)
    .blastFurnaceTemp(1200)
    .duration(720)
    .EUt(VA[MV])
    .buildAndRegister()

ERF.recipeBuilder()
    .inputs(ore('dustChlorapatite') * 2)
    .inputs(ore('dustSiliconDioxide') * 27)
    .inputs(ore('dustAnyPurityCarbon') * 15)
    .outputs(metaitem('dustPhosphorus') * 6)
    .outputs(metaitem('dustCalciumMetasilicate') * 45)
    .outputs(metaitem('dustCalciumChloride') * 3)
    .fluidOutputs(fluid('carbon_monoxide') * 15000)
    .blastFurnaceTemp(1200)
    .duration(720)
    .EUt(VA[MV])
    .buildAndRegister()

ERF.recipeBuilder()
    .inputs(ore('dustHydroxyapatite') * 2)
    .inputs(ore('dustSiliconDioxide') * 27)
    .inputs(ore('dustAnyPurityCarbon') * 15)
    .outputs(metaitem('dustPhosphorus') * 6)
    .outputs(metaitem('dustCalciumMetasilicate') * 45)
    .outputs(metaitem('dustCalciumHydroxide') * 5)
    .fluidOutputs(fluid('carbon_monoxide') * 15000)
    .blastFurnaceTemp(1200)
    .duration(720)
    .EUt(VA[MV])
    .buildAndRegister()

//SPECIALIZED (HV)
MIXER.recipeBuilder()
    .inputs(ore('dustPhosphorite') * 2)
    .fluidInputs(fluid('distilled_water') * 1000)
    .fluidOutputs(fluid('phosphorite_slurry') * 1000)
    .duration(40)
    .EUt(VA[HV])
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('phosphorite_slurry') * 1000)
    .outputs(metaitem('dustPhosphatePulp') * 2)
    .chancedOutput(metaitem('dustClay'), 5000, 0)
    .chancedOutput(metaitem('dustSiliconDioxide') * 3, 5000, 0)
    .fluidOutputs(fluid('wastewater') * 1000)
    .duration(40)
    .EUt(VA[HV])
    .buildAndRegister()

SIFTER.recipeBuilder()
    .inputs(ore('dustPhosphatePulp'))
    .outputs(metaitem('dustFilteredPhosphatePulp'))
    .chancedOutput(metaitem('dustSiliconDioxide'), 2500, 0)
    .duration(20)
    .EUt(VA[HV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustFilteredPhosphatePulp') * 8)
    .fluidInputs(fluid('distilled_water') * 2000)
    .fluidOutputs(fluid('filtered_phosphate_slurry') * 2000)
    .EUt(VA[HV])
    .duration(80)
    .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
    .fluidInputs(fluid('filtered_phosphate_slurry') * 2000)
    .notConsumable(fluid('alkaline_sodium_oleate_solution') * 1000)
    .notConsumable(fluid('heavy_gas_oil') * 100)
    .fluidOutputs(fluid('phosphate_concentrate_slurry') * 1000)
    .fluidOutputs(fluid('limestone_tailing_slurry') * 1000)
    .duration(20)
    .EUt(VA[HV])
    .buildAndRegister()

CLARIFIER.recipeBuilder()
    .fluidInputs(fluid('phosphate_concentrate_slurry') * 1000)
    .outputs(metaitem('dustPhosphateConcentrate') * 16)
    .fluidOutputs(fluid('wastewater') * 1000)
    .duration(20)
    .EUt(VA[HV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustPhosphateConcentrate'))
    .fluidInputs(fluid('sulfuric_acid') * 1500)
    .outputs(metaitem('dustGypsum') * 12)
    .fluidOutputs(fluid('phosphoric_acid') * 1000)
    .duration(20)
    .EUt(VA[HV])
    .buildAndRegister()

//HIGH PURITY
COMPRESSOR.recipeBuilder()
    .inputs(ore('dustPhosphorus'))
    .outputs(metaitem('ingotPhosphorus'))
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

ZONE_REFINER.recipeBuilder()
    .inputs(ore('ingotPhosphorus'))
    .outputs(metaitem('ingotHighPurityPhosphorus'))
    .duration(400)
    .EUt(VA[LV])
    .buildAndRegister()

AUTOCLAVE.recipeBuilder()
    .inputs(ore('dustPhosphorus'))
    .fluidInputs(fluid('water') * 250)
    .chancedOutput(metaitem('dustArsenic'), 500, 50)
    .fluidOutputs(fluid('high_purity_phosphorus_vapor_mixture') * 250)
    .duration(60)
    .EUt(VA[LV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('high_purity_phosphorus_vapor_mixture') * 1000)
    .fluidOutputs(fluid('high_purity_phosphorus') * 576)
    .duration(240)
    .EUt(VA[LV])
    .buildAndRegister()

SOLIDIFIER.recipeBuilder()
    .fluidInputs(fluid('high_purity_phosphorus') * 144)
    .notConsumable(metaitem('shape.mold.ball'))
    .outputs(metaitem('dustHighPurityPhosphorus'))
    .duration(60)
    .EUt(VA[LV])
    .buildAndRegister()

// Compounds

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('sodium_phosphate_solution') * 1000)
    .outputs(metaitem('dustSodiumPhosphate') * 8)
    .fluidOutputs(fluid('water') * 1000)
    .duration(20)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumPhosphate') * 8)
    .fluidInputs(fluid('hydrochloric_acid') * 3000)
    .fluidOutputs(fluid('salty_phosphoric_acid') * 4000)
    .duration(20)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('salty_phosphoric_acid') * 4000)
    .outputs(metaitem('dustSalt') * 6)
    .fluidOutputs(fluid('phosphoric_acid') * 1000)
    .fluidOutputs(fluid('water') * 3000)
    .duration(20)
    .EUt(VA[LV])
    .buildAndRegister()

// Polyphosphoric Acid

ROASTER.recipeBuilder()
    .fluidInputs(fluid('phosphoric_acid') * 6000)
    .outputs(metaitem('dustPolyphosphoricAcid'))
    .fluidOutputs(fluid('dense_steam') * 5000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

// Ammonium phosphates

CSTR.recipeBuilder()
    .circuitMeta(1)
    .fluidInputs(fluid('phosphoric_acid') * 100)
    .fluidInputs(fluid('ammonia_solution') * 100)
    .fluidOutputs(fluid('ammonium_dihydrogen_phosphate_solution') * 50)
    .fluidOutputs(fluid('water') * 50)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister();

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('ammonium_dihydrogen_phosphate_solution') * 1000)
    .outputs(metaitem('dustAmmoniumDihydrogenPhosphate') * 24)
    .fluidOutputs(fluid('water') * 1000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister();

CSTR.recipeBuilder()
    .circuitMeta(2)
    .fluidInputs(fluid('phosphoric_acid') * 50)
    .fluidInputs(fluid('ammonia_solution') * 100)
    .fluidOutputs(fluid('diammonium_hydrogen_phosphate_solution') * 100)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister();

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('diammonium_hydrogen_phosphate_solution') * 2000)
    .outputs(metaitem('dustDiammoniumHydrogenPhosphate') * 15)
    .fluidOutputs(fluid('water') * 2000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister();
