import static prePostInit.Recipemaps.*
import globals.Carbons
import static gregtech.api.GTValues.*

// Tin Dust * 1
mods.gregtech.centrifuge.removeByInput(30, null, [fluid('crude_tin') * 1000])

//CASSITERITE BENEFICIATION
MIXER.recipeBuilder()
        .inputs(ore('dustImpureCassiterite') * 8)
        .fluidInputs(fluid('distilled_water') * 2000)
        .fluidOutputs(fluid('impure_cassiterite_slurry') * 2000)
        .EUt(VA[HV])
        .duration(80)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .fluidInputs(fluid('impure_cassiterite_slurry') * 2000)
        .notConsumable(metaitem('dustSodiumFluorosilicate'))
        .notConsumable(fluid('oleic_acid') * 1000)
        .notConsumable(fluid('methyl_isobutyl_carbinol') * 100)
        .fluidOutputs(fluid('cassiterite_slurry') * 1000)
        .fluidOutputs(fluid('limestone_tailing_slurry') * 1000)
        .EUt(VA[HV])
        .duration(80)
        .buildAndRegister()

CLARIFIER.recipeBuilder()
        .fluidInputs(fluid('cassiterite_slurry') * 1000)
        .outputs(metaitem('dustCassiterite') * 16)
        .fluidOutputs(fluid('wastewater') * 1000)
        .EUt(VA[LV])
        .duration(20)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('limestone_tailing_slurry') * 1000)
        .outputs(metaitem('dustLimestoneTailings') * 2)
        .fluidOutputs(fluid('wastewater') * 1000)
        .EUt(VA[LV])
        .duration(20)
        .buildAndRegister()

ELECTROMAGNETIC_SEPARATOR.recipeBuilder()
        .inputs(ore('dustCassiterite'))
        .outputs(metaitem('dustConcentrateCassiterite'))
        .chancedOutput(metaitem('dustHematite'), 2500, 0)
        .EUt(VA[ULV])
        .duration(100)
        .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
        .inputs(metaitem('dustConcentrateCassiterite'))
        .fluidInputs(fluid('ammonia_solution') * 120)
        .fluidOutputs(fluid('ammonium_tungstate_solution') * 60)
        .outputs(metaitem('dustLeachedCassiteriteConcentrate'))
        .EUt(VA[EV])
        .duration(100)
        .buildAndRegister()

//SMELTING
for (combustible in Carbons.combustibles()) {
    REACTION_FURNACE.recipeBuilder()
            .inputs(ore('dustConcentrateCassiterite'))
            .inputs(ore(combustible.name) * combustible.equivalent(2))
            .outputs(metaitem(combustible.byproduct))
            .fluidOutputs(fluid('crude_tin') * 190)
            .fluidOutputs(fluid('tin_dross') * 25)
            .fluidOutputs(fluid('carbon_dioxide') * 1000)
            .EUt(VA[MV])
            .duration(160)
            .buildAndRegister()

    REACTION_FURNACE.recipeBuilder()
            .inputs(ore('dustLeachedCassiteriteConcentrate'))
            .inputs(ore(combustible.name) * combustible.equivalent(2))
            .outputs(metaitem(combustible.byproduct))
            .fluidOutputs(fluid('crude_tin') * 190)
            .fluidOutputs(fluid('tin_dross') * 25)
            .fluidOutputs(fluid('carbon_dioxide') * 1000)
            .EUt(VA[MV])
            .duration(160)
            .buildAndRegister()
}

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('tin_dross') * 100)
        .fluidOutputs(fluid('crude_tin') * 85)
        .fluidOutputs(fluid('iron') * 15)
        .EUt(VA[LV])
        .duration(80)
        .buildAndRegister()

SOLIDIFIER.recipeBuilder()
        .notConsumable(metaitem('shape.mold.ingot'))
        .fluidInputs(fluid('crude_tin') * 216)
        .outputs(metaitem('ingotTin'))
        .EUt(VA[ULV])
        .duration(20)
        .buildAndRegister()

SOLIDIFIER.recipeBuilder()
        .notConsumable(metaitem('shape.mold.ingot'))
        .fluidInputs(fluid('decopperized_tin') * 180)
        .outputs(metaitem('ingotTin'))
        .EUt(VA[ULV])
        .duration(20)
        .buildAndRegister()

AUTOCLAVE.recipeBuilder()
        .notConsumable(fluid('sulfuric_acid') * 1000)
        .fluidInputs(fluid('hot_hp_oxygen') * 1000)
        .inputs(ore('dustTin'))
        .outputs(metaitem('dustPurifiedTinIiOxide') * 2)
        .EUt(VA[HV])
        .duration(120)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(ore('dustPurifiedTinIiOxide') * 2)
        .fluidInputs(fluid('hydrogen') * 2000)
        .outputs(metaitem('dustHighPurityTin'))
        .fluidOutputs(fluid('dense_steam') * 1000)
        .EUt(VA[MV])
        .duration(120)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .inputs(ore('dustAnyPuritySulfur'))
        .fluidInputs(fluid('crude_tin') * 5760)
        .fluidOutputs(fluid('decopperized_tin') * 5760)
        .outputs(metaitem('dustCopperMonosulfide') * 2)
        .EUt(VA[LV])
        .duration(300)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .fluidInputs(fluid('oxygen') * 2000)
        .inputs(ore('dustCopperMonosulfide') * 2)
        .outputs(metaitem('dustCopper'))
        .fluidOutputs(fluid('sulfur_dioxide') * 1000)
        .EUt(VA[LV])
        .duration(120)
        .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
        .fluidInputs(fluid('decopperized_tin') * 2880)
        .notConsumable(metaitem('wireFineAluminium'))
        .chancedOutput(metaitem('dustAntimony'), 500, 0)
        .chancedOutput(metaitem('dustBismuth'), 500, 0)
        .fluidOutputs(fluid('tin') * 2880)
        .EUt(VA[LV])
        .duration(160)
        .buildAndRegister()
