AUTOCLAVE = recipemap("autoclave")
MIXER = recipemap("mixer")
ROASTER = recipemap("roaster")
CHEMICAL_BATH = recipemap("chemical_bath")
BR = recipemap("batch_reactor")
CSTR = recipemap('continuous_stirred_tank_reactor')
BCR = recipemap("bubble_column_reactor")

AUTOCLAVE.recipeBuilder()
    .inputs(metaitem('anode_slime.copper'))
    .fluidInputs(fluid('sulfuric_acid') * 500)
    .fluidInputs(fluid('oxygen') * 500)
    .outputs(metaitem('anode_slime.decopperized'))
    .fluidOutputs(fluid('copper_sulfate_solution') * 500)
    .duration(120)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(metaitem('anode_slime.decopperized'))
    .inputs(ore('dustSodaAsh'))
    .fluidInputs(fluid('distilled_water'))
    .fluidOutputs(fluid('copper_anode_slime_paste'))
    .duration(120)
    .EUt(30)
    .buildAndRegister()

ROASTER.recipeBuilder()
    .fluidInputs(fluid('copper_anode_slime_paste'))
    .outputs(metaitem('dustSeleniumTelluriumConcentrate'))
    .fluidOutputs(fluid('steam'))
    .duration(120)
    .EUt(120)
    .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
    .inputs(ore('dustSeleniumTelluriumConcentrate'))
    .fluidInputs(fluid('distilled_water'))
    .outputs(metaitem('dustTelluriumResidue'))
    .fluidOutputs(fluid('selenium_liquor'))
    .duration(120)
    .EUt(30)
    .buildAndRegister()

CSTR.recipeBuilder()
    .fluidInputs(fluid('selenium_liquor'))
    .fluidInputs(fluid('hydrochloric_acid'))
    .fluidOutputs(fluid('acidic_selenite_solution'))
    .fluidOutputs(fluid('chlorine'))
    .duration(6)
    .EUt(30)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('acidic_selenite_solution'))
    .fluidInputs(fluid('sulfur_dioxide'))
    .chancedOutput(metaitem('dustSelenium'), 0000, 0)
    .fluidOutputs(fluid('wastewater'))
    .duration(6)
    .EUt(30)
    .buildAndRegister()

// Further refining