BR = recipemap('batch_reactor')
CHEMICAL_BATH = recipemap('chemical_bath')
EBF = recipemap('electric_blast_furnace')
ELECTROLYTIC_CELL = recipemap('electrolytic_cell')

EBF.recipeBuilder()
    .inputs(ore('dustTelluriumResidue'))
    .outputs(metaitem('dustRawElectrum'))
    .outputs(metaitem('dustTelluriumSlag'))
    .blastFurnaceTemp(1400)
    .duration(120)
    .EUt(240)
    .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
    .inputs(ore('dustTelluriumSlag'))
    .fluidInputs(fluid('distilled_water'))
    .fluidOutputs(fluid('tellurium_liquor'))
    .duration(120)
    .EUt(30)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('tellurium_liquor'))
    .fluidInputs(fluid('sulfuric_acid'))
    .outputs(metaitem('dustCrudeTelluriumDioxide'))
    .fluidOutputs(fluid('wastewater'))
    .duration(120)
    .EUt(30)
    .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
    .inputs(ore('dustCrudeTelluriumDioxide'))
    .fluidInputs(fluid('sodium_hydroxide_solution'))
    .fluidOutputs(fluid('sodium_tellurite_solution'))
    .duration(120)
    .EUt(30)
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .notConsumable(metaitem('graphite_electrode'))
    .notConsumable(metaitem('stickStainlessSteel'))
    .fluidInputs(fluid('sodium_tellurite_solution'))
    .outputs(metaitem('dustTellurium'))
    .fluidOutputs(fluid('sodium_hydroxide_solution'))
    .fluidOutputs(fluid('oxygen'))
    .duration(120)
    .EUt(30)
    .buildAndRegister()

// Further refining
