CSTR = recipemap('continuous_stirred_tank_reactor')
FBR = recipemap('fixed_bed_reactor')
BR = recipemap('batch_reactor')
POLYMERIZATION = recipemap('polymerization_tank')
FLUIDIZEDBR = recipemap('fluidized_bed_reactor')
DISTILLATION_TOWER = recipemap('distillation_tower')
SIFTER = recipemap('sifter')
CENTRIFUGE = recipemap('centrifuge')

// Diphenyl Isophthalate

BR.recipeBuilder()
.fluidInputs(fluid('phenol') * 1000)
.inputs(ore('dustSodiumHydroxide') * 3)
.fluidOutputs(fluid('sodium_phenoxide_solution') * 1000)
.duration(160)
.EUt(30)
.buildAndRegister()

CSTR.recipeBuilder()
.fluidInputs(fluid('isophthaloyl_chloride_solution') * 150)
.fluidInputs(fluid('sodium_phenoxide_solution') * 100)
.fluidOutputs(fluid('diphenyl_isophthalate_solution') * 150)
.duration(10)
.EUt(30)
.buildAndRegister()

// 3,3'-Dichlorobenzidine

FBR.recipeBuilder()
.fluidInputs(fluid('two_chloronitrobenzene') * 288)
.fluidInputs(fluid('hot_hp_hydrogen') * 2000)
.notConsumable(ore('catalystBedPalladium'))
.fluidOutputs(fluid('two_two_dichlorohydrazobenzene_solution') * 1000)
.duration(300)
.EUt(120)
.buildAndRegister()

CSTR.recipeBuilder()
.fluidInputs(fluid('two_two_dichlorohydrazobenzene_solution') * 50)
.fluidInputs(fluid('sulfuric_acid') * 50)
.fluidOutputs(fluid('dichlorobenzidine_solution') * 100)
.duration(10)
.EUt(120)
.buildAndRegister()

// 3,3-Diaminobenzidine

FLUIDIZEDBR.recipeBuilder()
.fluidInputs(fluid('dichlorobenzidine_solution') * 100)
.fluidInputs(fluid('hot_compressed_ammonia') * 200)
.notConsumable(ore('dustCopper'))
.fluidOutputs(fluid('diaminobenzidine_solution') * 100)
.fluidOutputs(fluid('hydrogen_chloride') * 200)
.duration(5)    
.EUt(60)
.buildAndRegister()

// PBI

BR.recipeBuilder()
.fluidInputs(fluid('diaminobenzidine_solution') * 2000)
.fluidInputs(fluid('diphenyl_isophthalate_solution') * 3000)
.fluidOutputs(fluid('pbi_polymerization_mix') * 5000)
.duration(200)
.EUt(30)
.buildAndRegister()

POLYMERIZATION.recipeBuilder()
.fluidInputs(fluid('pbi_polymerization_mix') * 5000)
.fluidOutputs(fluid('pbi_pre_polymer_foam') * 25000)
.duration(200)
.EUt(240)
.buildAndRegister()

POLYMERIZATION.recipeBuilder()
.fluidInputs(fluid('pbi_pre_polymer_foam') * 25000)
.fluidOutputs(fluid('impure_pbi_solution') * 7000)
.duration(200)
.EUt(240)
.buildAndRegister()

CENTRIFUGE.recipeBuilder()
.fluidInputs(fluid('dimethylacetamide') * 1000)
.fluidInputs(fluid('impure_pbi_solution') * 7000)
.fluidOutputs(fluid('pbi_solution') * 1000)
.fluidOutputs(fluid('pbi_waste') * 8000)
.duration(300)
.EUt(120)
.buildAndRegister()

SIFTER.recipeBuilder()
.fluidInputs(fluid('pbi_solution') * 1000)
.fluidOutputs(fluid('dimethylacetamide') * 1000)
.outputs(metaitem('dustPolybenzimidazole') * 7)
.duration(300)
.EUt(120)
.buildAndRegister()

DISTILLATION_TOWER.recipeBuilder()
.fluidInputs(fluid('pbi_waste') * 8000)
.fluidOutputs(fluid('toluene') * 2000)
.fluidOutputs(fluid('phenol') * 2000)
.fluidOutputs(fluid('water') * 3000)
.fluidOutputs(fluid('dichloroethane') * 1000)
.duration(300)
.EUt(240)
.buildAndRegister()