import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// Polyethylene glycol (PEG)

POLYMERIZATION_TANK.recipeBuilder()
    .fluidInputs(fluid('ethylene_oxide') * 1000)
    .fluidInputs(fluid('sodium_hydroxide_solution') * 1000)
    .fluidOutputs(fluid('polyethylene_glycol_solution') * 2000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('polyethylene_glycol_solution') * 2000)
    .fluidInputs(fluid('phosphoric_acid') * 500)
    .fluidOutputs(fuid('neutralized_polyethylene_glycol_solution') * 3000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('neutralized_polyethylene_glycol_solution') * 3000)
    .outputs(ore('dustDisodiumPhosphate') * 8)
    .fluidOutputs(fluid('polyethylene_glycol') * 1000)
    .fluidOutputs(fluid('water') * 2000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

// Polyvinyl Alcohol (PVA)

BR.recipeBuilder()
    .fluidInputs(fluid('polyvinyl_acetate') * 144)
    .fluidInputs(fluid('ethanol') * 1000)
    .outputs(metaitem('dustPolyvinylAlcohol'))
    .fluidOutputs(fluid('ethyl_acetate') * 1000)
    .duration(400)
    .EUt(VA[LV])
    .buildAndRegister()

CSTR.recipeBuilder()
    .fluidInputs(fluid('ethyl_acetate') * 50)
    .notConsumable(fluid('sulfuric_acid') * 50)
    .fluidOutputs(fluid('ethanol') * 50)
    .fluidOutputs(fluid('acetic_acid') * 50)
    .duration(20)
    .EUt(VA[LV])
    .buildAndRegister()

// Polyethylenimine (PEI)

CSTR.recipeBuilder()
    .fluidInputs(fluid('ethanolamine') * 50)
    .fluidInputs(fluid('sulfuric_acid') * 50)
    .fluidOutputs(fluid('two_aminoethyl_hydrogen_sulfate_solution') * 50)
    .duration(20)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumHydroxide') * 6)
    .fluidInputs(fluid('two_aminoethyl_hydrogen_sulfate_solution') * 1000)
    .fluidOutputs(fluid('ethylenimine_solution') * 3000)
    .duration(400)
    .EUt(VA[MV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('ethylenimine_solution') * 2000)
    .outputs(ore('dustSodiumSulfate') * 7)
    .fluidOutputs(fluid('ethylenimine') * 1000)
    .fluidOutputs(fluid('water') * 2000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

POLYMERIZATION_TANK.recipeBuilder()
    .fluidInputs(fluid('ethylenimine') * 1000)
    .fluidInputs(fluid('diluted_sulfuric_acid') * 2000)
    .fluidOutputs(fluid('polyethylenimine_solution') * 3000)
    .duration(300)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumHydroxide') * 6)
    .fluidInputs(fluid('polyethylenimine_solution') * 3000)
    .fluidOutputs(fluid('crude_polyethylenimine') * 1000)
    .fluidOutputs(fluid('wastewater') * 3000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
    .fluidInputs(fluid('crude_polyethylenimine') * 1000)
    .fluidInputs(fluid('ethanol') * 250)
    .fluidOutputs(fluid('polyethylenimine') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

// Polyvinylpyrrolidone (PVP)

AUTOCLAVE.recipeBuilder()
    .notConsumable(ore('dustPotassium'))
    .fluidInputs(fluid('acetylene') * 1000)
    .fluidInputs(fluid('two_pyrrolidone') * 1000)
    .fluidOutputs(fluid('n_vinylpyrrolidone') * 1000)
    .duration(400)
    .EUt(VA[MV])
    .buildAndRegister()

POLYMERIZATION_TANK.recipeBuilder()
    .fluidInputs(fluid('n_vinylpyrrolidone') * 1000)
    .fluidInputs(fluid('distilled_water') * 990)
    .fluidInputs(fluid('hydrogen_peroxide_solution') * 10)
    .fluidOutputs(fluid('polyvinylpyrrolidone_solution') * 1000)
    .duration(400)
    .EUt(VA[MV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('polyvinylpyrrolidone_solution') * 1000)
    .outputs(metaitem('dustPolyvinylpyrrolidone'))
    .fluidOutputs(fluid('wastewater') * 1000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()