import globals.Globals

// Every base component needed for EUV lithography

ASSEMBLER = recipemap('assembler')
BR = recipemap('batch_reactor')
DT = recipemap('distillation_tower')
EBF = recipemap('electric_blast_furnace')
POLYMERIZATION = recipemap('polymerization_tank')
REACTION_FURNACE = recipemap('reaction_furnace')
SPUTTERING = recipemap('sputter_deposition')

/// LTE (Low Temperature Expansion) Substrate: Tianium Doped Silica Glass
// This pick is based on [1]

// 1 Titanium Tetrachloride + 4 Isopropanol + 4 Ammonia ==[Benzene]==> 1 Titanium Tetraisopropoxide (benene) + 4 Ammonium Chloride [LCR]
// Based on [4]
LCR.recipeBuilder()
    .fluidInputs(fluid('titanium_tetrachloride') * 1000)
    .fluidInputs(fluid('isopropyl_alcohol') * 4000)
    .fluidInputs(fluid('ammonia') * 4000)
    .fluidInputs(fluid('benzene') * 1000)
    .outputs(ore('dustAmmoniumChloride').first() * 24)
    .fluidOutputs(fluid('titanium_tetraisopropoxide_solution') * 1000)
    .EUt(Globals.voltAmps[3])
    .duration(200)
    .buildAndRegister();

DT.recipeBuilder()
    .fluidInputs(fluid('titanium_tetraisopropoxide_solution') * 1000)
    .fluidOutputs(fluid('titanium_tetraisopropoxide') * 1000)
    .fluidOutputs(fluid('benzene') * 1000)
    .EUt(Globals.voltAmps[2])
    .duration(80)
    .buildAndRegister();


// 1 Silicon Tetrachloride + 4 Ethanol + 4 Ammonia = 1 Tetraethoxysilane + 4 Ammonium Chloride
// Based on [4]
LCR.recipeBuilder()
    .fluidInputs(fluid('silicon_tetrachloride') * 1000)
    .fluidInputs(fluid('ethanol') * 4000)
    .fluidInputs(fluid('ammonia') * 4000)
    .outputs(ore('dustAmmoniumChloride').first() * 24)
    .fluidOutputs(fluid('tetraethoxysilane') * 1000)
    .EUt(Globals.voltAmps[1])
    .duration(100)
    .buildAndRegister();

// 1:15 Titanium Tetraisopropoxide : TEOS dissolved in ethanol
// Based on [2, 3]
MIXER.recipeBuilder()
    .fluidInputs(fluid('titanium_tetraisopropoxide') * 125)
    .fluidInputs(fluid('tetraethoxysilane') * 1875)
    .fluidInputs(fluid('ethanol') * 1000)
    .fluidOutputs(fluid('titanium_silicon_alkoxide_ethanol_solution') * 3000)
    .EUt(Globals.voltAmps[2])
    .duration(80)
    .buildAndRegister();

// Hydrolyzation catalyst is not accurate to literature; adjusted for gameplay
// Based on [2, 3]
POLYMERIZATION.recipeBuilder()
    .fluidInputs(fluid('titanium_silicon_alkoxide_ethanol_solution') * 3000)
    .fluidInputs(fluid('distilled_water') * 1000)
    .fluidInputs(fluid('acetic_acid') * 500)
    .outputs(ore('dustTitaniumDopedSilicaGlass').first() * 3) // gel
    .fluidOutputs(fluid('wastewater') * 3000)
    .EUt(Globals.voltAmps[3])
    .duration(400)
    .buildAndRegister();

// Smelt recipe is autogenerated
// Based on [2, 3]
EBF.recipeBuilder()
    .inputs(ore('dustTitaniumDopedSilicaGlass'))
    .notConsumable(metaitem('shape.mold.plate'))
    .outputs(ore('plateTitaniumDopedSilicaGlass').first())
    .EUt(Globals.voltAmps[2])
    .blastFurnaceTemp(1200)
    .duration(200)
    .buildAndRegister();

/// EUV Photomask
// Electrostatic Chuck: CrN or TaB (not implemented)
SPUTTERING.recipeBuilder()
    .inputs(ore('foilChrome'))
    .inputs(ore('plateTitaniumDopedSilicaGlass'))
    .fluidInputs(fluid('argon') * 200)
    .fluidInputs(fluid('nitrogen') * 250)
    .outputs(metaitem('euv_photomask.chuck_applied'))
    .EUt(Globals.voltAmps[4])
    .duration(400)
    .buildAndRegister();

// Mo/Si layer
SPUTTERING.recipeBuilder()
    .inputs(metaitem('euv_photomask.chuck_applied') * 1)
    .inputs(ore('foilSilicon') * 1)
    .inputs(ore('foilMolybdenum') * 1)
    .fluidInputs(fluid('argon') * 200)
    .fluidInputs(fluid('krypton') * 200)
    .outputs(metaitem('euv_photomask.mo_si_coated') * 1)
    .EUt(Globals.voltAmps[4])
    .duration(400)
    .buildAndRegister();

// Ru Capping
SPUTTERING.recipeBuilder()
    .inputs(metaitem('euv_photomask.mo_si_coated') * 1)
    .inputs(ore('foilRuthenium') * 1)
    .fluidInputs(fluid('krypton') * 200)
    .outputs(metaitem('euv_photomask.ru_capped') * 1)
    .EUt(Globals.voltAmps[4])
    .duration(400)
    .buildAndRegister();

// TaN abosrber
SPUTTERING.recipeBuilder()
    .inputs(metaitem('euv_photomask.ru_capped') * 1)
    .inputs(ore('foilTantalum') * 1)
    .notConsumable(metaitem('pvd_apparatus.ion_source') * 1)
    .fluidInputs(fluid('krypton') * 200)
    .fluidInputs(fluid('nitrogen') * 1000)
    .outputs(metaitem('euv_photomask.absorber_applied') * 1)
    .EUt(Globals.voltAmps[4])
    .duration(400)
    .buildAndRegister();

// Antireflective Coating: YF3
// material credit to planetme, [6]
BR.recipeBuilder()
    .inputs(ore('dustYttriumHydroxide') * 7)
    .fluidInputs(fluid('hydrogen_fluoride') * 3000)
    .outputs(ore('dustYttriumTrifluoride').first() * 4)
    .fluidOutputs(fluid('water') * 3000)
    .EUt(7)
    .duration(30)
    .buildAndRegister()

SPUTTERING.recipeBuilder()
    .inputs(metaitem('euv_photomask.absorber_applied') * 1)
    .inputs(ore('dustSmallYttriumTrifluoride') * 4)
    .fluidInputs(fluid('argon') * 200)
    .outputs(metaitem('euv_photomask.blank') * 1)
    .EUt(Globals.voltAmps[4])
    .duration(400)
    .buildAndRegister();


/// EUV Components
// Laser
ASSEMBLER.recipeBuilder()
    .inputs(metaitem('laser.fast_axial_gas_co2') * 4)
    .inputs(metaitem('laser.nd_yag') * 1)
    .inputs(metaitem('electric.pump.ev') * 1)
    .inputs(ore('circuitEv') * 4)
    .inputs(ore('plateTungstenSteel') * 6)
    .inputs(ore('screwTungstenSteel') * 8)
    .fluidInputs(fluid('soldering_alloy') * 1152)
    .outputs(item('susy:euv_lithographer_component'))
    .duration(100)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

// Recticle
ASSEMBLER.recipeBuilder()
    .inputs(metaitem('conveyor.module.ev') * 2)
    .inputs(ore('frameGtTungstenSteel') * 1)
    .inputs(ore('gearTungstenSteel') * 4)
    .inputs(ore('plateTungstenSteel') * 6)
    .inputs(ore('screwTungstenSteel') * 8)
    .fluidInputs(fluid('soldering_alloy') * 1152)
    .outputs(item('susy:euv_lithographer_component', 1))
    .duration(100)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

// Mirror
ASSEMBLER.recipeBuilder()
    .inputs(metaitem('mirror.molybdenum_silicon') * 1)
    .inputs(metaitem('electric.motor.ev') * 2)
    .inputs(ore('gearSmallTungstenSteel') * 4)
    .inputs(ore('frameGtTungstenSteel') * 1)
    .inputs(ore('plateTungstenSteel') * 5)
    .inputs(ore('screwTungstenSteel') * 8)
    .fluidInputs(fluid('soldering_alloy') * 1152)
    .outputs(item('susy:euv_lithographer_component', 2))
    .duration(100)
    .EUt(Globals.voltAmps[1])
    .buildAndRegister()

// Others are not registered because they might not even be used, and their recipes are straight forward

/*
References:
[1] Mitsuhiro Kawata, Akira Takada, Hideaki Hayashi, Naoki Sugimoto, Shinya Kikugawa, "Novel low thermal expansion material for EUV application," Proc. SPIE 6151, Emerging Lithographic Technologies X, 61511A (23 March 2006); https://doi.org/10.1117/12.655931 
[2] K. Kamiya, S. Sakka, Thermal expansion of TiO2∙SiO2 and TiO2∙GeO2 glasses, Journal of Non-Crystalline Solids, Volume 52, Issues 1–3, 1982,Pages 357-363, ISSN 0022-3093, https://doi.org/10.1016/0022-3093(82)90310-6.
[3] Kamiya, K., Sakka, S. TiO2-SiO2 glasses prepared from metal alkoxides. J Mater Sci 15, 2937–2939 (1980). https://doi.org/10.1007/BF00550569
[4] D.C. Bradley, R.C. Mehrotra, I.P. Rothwell, A. Singh, 2 - Homometallic Alkoxides, Editor(s): D.C. Bradley, R.C. Mehrotra, I.P. Rothwell, A. Singh, Alkoxo and Aryloxo Derivatives of Metals, Academic Press, 2001, Pages 3-181, ISBN 9780121241407, https://doi.org/10.1016/B978-012124140-7/50002-5.
[5] Kaufman & Robinson, “Gridded Ion Beam Sources,” BeamTec GmbH, brochure, Feb. 2019. Available: https://www.beamtec.de/wp-content/uploads/2019/02/Gridded-Ion-Source-Brochure.pdf.
[6] Lei Pei, Zhu Jiaqi, Zhu Yuankun, Han Jiecai, Preparation and optical properties of sputtered-deposition yttrium fluoride film, Nuclear Instruments and Methods in Physics Research Section B: Beam Interactions with Materials and Atoms, Volume 307, 2013, Pages 429-433, ISSN 0168-583X, https://doi.org/10.1016/j.nimb.2013.02.047.
*/