import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*
import gregtech.api.recipes.recipeproperties.RecipeProperty
import gregtech.api.recipes.RecipeBuilder
import static gregtech.api.recipes.RecipeMaps.*
import gregtech.api.unification.material.Materials.*

import gregtech.api.recipes.ModHandler
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.api.unification.stack.UnificationEntry

import postInit.utils.RecyclingHelper

log.infoMC("Running SpaceSuit.groovy...")


VACUUM_CHAMBER.recipeBuilder() //FIXME: REPLACE WITH EVAPORATION DEPOSITION
        .inputs(metaitem('mylar'))
        .inputs(ore('dustSmallHighPurityAluminium'))
        .outputs(metaitem('sheet.aluminized_mylar'))
        .duration(100)
        .EUt(VA[HV])
        .buildAndRegister()

FORMING_PRESS.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam'))
        .inputs(metaitem('foilNeoprene'))
        .outputs(metaitem('sheet.neoprene_coated_nylon'))
        .duration(20)
        .EUt(VA[MV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('threadNomex') * 3)
        .inputs(metaitem('threadKevlar') * 3)
        .inputs(metaitem('threadExpandedPolytetrafluoroethylene') * 3)
        .outputs(metaitem('sheet.ortho_fabric'))
        .duration(20)
        .EUt(VA[MV])
        .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam'))
        .fluidInputs(fluid('polyurethane') * 36)
        .outputs(metaitem('sheet.urethane_coated_nylon'))
        .duration(120)
        .EUt(VA[MV])
        .buildAndRegister()


ASSEMBLER.recipeBuilder()
        .inputs(metaitem('ringAluminium'))
        .inputs(metaitem('platePolycarbonate') * 4)
        .outputs(metaitem('space_suit.pressure.helmet'))
        .duration(800)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('plateReinforcedEpoxyResin') * 5)
        .inputs(metaitem('sheet.urethane_coated_nylon') * 10)
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 10)
        .inputs(metaitem('sheet.neoprene_coated_nylon') * 10)
        .inputs(metaitem('ringTitanium') * 8)
        .inputs(metaitem('ringSiliconeRubber') * 2)
        .outputs(metaitem('space_suit.pressure.chest'))
        .circuitMeta(1)
        .duration(1200)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('sheet.urethane_coated_nylon'))
        .inputs(metaitem('sheet.neoprene_coated_nylon'))
        .inputs(metaitem('foilPolyethyleneTerephthalate'))
        .inputs(metaitem('ringTitanium') * 2)
        .outputs(metaitem('space_suit.pressure.gloves'))
        .circuitMeta(2)
        .duration(300)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('sheet.urethane_coated_nylon') * 6)
        .inputs(metaitem('sheet.neoprene_coated_nylon') * 6)
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 6)
        .outputs(metaitem('space_suit.pressure.leggings'))
        .circuitMeta(3)
        .duration(1000)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('plateReinforcedEpoxyResin') * 2)
        .inputs(metaitem('sheet.urethane_coated_nylon') * 2)
        .inputs(metaitem('sheet.neoprene_coated_nylon') * 2)
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 2)
        .outputs(metaitem('space_suit.pressure.boots'))
        .circuitMeta(4)
        .duration(600)
        .EUt(VA[EV])
        .buildAndRegister()


ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam') * 5)
        .inputs(ore('pipeTinyFluidEthyleneVinylAcetate') * 25)
        .inputs(metaitem('plateSpandex') * 5)
        .inputs(metaitem('ringTitanium') * 8)
        .outputs(metaitem('space_suit.cooling.chest'))
        .circuitMeta(1)
        .duration(1000)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam') * 4)
        .inputs(ore('pipeTinyFluidEthyleneVinylAcetate') * 20)
        .inputs(metaitem('plateSpandex') * 4)
        .outputs(metaitem('space_suit.cooling.leggings'))
        .circuitMeta(2)
        .duration(750)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolytetrafluoroethylene') * 2)
        .inputs(metaitem('sheet.neoprene_coated_nylon') * 2)
        .inputs(metaitem('foilPolypropylene') * 2)
        .inputs(ore('pipeTinyFluidEthyleneVinylAcetate') * 10)
        .inputs(metaitem('plateSpandex') * 2)
        .outputs(metaitem('space_suit.cooling.boots'))
        .circuitMeta(3)
        .duration(400)
        .EUt(VA[EV])
        .buildAndRegister()


ASSEMBLER.recipeBuilder()
        .inputs(metaitem('platePolycarbonate') * 4)
        .inputs(metaitem('foilPolysulfone') * 2)
        .inputs(metaitem('plateReinforcedEpoxyResin') * 2)
        .inputs(metaitem('ringSiliconeRubber') * 2)
        .inputs(metaitem('ringStainlessSteel'))
        .inputs(metaitem('boltStainlessSteel') * 4)
        .outputs(metaitem('space_suit.thermal.helmet'))
        .duration(1800)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 35)
        .inputs(metaitem('sheet.aluminized_mylar') * 35)
        .inputs(metaitem('sheet.ortho_fabric') * 5)
        .inputs(metaitem('ringTitanium') * 8)
        .outputs(metaitem('space_suit.thermal.chest'))
        .circuitMeta(1)
        .duration(3000)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 7)
        .inputs(metaitem('sheet.aluminized_mylar') * 7)
        .inputs(metaitem('sheet.ortho_fabric'))
        .inputs(metaitem('foilSiliconeRubber'))
        .outputs(metaitem('space_suit.thermal.gloves'))
        .circuitMeta(2)
        .duration(800)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 28)
        .inputs(metaitem('sheet.aluminized_mylar') * 28)
        .inputs(metaitem('sheet.ortho_fabric') * 4)
        .outputs(metaitem('space_suit.thermal.leggings'))
        .circuitMeta(3)
        .duration(2400)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 14)
        .inputs(metaitem('sheet.aluminized_mylar') * 14)
        .inputs(metaitem('sheet.ortho_fabric') * 2)
        .inputs(metaitem('honeycomb.aluminium') * 2)
        .outputs(metaitem('space_suit.thermal.boots'))
        .circuitMeta(4)
        .duration(1500)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam') * 2)
        .inputs(metaitem('dustSodiumPolyacrylate') * 2)
        .outputs(metaitem('space_suit.mag'))
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('battery.re.hv.lithium') * 2)
        .inputs(metaitem('large_fluid_cell.titanium') * 4)
        .inputs(metaitem('electric.pump.ev') * 4)
        .inputs(ore('pipeTinyFluidEthyleneVinylAcetate') * 20)
        .inputs(ore('circuitHv') * 2)
        .inputs(metaitem('dustActivatedCarbon') * 2)
        .inputs(metaitem('hepa_filter'))
        .inputs(metaitem('plateReinforcedEpoxyResin') * 6)
        .inputs(metaitem('cableGtSingleAluminium') * 8)
        .fluidInputs(fluid('water') * 8000)
        .outputs(metaitem('space_suit.plss'))
        .duration(2500)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('space_suit.pressure.helmet'))
        .inputs(metaitem('space_suit.thermal.helmet'))
        .outputs(metaitem('susy:astronaut_helmet'))
        .duration(600)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('space_suit.pressure.chest'))
        .inputs(metaitem('space_suit.cooling.chest'))
        .inputs(metaitem('space_suit.thermal.chest'))
        .inputs(metaitem('space_suit.pressure.gloves'))
        .inputs(metaitem('space_suit.thermal.gloves'))
        .inputs(metaitem('space_suit.plss'))
        .outputs(metaitem('susy:astronaut_chestplate'))
        .duration(1000)
        .EUt(VA[EV])
        .buildAndRegister()

crafting.shapelessBuilder()
    .name("susy:space_suit_fill")
    .output(metaitem('susy:astronaut_chestplate').withNbt(['oxygen': 3600.0D]))
    .input(metaitem('susy:astronaut_chestplate').mark('tank')) 
    .input(metaitem('dustCalciumHydroxide'))
    .recipeFunction { output, inputs, info -> 
        output.getTagCompound().setDouble("damage", inputs['tank'].getTagCompound().getDouble("damage"))
    }.register()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('space_suit.pressure.leggings'))
        .inputs(metaitem('space_suit.cooling.leggings'))
        .inputs(metaitem('space_suit.thermal.leggings'))
        .inputs(metaitem('space_suit.mag'))
        .outputs(metaitem('susy:astronaut_leggings'))
        .duration(800)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('space_suit.pressure.boots'))
        .inputs(metaitem('space_suit.cooling.boots'))
        .inputs(metaitem('space_suit.thermal.boots'))
        .outputs(metaitem('susy:astronaut_boots'))
        .duration(400)
        .EUt(VA[EV])
        .buildAndRegister()

POLYMERIZATION_TANK.recipeBuilder()
        .inputs(metaitem('dustTinyPotassiumPersulfate'))
        .fluidInputs(fluid('acrylic_acid') * 1000)
        .fluidOutputs(fluid('polyacrylic_acid') * 1000)
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister()

CSTR.recipeBuilder()
        .fluidInputs(fluid('polyacrylic_acid') * 50)
        .fluidInputs(fluid('sodium_hydroxide_solution') * 50)
        .fluidOutputs(fluid('sodium_polyacrylate_solution') * 50)
        .duration(1)
        .EUt(VA[LV])
        .buildAndRegister()

SIFTER.recipeBuilder()
        .fluidInputs(fluid('sodium_polyacrylate_solution') * 1000)
        .notConsumable(metaitem('item_filter'))
        .outputs(metaitem('dustWetSodiumPolyacrylate') * 9)
        .fluidOutputs(fluid('water') * 500)
        .duration(90)
        .EUt(VA[LV])
        .buildAndRegister()

DRYER.recipeBuilder()
        .inputs(metaitem('dustWetSodiumPolyacrylate') * 9)
        .outputs(metaitem('dustSodiumPolyacrylate') * 9)
        .fluidOutputs(fluid('dense_steam') * 500)
        .duration(120)
        .EUt(VA[LV])
        .buildAndRegister()
