import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*
import gregtech.api.recipes.recipeproperties.RecipeProperty
import gregtech.api.recipes.RecipeBuilder
import static gregtech.api.recipes.RecipeMaps.*
import gregtech.api.unification.material.Materials.*

import gregtech.api.recipes.ModHandler
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.api.unification.stack.UnificationEntry

import postInit.utils.RecyclingHelper

log.infoMC("Running SpaceSuit.groovy...")

mods.gregtech.spinning.removeByInput(30, [metaitem('fiberSodiumSilicate') * 4], [fluid('air') * 100])

VACUUM_CHAMBER.recipeBuilder() //REPLACE WITH EVAPORATION DEPOSITION
        .inputs(metaitem('mylar'))
        .inputs(ore('dustSmallHighPurityAluminium'))
        .outputs(metaitem('sheet.aluminized_mylar'))
        .duration(100)
        .EUt(VA[HV])
        .buildAndRegister()

VACUUM_CHAMBER.recipeBuilder() //REPLACE WITH EVAPORATION DEPOSITION
        .inputs(metaitem('foilKaptonK'))
        .inputs(ore('dustSmallHighPurityAluminium'))
        .outputs(metaitem('sheet.aluminized_kapton'))
        .duration(100)
        .EUt(VA[HV])
        .buildAndRegister()

VACUUM_CHAMBER.recipeBuilder() //REPLACE WITH EVAPORATION DEPOSITION
        .inputs(metaitem('foilPolysulfone'))
        .inputs(ore('dustSmallHighPurityGold'))
        .outputs(metaitem('sheet.gold_coated_polysulfone'))
        .duration(150)
        .EUt(VA[HV])
        .buildAndRegister()

VULCANIZER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam'))
        .fluidInputs(fluid('neoprene_solution') * 250)
        .notConsumable(metaitem('dustZincOxide'))
        .outputs(metaitem('sheet.neoprene_coated_nylon'))
        .fluidOutputs(fluid('wastewater') * 250)
        .duration(100)
        .EUt(VA[MV])
        .buildAndRegister()

VULCANIZER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam'))
        .fluidInputs(fluid('neoprene_solution') * 250)
        .notConsumable(metaitem('dustMagnesia'))
        .outputs(metaitem('sheet.neoprene_coated_nylon'))
        .fluidOutputs(fluid('wastewater') * 250)
        .duration(100)
        .EUt(VA[MV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('threadSiliconDioxide') * 8)
        .outputs(metaitem('sheet.beta_cloth'))
        .duration(80)
        .EUt(VA[MV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('wireFineNichrome') * 8)
        .outputs(metaitem('sheet.nichrome_fabric'))
        .duration(120)
        .EUt(VA[MV])
        .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
        .inputs(metaitem('sheet.beta_cloth'))
        .fluidInputs(fluid('polytetrafluoroethylene') * 36)
        .outputs(metaitem('sheet.teflon_coated_beta_cloth'))
        .duration(120)
        .EUt(VA[MV])
        .buildAndRegister()


CHEMICAL_BATH.recipeBuilder()
        .notConsumable(metaitem('spinneret'))
        .fluidInputs(fluid('sodium_silicate_solution') * 1000)
        .fluidInputs(fluid('water') * 100)
        .fluidInputs(fluid('hot_air') * 1000)
        .outputs(metaitem('fiberSodiumSilicate') * 8)
        .fluidOutputs(fluid('wastewater') * 1000)
        .duration(240)
        .EUt(VA[HV])
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(metaitem('fiberSodiumSilicate') * 8)
        .fluidInputs(fluid('diluted_hydrochloric_acid') * 1000)
        .outputs(metaitem('fiberWetSiliconDioxide') * 8)
        .fluidOutputs(fluid('wastewater') * 1000)
        .duration(300)
        .EUt(VA[LV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('ringAluminium'))
        .inputs(metaitem('platePolycarbonate') * 4)
        .outputs(metaitem('space_suit.pressure.helmet'))
        .duration(800)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam') * 5)
        .inputs(metaitem('sheet.neoprene_coated_nylon') * 5)
        .inputs(metaitem('plateNomex') * 5)
        .outputs(metaitem('space_suit.pressure.chest'))
        .circuitMeta(1)
        .duration(1200)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam'))
        .inputs(metaitem('sheet.neoprene_coated_nylon'))
        .inputs(metaitem('plateNomex'))
        .outputs(metaitem('space_suit.pressure.gloves'))
        .circuitMeta(2)
        .duration(300)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam') * 4)
        .inputs(metaitem('sheet.neoprene_coated_nylon') * 4)
        .inputs(metaitem('plateNomex') * 4)
        .outputs(metaitem('space_suit.pressure.leggings'))
        .circuitMeta(3)
        .duration(1000)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam') * 2)
        .inputs(metaitem('sheet.neoprene_coated_nylon') * 2)
        .inputs(metaitem('plateNomex') * 2)
        .outputs(metaitem('space_suit.pressure.boots'))
        .circuitMeta(4)
        .duration(600)
        .EUt(VA[EV])
        .buildAndRegister()


ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam') * 5)
        .inputs(ore('pipeTinyFluidEthyleneVinylAcetate') * 25)
        .inputs(metaitem('plateSpandex') * 5)
        .inputs(metaitem('ringTitanium') * 8)
        .outputs(metaitem('space_suit.cooling.chest'))
        .circuitMeta(1)
        .duration(1000)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam') * 4)
        .inputs(ore('pipeTinyFluidEthyleneVinylAcetate') * 20)
        .inputs(metaitem('plateSpandex') * 4)
        .outputs(metaitem('space_suit.cooling.leggings'))
        .circuitMeta(2)
        .duration(750)
        .EUt(VA[EV])
        .buildAndRegister()


ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 12)
        .inputs(metaitem('sheet.aluminized_mylar') * 12)
        .inputs(metaitem('platePolycarbonate') * 4)
        .inputs(metaitem('sheet.gold_coated_polysulfone') * 2)
        .inputs(metaitem('sheet.teflon_coated_beta_cloth') * 3)
        .inputs(metaitem('foilPolytetrafluoroethylene') * 3)
        .inputs(metaitem('ringStainlessSteel'))
        .inputs(metaitem('boltStainlessSteel') * 4)
        .outputs(metaitem('space_suit.thermal.helmet'))
        .duration(1800)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('sheet.neoprene_coated_nylon') * 5)
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 25)
        .inputs(metaitem('sheet.aluminized_mylar') * 25)
        .inputs(metaitem('sheet.beta_cloth') * 15)
        .inputs(metaitem('sheet.aluminized_kapton') * 10)
        .inputs(metaitem('sheet.teflon_coated_beta_cloth') * 5)
        .inputs(metaitem('foilPolytetrafluoroethylene') * 5)
        .inputs(metaitem('ringTitanium') * 8)
        .outputs(metaitem('space_suit.thermal.chest'))
        .circuitMeta(1)
        .duration(3000)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('sheet.neoprene_coated_nylon'))
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 5)
        .inputs(metaitem('sheet.aluminized_mylar') * 5)
        .inputs(metaitem('sheet.nichrome_fabric'))
        .inputs(metaitem('foilSiliconeRubber'))
        .inputs(metaitem('sheet.teflon_coated_beta_cloth'))
        .inputs(metaitem('foilPolytetrafluoroethylene'))
        .inputs(metaitem('ringTitanium') * 2)
        .outputs(metaitem('space_suit.thermal.gloves'))
        .circuitMeta(2)
        .duration(800)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('sheet.neoprene_coated_nylon') * 4)
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 20)
        .inputs(metaitem('sheet.aluminized_mylar') * 20)
        .inputs(metaitem('sheet.beta_cloth') * 12)
        .inputs(metaitem('sheet.aluminized_kapton') * 8)
        .inputs(metaitem('sheet.teflon_coated_beta_cloth') * 4)
        .inputs(metaitem('foilPolytetrafluoroethylene') * 4)
        .outputs(metaitem('space_suit.thermal.leggings'))
        .circuitMeta(3)
        .duration(2400)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('sheet.neoprene_coated_nylon') * 2)
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 10)
        .inputs(metaitem('sheet.aluminized_mylar') * 10)
        .inputs(metaitem('sheet.beta_cloth') * 6)
        .inputs(metaitem('sheet.aluminized_kapton') * 4)
        .inputs(metaitem('sheet.teflon_coated_beta_cloth') * 2)
        .inputs(metaitem('foilPolytetrafluoroethylene') * 2)
        .inputs(metaitem('honeycomb.aluminium') * 2)
        .outputs(metaitem('space_suit.thermal.boots'))
        .circuitMeta(4)
        .duration(1500)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('foilPolycaprolactam') * 2)
        .inputs(metaitem('dustSodiumPolyacrylate') * 2)
        .outputs(metaitem('space_suit.mag'))
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('battery.re.hv.lithium') * 2)
        .inputs(metaitem('large_fluid_cell.titanium') * 4)
        .inputs(metaitem('electric.pump.ev') * 4)
        .inputs(ore('pipeTinyFluidEthyleneVinylAcetate') * 20)
        .inputs(ore('circuitHv') * 2)
        .inputs(metaitem('dustActivatedCarbon') * 2)
        .inputs(metaitem('hepa_filter'))
        .inputs(metaitem('plateKaptonK') * 6)
        .inputs(metaitem('cableGtSingleAluminium') * 8)
        .outputs(metaitem('space_suit.plss'))
        .duration(2500)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('space_suit.pressure.helmet'))
        .inputs(metaitem('space_suit.thermal.helmet'))
        .outputs(metaitem('susy:astronaut_helmet'))
        .duration(600)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('space_suit.pressure.chest'))
        .inputs(metaitem('space_suit.cooling.chest'))
        .inputs(metaitem('space_suit.thermal.chest'))
        .inputs(metaitem('space_suit.pressure.gloves'))
        .inputs(metaitem('space_suit.thermal.gloves'))
        .inputs(metaitem('space_suit.plss'))
        .outputs(metaitem('susy:astronaut_chestplate'))
        .duration(1000)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('space_suit.pressure.leggings'))
        .inputs(metaitem('space_suit.cooling.leggings'))
        .inputs(metaitem('space_suit.thermal.leggings'))
        .inputs(metaitem('space_suit.mag'))
        .outputs(metaitem('susy:astronaut_leggings'))
        .duration(800)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('space_suit.pressure.boots'))
        .inputs(metaitem('space_suit.thermal.boots'))
        .outputs(metaitem('susy:astronaut_boots'))
        .duration(400)
        .EUt(VA[EV])
        .buildAndRegister()
