import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*
import net.minecraft.item.ItemStack;
import supersymmetry.common.rocketry.SusyRocketComponents;

ASSEMBLER.recipeBuilder()
        .circuitMeta(2)
        .inputs(metaitem('foilPolycaprolactam') * 64)
        .inputs(metaitem('threadKevlar') * 32)
        .outputs(metaitem('parachute.drogue'))
        .duration(200)
        .EUt(VA[HV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .circuitMeta(3)
        .inputs(metaitem('foilPolycaprolactam') * 64)
        .inputs(metaitem('foilPolycaprolactam') * 64)
        .inputs(metaitem('foilPolycaprolactam') * 64)
        .inputs(metaitem('foilPolycaprolactam') * 64)
        .inputs(metaitem('foilPolycaprolactam') * 64)
        .inputs(metaitem('threadKevlar') * 64)
        .inputs(metaitem('threadKevlar') * 32)
        .outputs(metaitem('parachute.main'))
        .duration(600)
        .EUt(VA[HV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .circuitMeta(4)
        .inputs(metaitem('foilPolycaprolactam') * 64)
        .inputs(metaitem('foilPolycaprolactam') * 64)
        .inputs(metaitem('foilPolycaprolactam') * 64)
        .inputs(metaitem('foilPolycaprolactam') * 64)
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 64)
        .inputs(metaitem('foilPolyethyleneTerephthalate') * 64)
        .inputs(metaitem('threadKevlar') * 64)
        .inputs(metaitem('threadKevlar') * 32)
        .outputs(metaitem('parachute.supersonic_main'))
        .duration(600)
        .EUt(VA[HV])
        .buildAndRegister();

CSTR.recipeBuilder()
        .circuitMeta(1)
        .fluidInputs(fluid('formaldehyde') * 75)
        .fluidInputs(fluid('phenol') * 25)
        .notConsumable(fluid('sodium_hydroxide_solution') * 50)
        .fluidOutputs(fluid('resol_resin_mixture') * 100)
        .duration(4)
        .EUt(VA[MV])
        .buildAndRegister();

CSTR.recipeBuilder()
        .fluidInputs(fluid('isopropyl_alcohol') * 75)
        .fluidInputs(fluid('resol_resin_mixture') * 25)
        .fluidOutputs(fluid('resol_resin_infiltrant') * 100)
        .duration(2)
        .EUt(VA[MV])
        .buildAndRegister();

CHEMICAL_BATH.recipeBuilder()
        .inputs(metaitem('carbon.mesh'))
        .fluidInputs(fluid('resol_resin_infiltrant') * 4000)
        .outputs(metaitem('carbon.mesh.phenolic.moist'))
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister();

TUBE_FURNACE.recipeBuilder()
        .inputs(metaitem('carbon.mesh.phenolic.moist'))
        .fluidInputs(fluid('argon') * 500)
        .outputs(metaitem('carbon.mesh.phenolic.treated'))
        .duration(300)
        .EUt(VA[HV])
        .buildAndRegister();

CUTTER.recipeBuilder()
        .inputs(metaitem('carbon.mesh.phenolic.treated'))
        .outputs(metaitem('carbon.tile.phenolic.treated') * 8)
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister();

/*ASSEMBLER.recipeBuilder()
        .inputs(metaitem('carbon.tile.phenolic.treated') * 64)
        .inputs(metaitem('carbon.tile.phenolic.treated') * 64)
        .inputs(metaitem('carbon.tile.phenolic.treated') * 64)
        .inputs(metaitem('carbon.tile.phenolic.treated') * 64)
        .inputs(metaitem('plateAluminium') * 32)
        .fluidInputs(fluid('polydimethylsiloxane') * 8000)
        .outputs(metaitem('heat_shield.pica'))
        .duration(600)
        .EUt(VA[EV])
        .buildAndRegister();*/

MIXER.recipeBuilder()
        .inputs(metaitem('cac_dust') * 2)
        .fluidInputs(fluid('water') * 500)
        .fluidOutputs(fluid('calcium_aluminate_concrete') * 144)
        .duration(30)
        .EUt(VA[MV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('stickSteel') * 4)
        .fluidInputs(fluid('calcium_aluminate_concrete') * 144)
        .outputs(item('susy:rocket_assembler_casing', 1))
        .duration(100)
        .EUt(VA[LV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(item('susy:rocket_assembler_casing', 1))
        .inputs(metaitem('boltStainlessSteel') * 4)
        .inputs(metaitem('ingotTabularAluminaRefractory') * 4)
        .fluidInputs(fluid('epoxy') * 144)
        .outputs(item('susy:rocket_assembler_casing'))
        .duration(35)
        .EUt(VA[MV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('stickLongSteel') * 24)
        .inputs(metaitem('plateStainlessSteel') * 6)
        .outputs(item('susy:rocket_assembler_casing', 3))
        .circuitMeta(1)
        .duration(15)
        .EUt(VA[MV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('stickLongSteel') * 30)
        .inputs(metaitem('plateSteel') * 20)
        .inputs(metaitem('plateStainlessSteel') * 8)
        .outputs(item('susy:rocket_assembler_casing', 2))
        .circuitMeta(1)
        .duration(40)
        .EUt(VA[HV])
        .buildAndRegister();

EVAPORATION_DEPOSITION.recipeBuilder()
        .inputs(metaitem('fused_quartz'))
        .inputs(metaitem('dustSmallCaesium'))
        .inputs(metaitem('dustSmallRubidium'))
        .inputs(metaitem('dustSmallAntimony'))
        .outputs(metaitem('bialkali_photocathode'))
        .duration(300)
        .EUt(VA[HV])
        .buildAndRegister();

SPUTTERING.recipeBuilder()
        .inputs(metaitem('plateStainlessSteel') * 4)
        .inputs(metaitem('plateBerylliumOxide'))
        .fluidInputs(fluid('argon') * 1000)
        .outputs(metaitem('beo_coated_stainless_steel_plate') * 4)
        .duration(180)
        .EUt(VA[HV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('bialkali_photocathode'))
        .inputs(metaitem('beo_coated_stainless_steel_plate') * 4)
        .inputs(metaitem('plateAnnealedCopper'))
        .inputs(metaitem('cableGtSingleAluminium') * 4)
        .outputs(metaitem('photomultiplier_components'))
        .duration(120)
        .EUt(VA[EV])
        .buildAndRegister();

VACUUM_CHAMBER.recipeBuilder()
        .inputs(metaitem('photomultiplier_components'))
        .inputs(metaitem('ringKovar'))
        .inputs(metaitem('component.glass.tube'))
        .outputs(metaitem('photomultiplier_tube'))
        .duration(80)
        .EUt(VA[HV])
        .buildAndRegister();

TUBE_FURNACE.recipeBuilder()
        .inputs(metaitem('dustManganeseDioxide') * 15)
        .inputs(metaitem('dustManganeseIiOxide') * 5)
        .inputs(metaitem('dustCobaltOxide') * 12)
        .inputs(metaitem('dustNickelIiOxide') * 4)
        .notConsumable(metaitem('shape.mold.plate'))
        .outputs(metaitem('plateManganeseCobaltNickelOxide') * 8)
        .duration(180)
        .EUt(VA[HV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('ringTitanium') * 10)
        .inputs(metaitem('roundStainlessSteel') * 24)
        .inputs(metaitem('electric.motor.ev'))
        .inputs(metaitem('plateTitanium') * 2)
        .fluidInputs(fluid('polydimethylsiloxane') * 100)
        .outputs(metaitem('spacecraft_sensor.gyroscope'))
        .duration(180)
        .EUt(VA[HV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('plateMolybdenum'))
        .inputs(metaitem('wireFineTungsten') * 16)
        .inputs(metaitem('plateAluminium') * 2)
        .inputs(metaitem('cableGtSingleAnnealedCopper') * 2)
        .outputs(metaitem('spacecraft_sensor.ion_flow'))
        .duration(280)
        .EUt(VA[HV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('photomultiplier_tube') * 2)
        .inputs(metaitem('fused_quartz') * 3)
        .inputs(metaitem('plateAluminium') * 4)
        .inputs(metaitem('cableGtSingleCopper') * 2)
        //FIXME: add photodiode
        .outputs(metaitem('spacecraft_sensor.sun_star'))
        .duration(400)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('plateGermanium'))
        .inputs(metaitem('plateManganeseCobaltNickelOxide') * 2)
        .inputs(metaitem('plateTitanium') * 3)
        .inputs(metaitem('electric.motor.ev'))
        .inputs(metaitem('cableGtSingleSilver') * 2)
        .outputs(metaitem('spacecraft_sensor.infrared'))
        .duration(360)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.ev'))
        .inputs(metaitem('spacecraft_sensor.gyroscope') * 6)
        .inputs(metaitem('spacecraft_sensor.ion_flow') * 3)
        .inputs(metaitem('spacecraft_sensor.sun_star'))
        .inputs(metaitem('spacecraft_sensor.infrared'))
        .inputs(metaitem('wireless') * 3)//FIXME (maybe): replace with actual antenna
        .inputs(metaitem('circuit.nano_computer')) //specifically excludes mainframes because they're too heavy
        .inputs(metaitem('cableGtDoubleSilver') * 6)
        .outputs(item('susy:guidance_system'))
        .duration(800)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.ev'))
        .inputs(metaitem('spacecraft_sensor.gyroscope') * 6)
        .inputs(metaitem('spacecraft_sensor.ion_flow') * 3)
        .inputs(metaitem('spacecraft_sensor.sun_star'))
        .inputs(metaitem('spacecraft_sensor.infrared'))
        .inputs(metaitem('wireless') * 3)//FIXME (maybe): replace with actual antenna
        .inputs(metaitem('circuit.quantum_assembly'))
        .inputs(metaitem('cableGtDoubleSilver') * 6)
        .outputs(item('susy:guidance_system'))
        .duration(800)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.ev'))
        .inputs(metaitem('spacecraft_sensor.gyroscope') * 6)
        .inputs(metaitem('spacecraft_sensor.ion_flow') * 3)
        .inputs(metaitem('spacecraft_sensor.sun_star'))
        .inputs(metaitem('spacecraft_sensor.infrared'))
        .inputs(metaitem('wireless') * 3)//FIXME (maybe): replace with actual antenna
        .inputs(metaitem('circuit.crystal_processor'))
        .inputs(metaitem('cableGtDoubleSilver') * 6)
        .outputs(item('susy:guidance_system'))
        .duration(800)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.ev'))
        .inputs(metaitem('spacecraft_sensor.gyroscope') * 6)
        .inputs(metaitem('spacecraft_sensor.ion_flow') * 3)
        .inputs(metaitem('spacecraft_sensor.sun_star'))
        .inputs(metaitem('spacecraft_sensor.infrared'))
        .inputs(metaitem('wireless') * 3)//FIXME (maybe): replace with actual antenna
        .inputs(metaitem('circuit.suprachronal.iv'))
        .inputs(metaitem('cableGtDoubleSilver') * 6)
        .outputs(item('susy:guidance_system'))
        .duration(800)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.ev'))
        .inputs(metaitem('sensor.iv') * 8)
        .inputs(metaitem('emitter.iv') * 4)
        .inputs(ore('circuitIv') * 8)
        .inputs(metaitem('electric.motor.ev') * 4)
        .outputs(metaitem('susy:component_scanner'))
        .duration(350)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.iv'))
        .inputs(metaitem('robot.arm.ev') * 48)
        .inputs(metaitem('emitter.iv') * 8)
        .inputs(metaitem('sensor.iv') * 8)
        .inputs(metaitem('electric.motor.ev') * 16)
        .inputs(metaitem('electric.piston.ev') * 16)
        .inputs(ore('circuitIv') * 32)
        .outputs(metaitem('susy:rocket_assembler'))
        .duration(500)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('frameStainlessSteel'))
        .inputs(metaitem('rotorAluminium') * 2)
        .inputs(metaitem('electric.motor.mv') * 2)
        .inputs(ore('pipeSmallItemPolyvinylChloride') * 8)
        .inputs(ore('circuitEv') * 8)
        .outputs(item('susy:processor_cluster'))
        .duration(100)
        .EUt(VA[HV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.hv'))
        .inputs(metaitem('emitter.hv') * 4)
        .inputs(metaitem('cover.screen'))
        .inputs(ore('circuitIv') * 16)
        .outputs(metaitem('susy:rocket_programmer'))
        .duration(250)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.iv'))
        .inputs(metaitem('sensor.ev') * 8)
        .inputs(metaitem('cover.screen'))
        .inputs(ore('circuitIv') * 24)
        .outputs(metaitem('susy:aerospace_flight_simulator'))
        .duration(320)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.iv'))
        .inputs(metaitem('sensor.iv') * 8)
        .inputs(metaitem('electric.motor.ev') * 64)
        .inputs(metaitem('electric.motor.ev') * 64)
        .inputs(metaitem('electric.piston.ev') * 48)
        .inputs(metaitem('electric.pump.ev') * 32)
        .inputs(metaitem('cableGtQuadrupleAluminium') * 64)
        .inputs(ore('pipeHugeFluidTungstenSteel') * 32)
        .inputs(ore('circuitEv') * 16)
        .outputs(metaitem('susy:launch_pad'))
        .duration(640)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.iv'))
        .inputs(metaitem('sensor.iv') * 8)
        .inputs(metaitem('emitter.iv') * 8)
        .inputs(ore('circuitIv') * 40)
        .outputs(metaitem('susy:blueprint_assembler'))
        .duration(400)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.iv'))
        .inputs(metaitem('sensor.ev') * 24)
        .inputs(metaitem('robot.arm.ev') * 20)
        .inputs(ore('circuitEv') * 32)
        .outputs(metaitem('susy:scrap_recycler'))
        .duration(320)
        .EUt(VA[EV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('fuel_injector'))
        .inputs(metaitem('plateGrcop84') * 16)
        .inputs(metaitem('pipeLargeFluidStainlessSteel') * 6)
        .outputs(item('susy:rocket_combustion_chamber'))
        .duration(120)
        .EUt(VA[HV])
        .buildAndRegister();

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('plateMolybdenum') * 2)
        .inputs(metaitem('foilTantalum') * 2)
        .inputs(metaitem('wireGtSingleTungsten'))
        .inputs(metaitem('ringMolybdenum'))
        .inputs(metaitem('sintered_alumina.insulator'))
        .inputs(metaitem('component.glass.tube'))
        .outputs(metaitem('electron_gun'))
        .duration(200)
        .EUt(VA[EV])
        .buildAndRegister();

EVAPORATION_DEPOSITION.recipeBuilder()
        .circuitMeta(1)
        .notConsumable(metaitem('electron_gun'))
        .inputs(metaitem('dustTitaniumDioxide'))
        .inputs(metaitem('dustSiliconDioxide'))
        .outputs(metaitem('spectral_filter.near_ir_bandpass'))
        .duration(1200)
        .EUt(VA[EV])
        .buildAndRegister();

EVAPORATION_DEPOSITION.recipeBuilder()
        .circuitMeta(2)
        .notConsumable(metaitem('electron_gun'))
        .inputs(metaitem('dustTitaniumDioxide'))
        .inputs(metaitem('dustSiliconDioxide'))
        .outputs(metaitem('spectral_filter.mid_ir_bandpass'))
        .duration(1200)
        .EUt(VA[EV])
        .buildAndRegister();

EVAPORATION_DEPOSITION.recipeBuilder()
        .circuitMeta(3)
        .notConsumable(metaitem('electron_gun'))
        .inputs(metaitem('dustTitaniumDioxide'))
        .inputs(metaitem('dustSiliconDioxide'))
        .outputs(metaitem('spectral_filter.visible_bandpass'))
        .duration(1200)
        .EUt(VA[EV])
        .buildAndRegister();

EVAPORATION_DEPOSITION.recipeBuilder()
        .circuitMeta(4)
        .notConsumable(metaitem('electron_gun'))
        .inputs(metaitem('dustTitaniumDioxide'))
        .inputs(metaitem('dustSiliconDioxide'))
        .outputs(metaitem('spectral_filter.near_uv_bandpass'))
        .duration(1200)
        .EUt(VA[EV])
        .buildAndRegister();

EVAPORATION_DEPOSITION.recipeBuilder()
        .notConsumable(metaitem('springRtmAlloy'))
        .inputs(metaitem('dustSilver'))
        .inputs(metaitem('mylar'))
        .outputs(metaitem('foilMetallizedBopet'))
        .duration(100)
        .EUt(VA[EV])
        .buildAndRegister();

EVAPORATION_DEPOSITION.recipeBuilder()
        .inputs(ore('stickLongAluminium'))
        .inputs(ore('plateAluminium') * 4)
        .inputs(ore('dustAluminium'))
        .inputs(metaitem('electric.motor.ev'))
        .outputs(item('susy:heliostat'))
        .duration(64)
        .EUt(60)
        .buildAndRegister()

EVAPORATION_DEPOSITION.recipeBuilder()
        .inputs(ore('plateReinforcedEpoxyResin') * 2)
        .inputs(ore('dustAluminium'))
        .circuitMeta(1)
        .outputs(item('susy:epoxy_solar_furnace_mirror'))
        .duration(80)
        .EUt(VA[HV])
        .buildAndRegister()

EVAPORATION_DEPOSITION.recipeBuilder()
        .inputs(ore('plateSteel') * 2)
        .inputs(ore('dustAluminium'))
        .circuitMeta(1)
        .outputs(item('susy:steel_solar_furnace_mirror'))
        .duration(32)
        .EUt(48)
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('hull.ev'))
        .inputs(metaitem('electric.pump.ev') * 4)
        .inputs(metaitem('conveyor.module.ev') * 4)
        .inputs(ore('circuitEv'))
        .circuitMeta(5)
        .outputs(metaitem('susy:solar_furnace'))
        .duration(200)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('crucible.quartz'))
        .inputs(metaitem('electric.pump.ev'))
        .inputs(metaitem('conveyor.module.ev'))
        .inputs(metaitem('fused_quartz'))
        .inputs(metaitem('plateAluminium'))
        .circuitMeta(5)
        .outputs(item('susy:solar_furnace_crucible'))
        .duration(200)
        .EUt(VA[EV])
        .buildAndRegister()

EVAPORATION_DEPOSITION.recipeBuilder()
    .inputs(ore('plateAluminium') * 2)
    .inputs(ore('stickAluminium') * 4)
    .inputs(ore('dustAluminium'))
    .circuitMeta(1)
    .outputs(item('susy:solar_furnace_redirecting_mirror'))
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

ASSEMBLER.recipeBuilder()
    .inputs(metaitem('hull.ev'))
    .inputs(metaitem('robot.arm.ev') * 64)
    .inputs(metaitem('robot.arm.ev') * 64)
    .inputs(metaitem('conveyor.module.ev') * 32)
    .inputs(ore('circuitEv') * 16)
    .circuitMeta(5)
    .outputs(item('gregtech:machine', 18520))
    .duration(480)
    .EUt(VA[EV])
    .buildAndRegister()

CIRCUIT_ASSEMBLER.recipeBuilder()
    .inputs(metaitem('platePolyvinylChloride') * 2) //FIXME: make this realistic once circuit update is here
    .inputs(metaitem('circuit_board.plastic'))
    .inputs(ore('circuitEv'))
    .inputs(metaitem('plate.nand_memory_chip') * 24)
    .inputs(metaitem('plate.random_access_memory') * 2)
    .inputs(metaitem('wireFineSilver') * 32)
    .fluidInputs(fluid('tin') * 288)
    .outputs(metaitem('susy:data_card'))
    .duration(40)
    .EUt(VA[EV])
    .buildAndRegister()

CIRCUIT_ASSEMBLER.recipeBuilder()
    .inputs(metaitem('platePolyvinylChloride') * 2)
    .inputs(metaitem('circuit_board.plastic'))
    .inputs(ore('circuitEv'))
    .inputs(metaitem('plate.nand_memory_chip') * 24)
    .inputs(metaitem('plate.random_access_memory') * 2)
    .inputs(metaitem('wireFineSilver') * 32)
    .fluidInputs(fluid('soldering_alloy') * 144)
    .outputs(metaitem('susy:data_card'))
    .duration(30)
    .EUt(VA[EV])
    .buildAndRegister()

ItemStack stack = metaitem('susy:data_card.master_blueprint') * 1
stack.setTagCompound(SusyRocketComponents.ROCKET_SOYUZ_BLUEPRINT_DEFAULT.writeToNBT())

SCANNER.recipeBuilder()
        .inputs(metaitem('susy:data_card'))
        .circuitMeta(1)
        .outputs(stack)
        .EUt(VA[EV])
        .duration(10000)
        .buildAndRegister()

ItemStack stack = metaitem('susy:data_card.master_blueprint') * 1
stack.setTagCompound(SusyRocketComponents.ROCKET_LUNAR_BLUEPRINT_DEFAULT.writeToNBT())

SCANNER.recipeBuilder()
        .inputs(metaitem('susy:data_card'))
        .circuitMeta(1)
        .outputs(stack)
        .EUt(VA[EV])
        .duration(10000)
        .buildAndRegister()


mods.susy.rocketCosts.add('soyuz', 'soyuz_plumbing')
        .input(ore('pipeLargeStainlessSteel'), 20) // hydrogen embrittlement moment
        .input(ore('screwStainlessSteel'), 20)
        .duration(400)
        .register()

mods.susy.rocketCosts.add('soyuz', 'soyuz_wiring')
        .input(ore('circuitEv'), 32)
        .input(ore('cableGtQuadrupleAluminium'), 40)
        .duration(400)
        .register()

// 12, modeled after the Fregat
mods.susy.rocketCosts.add('soyuz', 'soyuz_verniers')
        .input(metaitem('large_fluid_cell.steel').withNbt(['Fluid': ['FluidName': 'dinitrogen_tetroxide', 'Amount': 8000]]) * 12)
        .input(metaitem('large_fluid_cell.steel').withNbt(['Fluid': ['FluidName': 'dimethylhydrazine', 'Amount': 8000]]) * 12)
        .input(item('susy:rocket_engine_gas_generator') * 4) // One for each stage (being nice here) 
        .input(item('susy:rocket_turbopump') * 12)
        .input(item('susy:rocket_nozzle') * 48)
        .duration(400)
        .register()

mods.susy.rocketCosts.add('lunar', 'lunar_plumbing')
        .input(ore('pipeLargeStainlessSteel'), 10)
        .input(ore('screwStainlessSteel'), 10)
        .duration(200)
        .register()

mods.susy.rocketCosts.add('lunar', 'lunar_wiring')
        .input(ore('cableGtQuadrupleAluminium'), 20)
        .duration(200)
        .register()

mods.susy.rocketCosts.add('lunar', 'lunar_verniers')
        .input(metaitem('large_fluid_cell.steel').withNbt(['Fluid': ['FluidName': 'dinitrogen_tetroxide', 'Amount': 8000]]) * 3)
        .input(metaitem('large_fluid_cell.steel').withNbt(['Fluid': ['FluidName': 'dimethylhydrazine', 'Amount': 8000]]) * 3)
        .input(item('susy:rocket_engine_gas_generator')) // One for each stage (being nice here) 
        .input(item('susy:rocket_turbopump') * 3)
        .input(item('susy:rocket_nozzle') * 12)
        .duration(200)
        .register()
