import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*
import gregtech.api.recipes.recipeproperties.RecipeProperty
import gregtech.api.recipes.RecipeBuilder
import static gregtech.api.recipes.RecipeMaps.*
import gregtech.api.unification.material.Materials.*

import gregtech.api.recipes.ModHandler
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.api.unification.stack.UnificationEntry

import postInit.utils.RecyclingHelper

log.infoMC("Running Turbines.groovy...")





MIXER.recipeBuilder()
        .inputs(ore('dustSiliconDioxide') * 9)
        .inputs(ore('dustZircon') * 12)
        .inputs(ore('dustSiliconCarbide') * 4)
        .outputs(metaitem('dustRawInvestmentCastingMixture') * 25)
        .duration(600)
        .EUt(VA[MV])
        .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
        .inputs(metaitem('dustRawInvestmentCastingMixture') * 25)
        .fluidInputs(fluid('colloidal_silica') * 1000)
        .outputs(metaitem('dustSilicaCoatedInvestmentCastingMixture') * 25)
        .duration(280)
        .EUt(VA[HV])
        .buildAndRegister()

DRYER.recipeBuilder()
        .inputs(metaitem('dustSilicaCoatedInvestmentCastingMixture') * 25)
        .outputs(metaitem('dustDriedSilicaCoatedInvestmentCastingMixture') * 25)
        .duration(240)
        .EUt(VA[MV])
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(metaitem('paraffin_wax') * 6)
        .fluidInputs(fluid('stearic_acid') * 1000)
        .outputs(metaitem('investment_casting_binder') * 7)
        .duration(320)
        .EUt(VA[MV])
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(metaitem('dustDriedSilicaCoatedInvestmentCastingMixture') * 25)
        .inputs(metaitem('investment_casting_binder') * 7)
        .outputs(metaitem('dustInvestmentCastingMixture') * 32)
        .duration(640)
        .EUt(VA[LV])
        .buildAndRegister()

INJECTION_MOLDER.recipeBuilder()
        .inputs(metaitem('dustInvestmentCastingMixture') * 1)
        .notConsumable(metaitem('turbine_blade_core_die'))
        .outputs(metaitem('turbine_blade_casting_core') * 1)
        .duration(20)
        .EUt(VA[HV])
        .buildAndRegister()

ERF.recipeBuilder()
        .inputs(metaitem('turbine_blade_casting_core') * 1)
        .outputs(metaitem('fired_turbine_blade_casting_core') * 1)
        .duration(240)
        .EUt(VA[HV])
        .blastFurnaceTemp(1450)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(metaitem('paraffin_wax') * 17)
        .inputs(metaitem('dustHydrogenatedPetroleumResin') * 16)
        .inputs(metaitem('roundCrosslinkedPolystyrene') * 90)
        .outputs(metaitem('investment_casting_wax') * 43)
        .duration(430)
        .EUt(VA[HV])
        .buildAndRegister()

INJECTION_MOLDER.recipeBuilder()
        .inputs(metaitem('investment_casting_wax') * 1)
        .inputs(metaitem('fired_turbine_blade_casting_core') * 2)
        .notConsumable(metaitem('turbine_blade_shape_die') * 1)
        .outputs(metaitem('wax_turbine_blade_mold') * 2)
        .duration(100)
        .EUt(VA[HV])
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(metaitem('dustZircon') * 1)
        .fluidInputs(fluid('colloidal_silica') * 1000)
        .fluidOutputs(fluid('investment_casting_ceramic_slurry') * 1000)
        .duration(180)
        .EUt(VA[MV])
        .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
        .inputs(metaitem('wax_turbine_blade_mold') * 1)
        .fluidInputs(fluid('investment_casting_ceramic_slurry') * 200)
        .outputs(metaitem('ceramic_coated_wax_turbine_blade_mold') * 1)
        .duration(120)
        .EUt(VA[LV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()//not the best machine for this, chembath would be better but only has 1 input slot
        .inputs(metaitem('ceramic_coated_wax_turbine_blade_mold') * 1)
        .inputs(metaitem('dustZircon') * 1)
        .notConsumable(metaitem('dustZircon') * 16)
        .outputs(metaitem('stuccoed_ceramic_turbine_blade_mold') * 1)
        .duration(100)
        .EUt(VA[MV])
        .buildAndRegister()

DRYER.recipeBuilder()
        .inputs(metaitem('stuccoed_ceramic_turbine_blade_mold') * 1)
        .outputs(metaitem('dried_ceramic_turbine_blade_mold') * 1)
        .duration(140)
        .EUt(VA[MV])
        .buildAndRegister()

AUTOCLAVE.recipeBuilder()
        .inputs(metaitem('dried_ceramic_turbine_blade_mold') * 1)
        .fluidInputs(fluid('dense_steam') * 4000)
        .outputs(metaitem('dewaxed_ceramic_turbine_blade_mold') * 1)
        .duration(60)
        .EUt(VA[HV])
        .buildAndRegister()

ERF.recipeBuilder()
        .inputs(metaitem('dewaxed_ceramic_turbine_blade_mold') * 1)
        .outputs(metaitem('turbine_blade_mold') * 1)
        .duration(200)
        .blastFurnaceTemp(1550)
        .EUt(VA[HV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('plateGraphite') * 4)
        .inputs(metaitem('ingotTabularAluminaRefractory') * 5)
        .inputs(metaitem('plateCopper') * 2)
        .inputs(metaitem('cableGtQuadrupleAnnealedCopper') * 4)
        .inputs(metaitem('pipeTinyFluidCopper') * 6)
        .inputs(metaitem('electric.piston.mv') * 1)
        .outputs(metaitem('bridgman_furnace') * 1)
        .duration(400)
        .EUt(VA[HV])
        .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
        .inputs(metaitem('turbine_blade_mold') * 1)
        .notConsumable(metaitem('bridgman_furnace') * 1)
        .fluidInputs(fluid('molten.rene_n_5') * 144)
        .notConsumable(fluid('distilled_water') * 8000)
        .outputs(metaitem('cast_gas_turbine_blade') * 1)
        .duration(180)
        .EUt(VA[EV])
        .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
        .inputs(metaitem('turbine_blade_mold') * 1)
        .notConsumable(metaitem('bridgman_furnace') * 1)
        .fluidInputs(fluid('molten.nimonic_105') * 144)
        .notConsumable(fluid('distilled_water') * 8000)
        .outputs(metaitem('cast_high_pressure_steam_turbine_blade') * 1)
        .duration(180)
        .EUt(VA[EV])
        .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
        .inputs(metaitem('turbine_blade_mold') * 1)
        .notConsumable(metaitem('bridgman_furnace') * 1)
        .fluidInputs(fluid('molten.incoloy_825') * 144)
        .notConsumable(fluid('distilled_water') * 8000)
        .outputs(metaitem('cast_low_pressure_steam_turbine_blade') * 1)
        .duration(180)
        .EUt(VA[EV])
        .buildAndRegister()

['gas', 'high_pressure_steam', 'low_pressure_steam'].each { turbine_type ->

    FORGE_HAMMER.recipeBuilder()
            .inputs(metaitem('cast_' + turbine_type + '_turbine_blade') * 1)
            .outputs(metaitem('demolded_' + turbine_type + '_turbine_blade') * 1)
            .duration(10)
            .EUt(VA[MV])
            .buildAndRegister()

    BR.recipeBuilder()
            .inputs(metaitem('demolded_' + turbine_type + '_turbine_blade') * 1)
            .fluidInputs(fluid('sodium_hydroxide_solution') * 2000)
            .outputs(metaitem('decored_' + turbine_type + '_turbine_blade') * 1)
            .fluidOutputs(fluid('wastewater') * 2000)
            .duration(150)
            .EUt(VA[MV])
            .buildAndRegister()

    MILLING.recipeBuilder()
            .inputs(metaitem('decored_' + turbine_type + '_turbine_blade') * 1)
            .outputs(metaitem('milled_' + turbine_type + '_turbine_blade') * 1)
            .duration(90)
            .EUt(VA[EV])
            .buildAndRegister()

}

SINTERING_OVEN.recipeBuilder()
        .inputs(metaitem('dustLanthanumOxide') * 5)
        .inputs(metaitem('dustZirconiumDioxide') * 6)
        .fluidInputs(fluid('argon') * 250)
        .outputs(metaitem('ingotLanthanumZirconiumOxide') * 11)
        .duration(240)
        .EUt(VA[HV])
        .buildAndRegister()

ZONE_REFINER.recipeBuilder()
        .inputs(metaitem('ingotPlatinum') * 1)
        .outputs(metaitem('ingotHighPurityPlatinum') * 1)
        .duration(120)
        .EUt(VA[HV])
        .buildAndRegister()

SPUTTERING.recipeBuilder()
        .inputs(metaitem('surface_finished_gas_turbine_blade') * 1)
        .inputs(metaitem('nuggetHighPurityPlatinum') * 2)
        .fluidInputs(fluid('argon') * 250)
        .outputs(metaitem('platinum_coated_gas_turbine_blade') * 1)
        .duration(80)
        .EUt(VA[EV])
        .buildAndRegister()

VACUUM_CHAMBER.recipeBuilder()
        .inputs(metaitem('platinum_coated_gas_turbine_blade'))
        .inputs(metaitem('nuggetHighPurityAluminium') * 4)
        .notConsumable(metaitem('crucible.tantalum'))
        .notConsumable(metaitem('springTungsten'))
        .outputs(metaitem('platinum_aluminide_coated_gas_turbine_blade'))
        .duration(180)
        .EUt(VA[EV])
        .buildAndRegister()

SPUTTERING.recipeBuilder()
        .inputs(metaitem('platinum_aluminide_coated_gas_turbine_blade'))
        .inputs(metaitem('ingotLanthanumZirconiumOxide') * 1)
        .fluidInputs(fluid('argon') * 250)
        .outputs(metaitem('gas_turbine_blade') * 1)
        .duration(140)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('plateTungstenSteel') * 8)
        .inputs(metaitem('stickLongTungstenSteel') * 1)
        .inputs(metaitem('ringStainlessSteel') * 2)
        .inputs(metaitem('gas_turbine_blade') * 20)
        .outputs(item('susy:turbine_rotor', 12) * 1)
        .duration(600)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('plateUltimet') * 8)
        .inputs(metaitem('stickLongUltimet') * 1)
        .inputs(metaitem('ringStainlessSteel') * 2)
        .inputs(metaitem('high_pressure_steam_turbine_blade') * 20)
        .outputs(item('susy:turbine_rotor', 8) * 1)
        .duration(500)
        .EUt(VA[EV])
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('plateUltimet') * 8)
        .inputs(metaitem('stickLongUltimet') * 1)
        .inputs(metaitem('ringStainlessSteel') * 2)
        .inputs(metaitem('low_pressure_steam_turbine_blade') * 20)
        .outputs(item('susy:turbine_rotor', 4) * 1)
        .duration(500)
        .EUt(VA[EV])
        .buildAndRegister()

