import static prePostInit.Recipemaps.*
import globals.Sintering

import static gregtech.api.GTValues.*
import gregtech.api.GregTechAPI
import gregtech.api.unification.material.Material
import static gregtech.api.unification.material.Materials.*

REACTION_FURNACE.recipeBuilder()
    .inputs(ore('dustVanadinite') * 1)
    .inputs(ore('dustSalt') * 6)
    .outputs(metaitem('dustSaltRoastedVanadinite') * 27)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .inputs(ore('dustVanadinite') * 2)
    .inputs(ore('dustSodaAsh') * 18)
    .outputs(metaitem('dustSodaAshRoastedVanadinite') * 51)
    .fluidOutputs(fluid('carbon_dioxide') * 3000)
    .duration(300)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustSodaAshRoastedVanadinite') * 51)
    .fluidInputs(fluid('water') * 6000)
    .fluidOutputs(fluid('sodium_vanadate_solution') * 6000)
    .outputs(metaitem('dustLeachedSodaAshRoastedVanadinite') * 21)
    .duration(80)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustLeachedSodaAshRoastedVanadinite') * 21)
    .fluidInputs(fluid('gtfo_heated_water') * 1000)
    .fluidOutputs(fluid('lead_chloride_solution') * 1000)
    .outputs(metaitem('dustLeadIiOxide') * 18)
    .duration(80)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustSaltRoastedVanadinite') * 27)
    .fluidInputs(fluid('water') * 3000)
    .fluidOutputs(fluid('sodium_vanadate_solution') * 3000)
    .outputs(metaitem('dustLeachedSaltRoastedVanadinite') * 12)
    .duration(80)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustLeachedSaltRoastedVanadinite') * 12)
    .fluidInputs(fluid('gtfo_heated_water') * 2000)
    .fluidOutputs(fluid('lead_chloride_solution') * 2000)
    .outputs(metaitem('dustLeadIiOxide') * 6)
    .duration(80)
    .EUt(VA[MV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('lead_chloride_solution') * 1000)
    .fluidOutputs(fluid('water') * 1000)
    .outputs(metaitem('dustLeadChloride') * 3)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustAmmoniumChloride') * 6)
    .fluidInputs(fluid('sodium_vanadate_solution') * 1000)
    .outputs(metaitem('dustAmmoniumMetavanadate') * 9)
    .fluidOutputs(fluid('salt_water') * 1000)
    .duration(80)
    .EUt(VA[MV])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustAmmoniumMetavanadate') * 18)
    .outputs(metaitem('dustVanadiumPentoxide') * 7)
    .fluidOutputs(fluid('dense_steam') * 1000)
    .fluidOutputs(fluid('ammonia') * 2000)
    .duration(80)
    .circuitMeta(1)
    .EUt(VA[MV])
    .buildAndRegister()

ELECTROMAGNETIC_SEPARATOR.recipeBuilder()
    .inputs(ore('dustImpureVanadiferousTitanomagnetite'))
    .outputs(metaitem('dustVanadiferousTitanomagnetite'))
    .chancedOutput(metaitem('dustPegmatiteTailings'), 2500, 500)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('distilled_water') * 2000)
    .inputs(ore('dustVanadiferousTitanomagnetite') * 8)
    .fluidOutputs(fluid('impure_vanadiferous_titanomagnetite_slurry') * 2000)
    .EUt(VA[MV])
    .duration(200)
    .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
    .fluidInputs(fluid('impure_vanadiferous_titanomagnetite_slurry') * 2000)
    .notConsumable(fluid('methyl_isobutyl_carbinol') * 100)
    .notConsumable(fluid('n_octylamine') * 100)
    .fluidOutputs(fluid('vanadiferous_titanomagnetite_slurry') * 1000)
    .fluidOutputs(fluid('pegmatite_tailing_slurry') * 1000)
    .EUt(VA[HV])
    .duration(800)
    .buildAndRegister()

CLARIFIER.recipeBuilder()
    .fluidInputs(fluid('vanadiferous_titanomagnetite_slurry') * 1000)
    .fluidOutputs(fluid('wastewater') * 1000)
    .outputs(metaitem('dustFlotatedVanadiferousTitanomagnetite') * 16)
    .EUt(VA[LV])
    .duration(20)
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .inputs(ore('dustMagnesite'))
    .outputs(metaitem('dustMagnesiumCarbonate'))
    .EUt(VA[LV])
    .duration(160)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustMagnesiumChloride') * 3)
    .fluidInputs(fluid('sodium_bicarbonate_solution') * 2000)
    .outputs(metaitem('dustMagnesiumCarbonate') * 5)
    .fluidOutputs(fluid('salt_water') * 2000)
    .fluidOutputs(fluid('carbon_dioxide') * 1000)
    .EUt(VA[LV])
    .duration(160)
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustMagnesiumHydroxide') * 5)
    .fluidInputs(fluid('carbon_dioxide') * 1000)
    .outputs(metaitem('dustMagnesiumCarbonate') * 5)
    .fluidOutputs(fluid('dense_steam') * 1000)
    .EUt(VA[LV])
    .duration(160)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustCalcite') * 5)
    .inputs(ore('dustMagnesiumCarbonate') * 5)
    .outputs(metaitem('dustDolomite') * 10)
    .EUt(VA[MV])
    .duration(300)
    .buildAndRegister()

Sintering.nonPlasmaFuels().each { fuel ->
Sintering.comburents.each { comburent ->
    ROTARY_KILN.recipeBuilder()
        .inputs(ore('dustFlotatedVanadiferousTitanomagnetite') * 11)
        .inputs(ore('dustCoke') * 7)
        .inputs(ore('dustDolomite'))
        .fluidInputs(fluid(fuel.name) * fuel.amountRequired)
        .fluidInputs(fluid(comburent.name) * comburent.amountRequired)
        .outputs(metaitem('vti_rich_pig_iron') * 4)
        .fluidOutputs(fluid('carbon_monoxide') * 7000)
        .duration(fuel.duration + comburent.duration)
        .EUt(VA[MV])
        .buildAndRegister()

    ROTARY_KILN.recipeBuilder()
        .inputs(ore('dustFlotatedVanadiferousTitanomagnetite') * 11)
        .inputs(ore('dustAnyPurityCarbon') * 7)
        .inputs(ore('dustDolomite'))
        .fluidInputs(fluid(fuel.name) * fuel.amountRequired)
        .fluidInputs(fluid(comburent.name) * comburent.amountRequired)
        .outputs(metaitem('vti_rich_pig_iron') * 4)
        .fluidOutputs(fluid('carbon_monoxide') * 7000)
        .duration(fuel.duration + comburent.duration)
        .EUt(VA[MV])
        .buildAndRegister()

    ROTARY_KILN.recipeBuilder()
        .inputs(ore('dustVtSlag'))
        .inputs(ore('dustSodaAsh') * 5)
        .fluidInputs(fluid(fuel.name) * fuel.amountRequired)
        .fluidInputs(fluid(comburent.name) * comburent.amountRequired)
        .outputs(metaitem('dustAlkaliVtSlag'))
        .fluidOutputs(fluid('carbon_dioxide') * 1000)
        .duration(fuel.duration + comburent.duration)
        .EUt(VA[MV])
        .buildAndRegister()
}
}

ADVANCED_ARC_FURNACE.recipeBuilder()
    .inputs(metaitem('vti_rich_pig_iron') * 2)
    .fluidInputs(fluid('oxygen') * 2700)
    .outputs(metaitem('ingotSteel') * 2)
    .outputs(metaitem('vt_slag'))
    .EUt(240)
    .duration(300)
    .buildAndRegister()

MACERATOR.recipeBuilder()
    .inputs(metaitem('vt_slag'))
    .outputs(metaitem('dustVtSlag'))
    .EUt(VA[MV])
    .duration(200)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustAlkaliVtSlag') * 7)
    .fluidInputs(fluid('distilled_water') * 1000)
    .outputs(metaitem('dustTitaniaSlag') * 6)
    .fluidOutputs(fluid('sodium_vanadate_solution') * 1000)
    .EUt(VA[MV])
    .duration(200)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustTitaniaSlag'))
    .fluidInputs(fluid('oleum') * 1000)
    .outputs(metaitem('dustSiliconDioxide'))
    .fluidOutputs(fluid('titanyl_sulfate_solution') * 1000)
    .EUt(VA[MV])
    .duration(200)
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .inputs(ore('dustHighPurityCalcium') * 5)
    .inputs(ore('dustVanadiumPentoxide') * 7)
    .outputs(metaitem('dustVanadium') * 2)
    .outputs(metaitem('dustQuicklime') * 10)
    .EUt(VA[MV])
    .duration(100)
    .buildAndRegister()


// Vanadium compounds

    /* Vanadium trioxide: https://link.springer.com/article/10.1007/s11837-025-07551-4?error=cookies_not_supported&code=6b81ec58-e6be-4dd8-a108-381282b53313
    ROASTER.recipeBuilder()
        .circuitMeta(2)
        .inputs(ore('dustAmmoniumMetavanadate') * 90)
        .inputs(ore('dustCarbon') * 7)
        .fluidOutputs(fluid('ammonia_solution') * 8000)
        .fluidOutputs(fluid('carbon_monoxide') * 7000)
        .fluidOutputs(fluid('nitrogen') * 2000)
        .outputs(metaitem('dustVanadiumTrioxide') * 25)
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister()*/

    // Vanadium (III) sulfate (VRFB discharged negolyte)
    BR.recipeBuilder()
        .inputs(ore('dustVanadiumPentoxide') * 7)
        .inputs(ore('dustSulfur'))
        .fluidInputs(fluid('sulfuric_acid') * 3000)
        .fluidOutputs(fluid('diluted_vanadium_iii_sulfate_solution') * 3000)
        .fluidOutputs(fluid('sulfur_dioxide') * 1000)
        .EUt(VA[MV])
        .duration(100)
        .buildAndRegister()

    DISTILLERY.recipeBuilder()
        .fluidInputs(fluid('diluted_vanadium_iii_sulfate_solution') * 3000)
        .fluidOutputs(fluid('vanadium_iii_sulfate_solution') * 1000)
        .duration(20)
        .EUt(VA[LV])
        .buildAndRegister()

    // Vanadyl sulfate (VRFB discharged posolyte)
    BR.recipeBuilder()
        .inputs(ore('dustVanadiumPentoxide') * 7)
        .fluidInputs(fluid('distilled_water') * 9000)
        .fluidInputs(fluid('sulfuric_acid') * 3000)
        .fluidInputs(fluid('sulfur_dioxide') * 1000)
        .fluidOutputs(fluid('vanadyl_sulfate_solution') * 2000)
        .EUt(VA[MV])
        .duration(100)
        .buildAndRegister()