import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

ERF.recipeBuilder()
        .inputs(ore('dustCeriumIvOxide') * 12)
        .outputs(metaitem('dustCeriumIiiOxide') * 10)
        .fluidOutputs(fluid('oxygen') * 2000)
        .EUt(VA[EV])
        .blastFurnaceTemp(2273)
        .duration(20)
        .buildAndRegister()

FLUIDIZED_BR.recipeBuilder()
        .inputs(ore('dustCeriumIiiOxide') * 10)
        .fluidInputs(fluid('water') * 2000)
        .outputs(metaitem('dustCeriumIvOxide') * 12)
        .fluidOutputs(fluid('hydrogen') * 4000)
        .EUt(VA[EV])
        .duration(20)
        .buildAndRegister()

PYROLYSE_OVEN.recipeBuilder()
    .fluidInputs(fluid('methane') * 1000)
    .fluidOutputs(fluid('hydrogen') * 4000)
    .inputs(ore('dustAnyPurityBismuth'))
    .outputs(metaitem('dustSpentBismuthCatalyst') * 2)
    .duration(10)
    .EUt(VA[HV] * 2)
    .buildAndRegister()

ELECTROMAGNETIC_SEPARATOR.recipeBuilder()
    .inputs(ore('dustSpentBismuthCatalyst') * 2)
    .outputs(metaitem('dustBismuth') * 1)
    .outputs(metaitem('dustCarbon') * 1)
    .duration(20)
    .EUt(VA[HV])
    .buildAndRegister()
