import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

//TRONA
ROASTER.recipeBuilder()
        .inputs(ore('dustTrona') * 28)
        .outputs(metaitem('dustSodaAsh') * 18)
        .fluidOutputs(fluid('dense_steam') * 5000)
        .fluidOutputs(fluid('carbon_dioxide') * 1000)
        .EUt(VA[LV])
        .duration(120)
        .buildAndRegister()

//CASTNER PROCESS
ELECTROLYZER.recipeBuilder()
        .fluidInputs(fluid('sodium_hydroxide') * 864)
        .notConsumable(metaitem('stickNickel'))
        .notConsumable(metaitem('stickIron'))
        .outputs(metaitem('dustSodium') * 2)
        .fluidOutputs(fluid('oxygen') * 1000)
        .fluidOutputs(fluid('dense_steam') * 1000)
        .duration(600)
        .EUt(VA[LV] * 2)
        .buildAndRegister()

//DOWNS CELL PROCESSES
ELECTROLYTIC_CELL.recipeBuilder()
        .notConsumable(metaitem('graphite_electrode'))
        .notConsumable(metaitem('stickIron'))
        .notConsumable(metaitem('foilSteel'))
        .notConsumable(fluid('calcium_chloride') * 432)
        .inputs(ore('dustSalt') * 2)
        .fluidOutputs(fluid('chlorine') * 1000)
        .outputs(metaitem('dustSodium'))
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()

//COMPOUNDS
DISTILLERY.recipeBuilder()
        .fluidInputs(fluid('sodium_nitrate_solution') * 1000)
        .outputs(metaitem('dustSodiumNitrate') * 5)
        .fluidOutputs(fluid('water') * 1000)
        .duration(140)
        .EUt(VA[LV])
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(ore('dustSodiumNitrate') * 5)
        .outputs(metaitem('dustSodiumNitrite') * 4)
        .fluidOutputs(fluid('oxygen') * 1000)
        .duration(400)
        .EUt(VA[LV])
        .buildAndRegister()

BR.recipeBuilder()
        .fluidInputs(fluid('sodium_nitrate') * 720)
        .fluidInputs(fluid('lead') * 144)
        .fluidOutputs(fluid('sodium_nitrite') * 576)
        .outputs(metaitem('dustLeadIiOxide') * 2)
        .duration(20)
        .EUt(VA[LV])
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(ore('dustSodiumNitrite') * 8)
        .outputs(metaitem('dustSodiumOxide') * 3)
        .fluidOutputs(fluid('nitric_oxide') * 1000)
        .fluidOutputs(fluid('nitrogen_dioxide') * 1000)
        .duration(60)
        .EUt(VA[LV])
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustSodiumNitrite') * 4)
        .fluidInputs(fluid('water') * 1000)
        .fluidOutputs(fluid('sodium_nitrite_solution') * 1000)
        .duration(20)
        .EUt(VA[LV])
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustSodiumOxide') * 3)
        .fluidInputs(fluid('water') * 3000)
        .fluidOutputs(fluid('sodium_hydroxide_solution') * 2000)
        .duration(60)
        .EUt(VA[LV])
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(ore('dustSodiumSulfate') * 7)
        .circuitMeta(1)
        .outputs(metaitem('dustSodiumOxide') * 3)
        .fluidOutputs(fluid('sulfur_trioxide_reaction_mixture') * 2000)
        .duration(200)
        .EUt(VA[MV])
        .buildAndRegister()
