import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// Regular saline brine, 1 mol solids in 1000L

CLARIFIER.recipeBuilder()
    .fluidInputs(fluid('brine') * 10000)
    .fluidInputs(fluid('calcium_hydroxide_slurry') * 60)
    .fluidOutputs(fluid('demagnesiated_brine') * 9940)
    .chancedOutput(metaitem('dustMagnesiumHydroxide'), 3000, 0)
    .chancedOutput(metaitem('dustGypsum'), 4800, 0)
    .EUt(VA[LV])
    .duration(180)
    .buildAndRegister()

CLARIFIER.recipeBuilder()
    .fluidInputs(fluid('demagnesiated_brine') * 9940)
    .fluidInputs(fluid('soda_ash_solution') * 20)
    .fluidOutputs(fluid('decalcified_brine') * 9960)
    .chancedOutput(metaitem('dustCalcite'), 1000, 0)
    .EUt(VA[LV])
    .duration(180)
    .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
    .notConsumable(ore('springCupronickel'))
    .fluidInputs(fluid('decalcified_brine') * 10000)
    .chancedOutput(metaitem('dustSalt') * 20, 9600, 0)
    .fluidOutputs(fluid('brine_mother_liquor') * 1000)
    .fluidOutputs(fluid('dense_steam') * 9200)
    .EUt(VA[LV])
    .duration(180)
    .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
    .fluidInputs(fluid('brine_mother_liquor') * 1000)
    .chancedOutput(metaitem('dustSodiumSulfate'), 5600, 0)
    .fluidOutputs(fluid('potassium_rich_mother_liquor') * 1000)
    .EUt(VA[LV])
    .duration(180)
    .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
    .notConsumable(ore('springCupronickel'))
    .fluidInputs(fluid('potassium_rich_mother_liquor') * 1000)
    .chancedOutput(metaitem('dustRockSalt'), 4000, 0)
    .fluidOutputs(fluid('bromine_rich_mother_liquor') * 50)
    .fluidOutputs(fluid('dense_steam') * 950)
    .EUt(VA[LV])
    .duration(180)
    .buildAndRegister()

// Salar brine

CLARIFIER.recipeBuilder()
    .fluidInputs(fluid('salar_brine') * 10000)
    .fluidInputs(fluid('calcium_hydroxide_slurry') * 160)
    .fluidOutputs(fluid('demagnesiated_salar_brine') * 9840)
    .chancedOutput(metaitem('dustMagnesiumHydroxide'), 8000, 0)
    .chancedOutput(metaitem('dustGypsum') * 2, 6400, 0)
    .EUt(VA[LV])
    .duration(180)
    .buildAndRegister()

CLARIFIER.recipeBuilder()
    .fluidInputs(fluid('demagnesiated_salar_brine') * 9840)
    .fluidInputs(fluid('soda_ash_solution') * 15)
    .fluidOutputs(fluid('decalcified_salar_brine') * 9860)
    .chancedOutput(metaitem('dustCalcite'), 750, 0)
    .EUt(VA[LV])
    .duration(180)
    .buildAndRegister()

FLUID_COMPRESSOR.recipeBuilder()
    .notConsumable(metaitem('membrane.cellulose_acetate'))
    .fluidInputs(fluid('decalcified_salar_brine') * 9860)
    .fluidOutputs(fluid('concentrated_salar_brine') * 1000)
    .fluidOutputs(fluid('water') * 8860)
    .duration(40)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('soda_ash_solution') * 775)
    .fluidInputs(fluid('concentrated_salar_brine') * 1000)
    .chancedOutput(metaitem('gregtechfoodoption:lithium_carbonate_dust') * 6, 7750, 0)
    .fluidOutputs(fluid('wastewater') * 1775)
    .EUt(VA[LV])
    .duration(600)
    .buildAndRegister()