import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

ERF.recipeBuilder()
        .inputs(item('minecraft:redstone') * 5)
        .fluidInputs(fluid('oxygen') * 40000)
        .outputs(metaitem('dustOxidizedRedstone') * 5)
        .fluidOutputs(fluid('sulfur_dioxide') * 10000)
        .blastTemp(2500)
        .duration(400)
        .voltage(VA[HV])
        .buildAndRegister()

ERF.recipeBuilder()
        .inputs(ore('dustOxidizedRedstone'))
        .fluidInputs(fluid('carbon_monoxide') * 3000)
        .outputs(metaitem('dustMagneticRedstone'))
        .fluidOutputs(fluid('carbon_dioxide') * 3000)
        .blastTemp(1750)
        .duration(80)
        .voltage(VA[HV])
        .buildAndRegister()

ELECTROMAGNETIC_SEPARATOR.recipeBuilder()
        .inputs(ore('dustMagneticRedstone'))
        .outputs(metaitem('dustIron') * 2)
        .outputs(metaitem('dustNonmagneticRedstone'))
        .duration(60)
        .voltage(VA[MV])
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustNonmagneticRedstone') * 5)
        .fluidInputs(fluid('sulfuric_acid') * 3000)
        .outputs(metaitem('dustAcidTreatedRedstone') * 5)
        .fluidOutputs(fluid('mercury_ii_sulfate_solution') * 3000)
        .duration(200)
        .voltage(VA[MV])
        .buildAndRegister()

DISTILLERY.recipeBuilder()
        .fluidInputs(fluid('mercury_ii_sulfate_solution') * 1000)
        .outputs(metaitem('dustMercuryIiSulfate') * 6)
        .fluidOutputs(fluid('water') * 1000)
        .duration(80)
        .voltage(VA[LV])
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('water') * 1000)
        .inputs(ore('dustMercuryIiSulfate') * 6)
        .fluidOutputs(fluid('mercury_ii_sulfate_solution') * 1000)
        .duration(80)
        .voltage(VA[LV])
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(ore('dustMercuryIiSulfate') * 6)
        .inputs(ore('dustSalt') * 4)
        .outputs(metaitem('dustMercuryIiChloride') * 3)
        .outputs(metaitem('dustSodiumSulfate') * 7)
        .duration(100)
        .voltage(VA[MV])

BR.recipeBuilder()
        .inputs(ore('dustAcidTreatedRedstone') * 5)
        .fluidInputs(fluid('sodium_hydroxide_solution') * 2000)
        .fluidInputs(fluid('dense_steam') * 1000)
        .outputs(metaitem('dustRuby'))
        .fluidOutputs(fluid('diluted_sodium_silicate') * 4000)
        .duration(120)
        .voltage(VA[MV])
        .buildAndRegister()