def RedundantOreRemovals = [
        item('gregtech:ore_orthomagmatic_deposit_0'),
        ore('oreNetherrackOrthomagmaticDeposit'),
        ore('oreEndstoneOrthomagmaticDeposit'),
        ore('crushedOrthomagmaticDeposit'),
        ore('crushedPurifiedOrthomagmaticDeposit'),
        ore('crushedCentrifugedOrthomagmaticDeposit'),
        ore('dustImpureOrthomagmaticDeposit'),
        ore('dustPureOrthomagmaticDeposit'),
        ore('dustOrthomagmaticDeposit'),
        ore('dustSmallOrthomagmaticDeposit'),
        ore('dustTinyOrthomagmaticDeposit'),

        item('gregtech:ore_metamorphic_deposit_0'),
        ore('oreNetherrackMetamorphicDeposit'),
        ore('oreEndstoneMetamorphicDeposit'),
        ore('crushedMetamorphicDeposit'),
        ore('crushedPurifiedMetamorphicDeposit'),
        ore('crushedCentrifugedMetamorphicDeposit'),
        ore('dustImpureMetamorphicDeposit'),
        ore('dustPureMetamorphicDeposit'),
        ore('dustMetamorphicDeposit'),
        ore('dustSmallMetamorphicDeposit'),
        ore('dustTinyMetamorphicDeposit'),

        item('gregtech:ore_sedimentary_deposit_0'),
        ore('oreNetherrackSedimentaryDeposit'),
        ore('oreEndstoneSedimentaryDeposit'),
        ore('crushedSedimentaryDeposit'),
        ore('crushedPurifiedSedimentaryDeposit'),
        ore('crushedCentrifugedSedimentaryDeposit'),
        ore('dustImpureSedimentaryDeposit'),
        ore('dustPureSedimentaryDeposit'),
        ore('dustSedimentaryDeposit'),
        ore('dustSmallSedimentaryDeposit'),
        ore('dustTinySedimentaryDeposit'),

        item('gregtech:ore_hydrothermal_deposit_0'),
        ore('oreNetherrackHydrothermalDeposit'),
        ore('oreEndstoneHydrothermalDeposit'),
        ore('crushedHydrothermalDeposit'),
        ore('crushedPurifiedHydrothermalDeposit'),
        ore('crushedCentrifugedHydrothermalDeposit'),
        ore('dustImpureHydrothermalDeposit'),
        ore('dustPureHydrothermalDeposit'),
        ore('dustHydrothermalDeposit'),
        ore('dustSmallHydrothermalDeposit'),
        ore('dustTinyHydrothermalDeposit'),

        item('gregtech:ore_alluvial_deposit_0'),
        ore('oreNetherrackAlluvialDeposit'),
        ore('oreEndstoneAlluvialDeposit'),
        ore('crushedAlluvialDeposit'),
        ore('crushedPurifiedAlluvialDeposit'),
        ore('crushedCentrifugedAlluvialDeposit'),
        ore('dustImpureAlluvialDeposit'),
        ore('dustPureAlluvialDeposit'),
        ore('dustAlluvialDeposit'),
        ore('dustSmallAlluvialDeposit'),
        ore('dustTinyAlluvialDeposit'),

        item('gregtech:ore_magmatic_hydrothermal_deposit_0'),
        ore('oreNetherrackMagmaticHydrothermalDeposit'),
        ore('oreEndstoneMagmaticHydrothermalDeposit'),
        ore('crushedMagmaticHydrothermalDeposit'),
        ore('crushedPurifiedMagmaticHydrothermalDeposit'),
        ore('crushedCentrifugedMagmaticHydrothermalDeposit'),
        ore('dustImpureMagmaticHydrothermalDeposit'),
        ore('dustPureMagmaticHydrothermalDeposit'),
        ore('dustMagmaticHydrothermalDeposit'),
        ore('dustSmallMagmaticHydrothermalDeposit'),
        ore('dustTinyMagmaticHydrothermalDeposit'),

        item('gregtech:ore_coal_deposit_0'),
        ore('oreNetherrackCoalDeposit'),
        ore('oreEndstoneCoalDeposit'),
        ore('crushedCoalDeposit'),
        ore('crushedPurifiedCoalDeposit'),
        ore('crushedCentrifugedCoalDeposit'),
        ore('dustImpureCoalDeposit'),
        ore('dustPureCoalDeposit'),
        ore('dustCoalDeposit'),
        ore('dustSmallCoalDeposit'),
        ore('dustTinyCoalDeposit'),

        item('gregtech:ore_native_copper_deposit_0'),
        ore('oreNetherrackNativeCopperDeposit'),
        ore('oreEndstoneNativeCopperDeposit'),
        ore('crushedNativeCopperDeposit'),
        ore('crushedPurifiedNativeCopperDeposit'),
        ore('crushedCentrifugedNativeCopperDeposit'),
        ore('dustImpureNativeCopperDeposit'),
        ore('dustPureNativeCopperDeposit'),
        ore('dustNativeCopperDeposit'),
        ore('dustSmallNativeCopperDeposit'),
        ore('dustTinyNativeCopperDeposit'),

        item('gregtech:ore_anthracite_deposit_0'),
        ore('oreNetherrackAnthraciteDeposit'),
        ore('oreEndstoneAnthraciteDeposit'),
        ore('crushedAnthraciteDeposit'),
        ore('crushedPurifiedAnthraciteDeposit'),
        ore('crushedCentrifugedAnthraciteDeposit'),
        ore('dustImpureAnthraciteDeposit'),
        ore('dustPureAnthraciteDeposit'),
        ore('dustAnthraciteDeposit'),
        ore('dustSmallAnthraciteDeposit'),
        ore('dustTinyAnthraciteDeposit'),

        item('gregtech:ore_lignite_deposit_0'),
        ore('oreNetherrackLigniteDeposit'),
        ore('oreEndstoneLigniteDeposit'),
        ore('crushedLigniteDeposit'),
        ore('crushedPurifiedLigniteDeposit'),
        ore('crushedCentrifugedLigniteDeposit'),
        ore('dustImpureLigniteDeposit'),
        ore('dustPureLigniteDeposit'),
        ore('dustLigniteDeposit'),
        ore('dustSmallLigniteDeposit'),
        ore('dustTinyLigniteDeposit')
]

for (entry in RedundantOreRemovals) {
    for (item in entry.getMatchingStacks()) {
        mods.jei.ingredient.removeAndHide(item)
    }
}
