import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*
import gregtech.api.recipes.chance.output.ChancedOutputLogic

// Earth
SALVAGING.recipeBuilder()
    .inputs(Planetoid.PLANETOIDS.inverse().get(0).getDisplayItem())
    .outputs(metaitem('scrap.commercial') * 2)
    .outputs(metaitem('scrap.parts'))
    .chancedOutput(metaitem('scrap.supply'), 8000, 0)
    .chancedOutput(metaitem('scrap.commercial'), 3000, 0)
    .chancedOutput(metaitem('scrap.supply'), 2000, 0)
    .chancedOutput(metaitem('scrap.military'), 1000, 0)
    .chancedOutput(metaitem('scrap.parts'), 500, 0)
    .chancedOutput(metaitem('scrap.commercial') * 3, 200, 0)
    .chancedOutput(metaitem('scrap.military'), 100, 0)
    .duration(5000)
    .buildAndRegister()

// Moon
SALVAGING.recipeBuilder()
    .inputs(Planetoid.PLANETOIDS.inverse().get(800).getDisplayItem())
    .outputs(metaitem('scrap.supply') * 2)
    .outputs(metaitem('scrap.commercial'))
    .outputs(metaitem('scrap.parts'))
    .chancedOutput(metaitem('scrap.supply'), 8000, 0)
    .chancedOutput(metaitem('scrap.parts'), 5000, 0)
    .chancedOutput(metaitem('scrap.military'), 2000, 0)
    .chancedOutput(metaitem('scrap.commercial'), 1000, 0)
    .chancedOutput(metaitem('scrap.parts') * 2, 500, 0)
    .chancedOutput(metaitem('scrap.military'), 200, 0)
    .duration(6000)
    .buildAndRegister()

// Have fun!
def robotArms = [metaitem('robot.arm.mv'), metaitem('robot.arm.hv'),
                 metaitem('robot.arm.ev'), metaitem('robot.arm.iv'),
                 metaitem('robot.arm.luv'), metaitem('robot.arm.zpm')];

def decreases = [-50, -100, -200, -400, -1000, -2000]
for (def i = 0; i < 6; i++) {
    SCRAP_RECYCLER.recipeBuilder()
        .inputs(metaitem('scrap.military'))
        .inputs(robotArms[i])
        .chancedOutput(metaitem('scrap.unusable'), 2000, decreases[i])
        .chancedOutput(metaitem('scrap.military.ammo'), 4000, 500)
        .chancedOutput(metaitem('scrap.military.unknown'), 1000, 2000)
        .chancedOutput(metaitem('scrap.military.armor'), 1500, 5000)
        .chancedOutput(metaitem('scrap.military.unknown') * 2, 2000, 4000)
        .chancedOutput(metaitem('scrap.unusable'), 10000, 0)
        .chancedOutputLogic(ChancedOutputLogic.XOR)
        .EUt(VA[HV])
        .duration(600 - 5 * i)
        .buildAndRegister()
}

SCRAP_RECYCLER.recipeBuilder()
    .inputs(metaitem('scrap.military'))
    .notConsumed(metaitem('sensor.hv'))
    .chancedOutput(metaitem('scrap.unusable'), 8500, -50)
    .chancedOutput(metaitem('scrap.military.ammo'), 4000, 500)
    .chancedOutput(metaitem('scrap.military.unknown'), 1000, 2000)
    .chancedOutput(metaitem('scrap.military.armor'), 1500, 5000)
    .chancedOutput(metaitem('scrap.military.unknown') * 2, 2000, 4000)
    .chancedOutputLogic(ChancedOutputLogic.XOR)
    .EUt(VA[HV])
    .duration(500)
    .buildAndRegister()

SCRAP_RECYCLER.recipeBuilder()
    .inputs(metaitem('scrap.commercial'))
    .notConsumed(metaitem('sensor.hv'))
    .chancedOutput(metaitem('scrap.commercial.lootbox'), 8700, 10)
    .chancedOutput(metaitem('scrap.unusable'), 3000, -300)
    .chancedOutput(metaitem('scrap.commercial.food'), 7000, 10)    
    .chancedOutput(metaitem('scrap.commercial.data'), 2000, 1000)
    .chancedOutput(metaitem('scrap.unusable'), 10000, 0)
    .chancedOutputLogic(ChancedOutputLogic.XOR)
    .EUt(VA[HV])
    .duration(500)
    .buildAndRegister()

for (def i = 0; i < 6; i++) {
    SCRAP_RECYCLER.recipeBuilder()
        .inputs(metaitem('scrap.supply'))
        .inputs(robotArms[i])
        .chancedOutput(metaitem('scrap.unusable'), 1600, decreases[i])
        .chancedOutput(metaitem('scrap.supply.wiring'), 6000, 0)
        .chancedOutput(metaitem('scrap.supply.alloy'), 7000, 0)    
        .chancedOutput(metaitem('scrap.supply.chemical'), 2000, 0)
        .chancedOutput(metaitem('scrap.supply.biological'), 2000, 0)
        .chancedOutput(metaitem('scrap.supply.circuitry'), 2000, 0)
        .chancedOutput(metaitem('scrap.supply.component'), 2000, 0)
        .chancedOutput(metaitem('scrap.unusable'), 10000, 0)
        .chancedOutputLogic(ChancedOutputLogic.XOR)
        .EUt(VA[HV])
        .duration(600 - 5 * i)
        .buildAndRegister()
}

SCRAP_RECYCLER.recipeBuilder()
    .inputs(metaitem('scrap.supply'))
    .notConsumed(metaitem('sensor.hv'))
    .chancedOutput(metaitem('scrap.unusable'), 3000, -25)
    .chancedOutput(metaitem('scrap.supply.wiring'), 6000, 0)
    .chancedOutput(metaitem('scrap.supply.alloy'), 7000, 0)    
    .chancedOutput(metaitem('scrap.supply.chemical'), 2000, 0)
    .chancedOutput(metaitem('scrap.supply.biological'), 2000, 0)
    .chancedOutput(metaitem('scrap.supply.circuitry'), 2000, 0)
    .chancedOutput(metaitem('scrap.supply.component'), 2000, 0)
    .chancedOutput(metaitem('scrap.unusable'), 10000, 0)
    .chancedOutputLogic(ChancedOutputLogic.XOR)
    .EUt(VA[HV])
    .duration(500)
    .buildAndRegister()

for (def i = 0; i < 6; i++) {
    SCRAP_RECYCLER.recipeBuilder()
        .inputs(metaitem('scrap.parts'))
        .inputs(robotArms[i])
        .chancedOutput(metaitem('scrap.unusable'), 1600, decreases[i])
        .chancedOutput(metaitem('scrap.parts.cladding'), 2000, 0)
        .chancedOutput(metaitem('scrap.parts.engine'), 4000, 0)
        .chancedOutput(metaitem('scrap.parts.life_support'), 6000, 0)
        .chancedOutput(metaitem('scrap.parts.energy'), 2000, 0)
        .chancedOutput(metaitem('scrap.unusable'), 10000, 0)
        .chancedOutputLogic(ChancedOutputLogic.XOR)
        .EUt(VA[HV])
        .duration(600 - 5 * i)
        .buildAndRegister()
}

SCRAP_RECYCLER.recipeBuilder()
    .inputs(metaitem('scrap.parts'))
    .notConsumed(metaitem('sensor.hv'))
    .chancedOutput(metaitem('scrap.unusable'), 3000, -25)
    .chancedOutput(metaitem('scrap.parts.cladding'), 2000, 0)
    .chancedOutput(metaitem('scrap.parts.engine'), 4000, 0)
    .chancedOutput(metaitem('scrap.parts.life_support'), 6000, 0)
    .chancedOutput(metaitem('scrap.parts.energy'), 2000, 0)
    .chancedOutput(metaitem('scrap.unusable'), 10000, 0)
    .chancedOutputLogic(ChancedOutputLogic.XOR)
    .EUt(VA[HV])
    .duration(500)
    .buildAndRegister()

// Commercial
// TODO: actual lootboxes
SCRAP_RECYCLER.recipeBuilder()
    .inputs(metaitem('scrap.commercial.lootbox'))
    .notConsumed(metaitem('robot.arm.lv'))
    .chancedOutput(metaitem('scrap.unusable'), 6000, 0)
    .chancedOutput(metaitem('food.protein_paste'), 4000, 0)
    .chancedOutput(metaitem('food.cellulose_reformate'), 4000, 0)
    .chancedOutput(metaitem('food.glue_pizza'), 1000, 0)
    .chancedOutput(metaitem('coin.doge'), 1000, 0)
    .chancedOutput(item('betterquesting:guide_book', 1000, 0))
    .EUt(VA[MV])
    .duration(100)
    .buildAndRegister()