import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

MIXER.recipeBuilder()
        .fluidInputs(fluid('water') * 100)
        .inputs(ore('dustTinyAsh'))
        .fluidOutputs(fluid('ash_slurry') * 100)
        .duration(5)
        .EUt(VA[ULV])
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('water') * 100)
        .inputs(ore('dustTinyDarkAsh'))
        .fluidOutputs(fluid('ash_slurry') * 100)
        .duration(5)
        .EUt(VA[ULV])
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('water') * 1000)
        .inputs(ore('dustAsh'))
        .fluidOutputs(fluid('ash_slurry') * 1000)
        .duration(40)
        .EUt(VA[ULV])
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('water') * 1000)
        .inputs(ore('dustDarkAsh'))
        .fluidOutputs(fluid('ash_slurry') * 1000)
        .duration(40)
        .EUt(VA[ULV])
        .buildAndRegister()

SIFTER.recipeBuilder()
        .fluidInputs(fluid('flue_gas') * 16000)
        .inputs(ore('dustTinyCalcite'))
        .fluidOutputs(fluid('desulfurized_flue_gas') * 16000)
        .outputs(metaitem('dustTinyCalciumSulfite'))
        .duration(4)
        .EUt(VA[LV])
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(ore('dustCalciumSulfite') * 5)
        .circuitMeta(1)
        .fluidOutputs(fluid('sulfur_dioxide') * 1000)
        .outputs(metaitem('dustQuicklime') * 2)
        .duration(80)
        .EUt(VA[LV])
        .buildAndRegister()

ROASTER.recipeBuilder()
        .fluidInputs(fluid('air') * 1500)
        .inputs(ore('dustCalciumSulfite') * 5)
        .outputs(metaitem('dustCalciumSulfate') * 6)
        .duration(80)
        .EUt(VA[LV])
        .buildAndRegister()

ROASTER.recipeBuilder()
        .fluidInputs(fluid('oxygen') * 1000)
        .inputs(ore('dustCalciumSulfite') * 5)
        .outputs(metaitem('dustCalciumSulfate') * 6)
        .duration(80)
        .EUt(VA[LV])
        .buildAndRegister()
