import static prePostInit.Recipemaps.*
import static globals.SinteringGlobals.*
import static gregtech.api.GTValues.*

//BORAX CALCINATION
ROASTER.recipeBuilder()
    .inputs(ore('dustBorax') * 4)
    .outputs(metaitem('dustSodiumTetraborate') * 13)
    .fluidOutputs(fluid('dense_steam') * 10000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

//DISSOLUTION OF TETRABORATE
BR.recipeBuilder()
    .inputs(ore('dustSodiumTetraborate') * 13)
    .fluidInputs(fluid('distilled_water') * 2000)
    .outputs(metaitem('dustTinyClay'))
    .fluidOutputs(fluid('borate_liquor') * 2000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

//PRECIPITATION OF BORIC ACID
BR.recipeBuilder()
    .fluidInputs(fluid('borate_liquor') * 2000)
    .fluidInputs(fluid('hydrochloric_acid') * 2000)
    .outputs(metaitem('dustBoricAcid') * 31)
    .fluidOutputs(fluid('salt_water') * 2000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

//CALCINATION OF BORIC ACID
ROASTER.recipeBuilder()
    .inputs(ore('dustBoricAcid') * 14)
    .outputs(metaitem('dustBoronTrioxide') * 5)
    .fluidOutputs(fluid('dense_steam') * 3000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

//REDUCTION OF BORON TRIOXIDE
ROASTER.recipeBuilder()
    .inputs(ore('dustBoronTrioxide') * 5)
    .inputs(ore('dustAnyPurityMagnesium') * 3)
    .outputs(metaitem('dustAmorphousBoron') * 2)
    .outputs(metaitem('dustMagnesia') * 6)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

MACERATOR.recipeBuilder()
    .inputs(ore('dustAmorphousBoron') * 2)
    .outputs(metaitem('dustBoron'))
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

//MAGNESIUM REGERNATION
ELECTROLYTIC_CELL.recipeBuilder()
    .inputs(ore('dustMagnesia') * 2)
    .notConsumable(ore('stickTantalum'))
    .notConsumable(metaitem('graphite_electrode'))
    .notConsumable(fluid('rock_salt') * 288)
    .notConsumable(fluid('magnesium_chloride') * 864)
    .duration(100)
    .outputs(metaitem('dustMagnesium'))
    .fluidOutputs(fluid('oxygen') * 1000)
    .EUt(VA[LV])
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .inputs(ore('dustMagnesia') * 2)
    .notConsumable(ore('stickSteel'))
    .notConsumable(metaitem('graphite_electrode'))
    .notConsumable(fluid('rock_salt') * 288)
    .notConsumable(fluid('magnesium_chloride') * 864)
    .duration(400)
    .outputs(metaitem('dustMagnesium'))
    .fluidOutputs(fluid('oxygen') * 1000)
    .EUt(VA[LV])
    .buildAndRegister()

//PRODUCTION OF KBF4
BR.recipeBuilder()
    .inputs(ore('dustBoricAcid') * 7)
    .fluidInputs(fluid('hydrofluoric_acid') * 4000)
    .fluidOutputs(fluid('tetrafluoroboric_acid') * 1000)
    .duration(600)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustPotassiumCarbonate') * 6)
    .fluidInputs(fluid('tetrafluoroboric_acid') * 1000)
    .fluidOutputs(fluid('potassium_tetrafluoroborate_solution') * 1000)
    .fluidOutputs(fluid('carbon_dioxide') * 1000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('potassium_tetrafluoroborate_solution') * 1000)
    .outputs(metaitem('dustPotassiumTetrafluoroborate') * 12)
    .fluidOutputs(fluid('water') * 7000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

//ELECTROLYSIS OF B2O3
ELECTROLYTIC_CELL.recipeBuilder()
    .inputs(ore('dustBoronTrioxide') * 5)
    .notConsumable(metaitem('graphite_electrode'))
    .notConsumable(metaitem('stickBoronCarbide'))
    .notConsumable(fluid('sodium_fluoride') * (13 * 144))
    .notConsumable(fluid('potassium_tetrafluoroborate') * (6 * 144))
    .outputs(metaitem('dustElectrolyticBoron') * 2)
    .fluidOutputs(fluid('oxygen') * 3000)
    .duration(120)
    .EUt(VA[MV])
    .buildAndRegister()

MACERATOR.recipeBuilder()
    .inputs(ore('dustElectrolyticBoron') * 4)
    .outputs(metaitem('dustBoron') * 3)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

//PURIFICATION OF SEMICONDUCTOR-GRADE BORON
FLUIDIZED_BR.recipeBuilder()
    .inputs(ore('dustAmorphousBoron') * 1)
    .fluidInputs(fluid('chlorine') * 4040)
    .chancedOutput(metaitem('dustMagnesiumChloride') * 3, 600, 0)
    .fluidOutputs(fluid('boron_trichloride') * 1000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

FLUIDIZED_BR.recipeBuilder()
    .inputs(ore('dustElectrolyticBoron') * 1)
    .fluidInputs(fluid('chlorine') * 3040)
    .chancedOutput(metaitem('dustMagnesiumChloride') * 3, 600, 0)
    .fluidOutputs(fluid('boron_trichloride') * 1000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('boron_trichloride') * 1000)
    .fluidInputs(fluid('hydrogen') * 3000)
    .outputs(metaitem('dustHighPurityBoron'))
    .fluidOutputs(fluid('hydrogen_chloride') * 3000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('boron_trioxide') * 720)
    .fluidInputs(fluid('chlorine') * 6000)
    .inputs(metaitem('dustCarbon') * 3)
    .fluidOutputs(fluid('boron_trichloride') * 2000)
    .fluidOutputs(fluid('carbon_monoxide') * 3000)
    .duration(400)
    .EUt(VA[HV])
    .buildAndRegister()

//Sodium Borohydride

BR.recipeBuilder()
    .inputs(ore('dustBoricAcid') * 7)
    .fluidInputs(fluid('methanol') * 3000)
    .fluidInputs(fluid('sulfuric_acid') * 1000)
    .fluidOutputs(fluid('trimethyl_borate_solution') * 4000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('trimethyl_borate_solution') * 4000)
    .fluidOutputs(fluid('sulfuric_acid') * 1000)
    .fluidOutputs(fluid('water') * 3000)
    .fluidOutputs(fluid('trimethyl_borate') * 1000)
    .duration(600)
    .EUt(90)
    .buildAndRegister()

MIXER.recipeBuilder()
    .notConsumable(fluid('lubricating_oil') * 100)
    .fluidInputs(fluid('sodium') * 144)
    .fluidInputs(fluid('hydrogen') * 1000)
    .outputs(metaitem('dustSodiumHydride') * 2)
    .duration(100)
    .EUt(VA[HV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumHydride') * 8)
    .fluidInputs(fluid('trimethyl_borate') * 1000)
    .outputs(metaitem('dustImpureSodiumBorohydride') * 24)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

AUTOCLAVE.recipeBuilder()
    .inputs(ore('dustImpureSodiumBorohydride') * 24)
    .fluidInputs(fluid('isopropylamine') * 1000)
    .outputs(metaitem('dustSodiumMethoxide') * 18)
    .fluidOutputs(fluid('sodium_borohydride_solution') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

VACUUM_DT.recipeBuilder()
    .fluidInputs(fluid('sodium_borohydride_solution') * 1000)
    .outputs(metaitem('dustSodiumBorohydride') * 6)
    .fluidOutputs(fluid('isopropylamine') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumMethoxide') * 6)
    .fluidInputs(fluid('water') * 1000)
    .fluidOutputs(fluid('sodium_hydroxide_methanol_solution') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('sodium_hydroxide_methanol_solution') * 1000)
    .outputs(metaitem('dustSodiumHydroxide') * 3)
    .fluidOutputs(fluid('methanol') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

//Sodium Cyanoborohydride

BR.recipeBuilder()
    .fluidInputs(fluid('diborane') * 500)
    .inputs(ore('dustSodiumCyanide') * 6)
    .outputs(metaitem('dustSodiumCyanoborohydride') * 14)
    .duration(160)
    .EUt(VA[MV])
    .buildAndRegister()
