import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// Boric acid

    // Kernite

    BR.recipeBuilder()
        .inputs(ore('dustKernite'))
        .fluidInputs(fluid('sulfuric_acid') * 1000)
        .fluidInputs(fluid('distilled_water') * 3000)
        .fluidOutputs(fluid('boric_acid_solution') * 2000)
        .fluidOutputs(fluid('kernite_liquor') * 2000)
        .duration(120)
        .EUt(VA[LV])
        .buildAndRegister()

    CLARIFIER.recipeBuilder()
        .fluidInputs(fluid('kernite_liquor') * 2000)
        .chancedOutput(metaitem('dustLimestoneTailings'), 1000, 0)
        .fluidOutputs(fluid('clarified_kernite_liquor') * 2000)
        .duration(120)
        .EUt(VA[LV])
        .buildAndRegister()

    CRYSTALLIZER.recipeBuilder()
        .notConsumable(ore('springCupronickel'))
        .fluidInputs(fluid('clarified_kernite_liquor') * 2000)
        .outputs(metaitem('dustBoricAcid') * 28)
        .fluidOutputs(fluid('sodium_sulfate_solution') * 1000)
        .fluidOutputs(fluid('dense_steam') * 1000)
        .duration(120)
        .EUt(VA[LV])
        .buildAndRegister()

    // Colemanite

    BR.recipeBuilder()
        .inputs(ore('dustColemanite'))
        .fluidInputs(fluid('sulfuric_acid') * 2000)
        .fluidInputs(fluid('distilled_water') * 12000)
        .fluidOutputs(fluid('colemanite_liquor') * 6000)
        .duration(120)
        .EUt(VA[LV])
        .buildAndRegister()

    SIFTER.recipeBuilder()
        .notConsumable(metaitem('item_filter'))
        .fluidInputs(fluid('colemanite_liquor') * 6000)
        .outputs(metaitem('dustGypsum') * 2)
        .fluidOutputs(fluid('clarified_colemanite_liquor') * 6000)
        .duration(120)
        .EUt(VA[LV])
        .buildAndRegister()

    CRYSTALLIZER.recipeBuilder()
        .fluidInputs(fluid('clarified_colemanite_liquor') * 1000)
        .outputs(metaitem('dustBoricAcid') * 7)
        .fluidOutputs(fluid('wastewater') * 1000)
        .duration(20)
        .EUt(VA[LV])
        .buildAndRegister()

    // Borax

    BR.recipeBuilder()
        .inputs(ore('dustBorax'))
        .fluidInputs(fluid('sulfuric_acid') * 1000)
        .fluidOutputs(fluid('borax_liquor') * 5000)
        .duration(120)
        .EUt(VA[LV])
        .buildAndRegister()

    CLARIFIER.recipeBuilder()
        .fluidInputs(fluid('borax_liquor') * 5000)
        .chancedOutput(metaitem('dustLimestoneTailings'), 1000, 0)
        .fluidOutputs(fluid('clarified_borax_liquor') * 5000)
        .duration(120)
        .EUt(VA[LV])
        .buildAndRegister()

    CRYSTALLIZER.recipeBuilder()
        .notConsumable(ore('springCupronickel'))
        .fluidInputs(fluid('clarified_borax_liquor') * 5000)
        .outputs(metaitem('dustBoricAcid') * 28)
        .fluidOutputs(fluid('sodium_sulfate_solution') * 1000)
        .fluidOutputs(fluid('dense_steam') * 4000)
        .duration(120)
        .EUt(VA[LV])
        .buildAndRegister()

    // From brine

    MIXER_SETTLER.recipeBuilder()
        .fluidInputs(fluid('boron_extract') * 10000)
        .fluidInputs(fluid('sulfuric_acid') * 1000)
        .fluidInputs(fluid('distilled_water') * 2000)
        .fluidOutputs(fluid('boron_extraction_mixture') * 10000)
        .fluidOutputs(fluid('boric_acid_concentrate') * 2000)
        .requiredCells(2)
        .duration(60)
        .EUt(VA[MV])
        .buildAndRegister()

    DT.recipeBuilder()
        .fluidInputs(fluid('boric_acid_concentrate') * 2000)
        .outputs(metaitem('dustBoricAcid') * 7)
        .fluidOutputs(fluid('sulfuric_acid') * 1000)
        .fluidOutputs(fluid('water') * 1000)
        .duration(60)
        .EUt(VA[LV])
        .buildAndRegister()

// Boron trioxide

ROASTER.recipeBuilder()
    .inputs(ore('dustBoricAcid') * 14)
    .outputs(metaitem('dustBoronTrioxide') * 5)
    .fluidOutputs(fluid('dense_steam') * 3000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

// Boron metal

ROASTER.recipeBuilder()
    .inputs(ore('dustBoronTrioxide') * 5)
    .inputs(ore('dustAnyPurityMagnesium') * 3)
    .outputs(metaitem('dustBoronMixture') * 8)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
    .inputs(ore('dustBoronMixture') * 8)
    .fluidInputs(fluid('hydrochloric_acid') * 6000)
    .outputs(metaitem('dustBoron') * 2)
    .fluidOutputs(fluid('diluted_magnesium_chloride_solution') * 9000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

// Potassium tetrafluoroborate

BR.recipeBuilder()
    .inputs(ore('dustBoricAcid') * 7)
    .fluidInputs(fluid('hydrofluoric_acid') * 4000)
    .fluidOutputs(fluid('tetrafluoroboric_acid') * 1000)
    .duration(600)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustPotassiumCarbonate') * 6)
    .fluidInputs(fluid('tetrafluoroboric_acid') * 1000)
    .fluidOutputs(fluid('potassium_tetrafluoroborate_solution') * 1000)
    .fluidOutputs(fluid('carbon_dioxide') * 1000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('potassium_tetrafluoroborate_solution') * 1000)
    .outputs(metaitem('dustPotassiumTetrafluoroborate') * 12)
    .fluidOutputs(fluid('water') * 7000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

// Purification

FLUIDIZED_BR.recipeBuilder()
    .inputs(ore('dustBoron') * 1)
    .fluidInputs(fluid('chlorine') * 3120)
    .chancedOutput(metaitem('dustMagnesiumChloride') * 3, 600, 0)
    .fluidOutputs(fluid('boron_trichloride') * 1000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

FLUIDIZED_BR.recipeBuilder()
    .inputs(ore('dustHighPurityBoron') * 1)
    .fluidInputs(fluid('chlorine') * 3120)
    .fluidOutputs(fluid('boron_trichloride') * 1000)
    .duration(20)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('boron_trichloride') * 1000)
    .fluidInputs(fluid('hydrogen') * 3000)
    .outputs(metaitem('dustHighPurityBoron'))
    .fluidOutputs(fluid('hydrogen_chloride') * 3000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()

REACTION_FURNACE.recipeBuilder()
    .fluidInputs(fluid('boron_trioxide') * 720)
    .fluidInputs(fluid('chlorine') * 6000)
    .inputs(metaitem('dustCarbon') * 3)
    .fluidOutputs(fluid('boron_trichloride') * 2000)
    .fluidOutputs(fluid('carbon_monoxide') * 3000)
    .duration(400)
    .EUt(VA[HV])
    .buildAndRegister()

// Sodium borohydride

BR.recipeBuilder()
    .inputs(ore('dustBoricAcid') * 7)
    .fluidInputs(fluid('methanol') * 3000)
    .fluidInputs(fluid('sulfuric_acid') * 1000)
    .fluidOutputs(fluid('trimethyl_borate_solution') * 4000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('trimethyl_borate_solution') * 4000)
    .fluidOutputs(fluid('sulfuric_acid') * 1000)
    .fluidOutputs(fluid('water') * 3000)
    .fluidOutputs(fluid('trimethyl_borate') * 1000)
    .duration(600)
    .EUt(90)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumHydride') * 8)
    .fluidInputs(fluid('trimethyl_borate') * 1000)
    .outputs(metaitem('dustImpureSodiumBorohydride') * 24)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

AUTOCLAVE.recipeBuilder()
    .inputs(ore('dustImpureSodiumBorohydride') * 24)
    .fluidInputs(fluid('isopropylamine') * 1000)
    .outputs(metaitem('dustSodiumMethoxide') * 18)
    .fluidOutputs(fluid('sodium_borohydride_solution') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

VACUUM_DT.recipeBuilder()
    .fluidInputs(fluid('sodium_borohydride_solution') * 1000)
    .outputs(metaitem('dustSodiumBorohydride') * 6)
    .fluidOutputs(fluid('isopropylamine') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumMethoxide') * 6)
    .fluidInputs(fluid('water') * 1000)
    .fluidOutputs(fluid('sodium_hydroxide_methanol_solution') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('sodium_hydroxide_methanol_solution') * 1000)
    .outputs(metaitem('dustSodiumHydroxide') * 3)
    .fluidOutputs(fluid('methanol') * 1000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

// Sodium cyanoborohydride

BR.recipeBuilder()
    .fluidInputs(fluid('diborane') * 500)
    .inputs(ore('dustSodiumCyanide') * 6)
    .outputs(metaitem('dustSodiumCyanoborohydride') * 14)
    .duration(160)
    .EUt(VA[MV])
    .buildAndRegister()

// Diborane

BR.recipeBuilder()
    .inputs(ore('dustLithiumHydride') * 12)
    .fluidInputs(fluid('boron_trifluoride') * 8000)
    .outputs(metaitem('dustLithiumTetrafluoroborate') * 36)
    .fluidOutputs(fluid('diborane') * 1000)
    .duration(300)
    .EUt(VA[LV])
    .buildAndRegister()

ROASTER.recipeBuilder()
    .inputs(ore('dustLithiumTetrafluoroborate') * 6)
    .outputs(metaitem('dustLithiumFluoride') * 2)
    .fluidOutputs(fluid('boron_trifluoride') * 1000)
    .duration(300)
    .EUt(VA[LV])
    .buildAndRegister()

// Boron Trifluoride

BR.recipeBuilder()
    .inputs(ore('dustBoronTrioxide') * 5)
    .fluidInputs(fluid('hydrogen_fluoride') * 6000)
    .fluidOutputs(fluid('boron_trifluoride') * 2000)
    .fluidOutputs(fluid('water') * 3000)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustBoricAcid') * 7)
    .fluidInputs(fluid('hydrogen_fluoride') * 3000)
    .fluidOutputs(fluid('boron_trifluoride') * 1000)
    .fluidOutputs(fluid('water') * 3000)
    .duration(100)
    .EUt(VA[LV])
    .buildAndRegister()