import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

//FROM BAUXITE
ELECTROLYZER.recipeBuilder()
.fluidInputs(fluid('impure_soda_ash_solution') * 1000)
.notConsumable(ore('stickSteel'))
.notConsumable(metaitem('graphite_electrode'))
.fluidOutputs(fluid('soda_ash_solution') * 1000)
.chancedOutput(metaitem('dustGallium'), 500, 0)
.duration(300)
.EUt(VA[LV])
.buildAndRegister()

ELECTROLYZER.recipeBuilder()
.fluidInputs(fluid('impure_sodium_hydroxide_solution') * 1000)
.notConsumable(ore('stickSteel'))
.notConsumable(metaitem('graphite_electrode'))
.fluidOutputs(fluid('sodium_hydroxide_solution') * 1000)
.chancedOutput(metaitem('dustGallium'), 500, 0)
.duration(300)
.EUt(VA[LV])
.buildAndRegister()

//FROM SPHALERITE (WILL ADD LATER)

//FROM COAL FLY ASH (WILL ADD LATER)

//HIGH PURITY GALLIUM
ROASTER.recipeBuilder()
.inputs(ore('dustGallium'))
.fluidInputs(fluid('chlorine') * 3500)
.outputs(metaitem('dustCrudeGalliumTrichloride') * 3)
.duration(120)
.EUt(VA[LV])
.buildAndRegister()

//CHLORIDE ROUTE (75%)
DISTILLERY.recipeBuilder()
.fluidInputs(fluid('crude_gallium_trichloride') * 432)
.fluidOutputs(fluid('gallium_trichloride') * 750)
.duration(120)
.EUt(VA[LV])
.buildAndRegister()

DT.recipeBuilder()
.fluidInputs(fluid('crude_gallium_trichloride') * 432)
.fluidOutputs(fluid('gallium_trichloride') * 1000)
.duration(120)
.EUt(VA[MV])
.buildAndRegister()

BR.recipeBuilder()
.fluidInputs(fluid('gallium_trichloride') * 1000)
.fluidInputs(fluid('hydrogen') * 3000)
.outputs(metaitem('dustHighPurityGallium'))
.fluidOutputs(fluid('hydrogen_chloride') * 3000)
.duration(120)
.EUt(VA[MV])
.buildAndRegister()

//VACUUM ROUTE
VACUUM_DT.recipeBuilder()
.inputs(ore('dustGallium'))
.outputs(metaitem('dustHighPurityGallium'))
.duration(120)
.EUt(VA[MV])
.buildAndRegister()

//GALLIUM ARSENIDE PRODUCTION (LIQUID ENCAPSULATED CZOCHIRALSKI PROCESS)
mods.gregtech.mixer.removeByInput(7, [metaitem('dustGallium'), metaitem('dustArsenic'), metaitem('circuit.integrated').withNbt(["Configuration": 1])], null)
mods.gregtech.blender.removeByInput(7, [metaitem('dustGallium'), metaitem('dustArsenic'), metaitem('circuit.integrated').withNbt(["Configuration": 1])], null)
//SEED CRYSTAL
CRYSTALLIZER.recipeBuilder()
.inputs(ore('dustSmallHighPurityArsenic'))
.fluidInputs(fluid('high_purity_gallium') * 36)
.chancedOutput(metaitem('seed_crystal.gallium_arsenide'), 2500, 0)
.duration(500)
.EUt(VA[LV])
.buildAndRegister()

//CRYSTALLIZATION
CRYSTALLIZER.recipeBuilder()
.circuitMeta(1)
.fluidInputs(fluid('high_purity_gallium') * 144)
.fluidInputs(fluid('high_purity_arsenic') * 144)
.notConsumable(fluid('boron_trioxide') * 720)
.inputs(metaitem('seed_crystal.gallium_arsenide'))
.notConsumable(metaitem('crucible.boron.nitride'))
.outputs(metaitem('unrefined_boule.gallium_arsenide'))
.duration(240)
.EUt(VA[LV])
.buildAndRegister()

CRYSTALLIZER.recipeBuilder()
.circuitMeta(2)
.fluidInputs(fluid('high_purity_gallium') * 144)
.fluidInputs(fluid('high_purity_arsenic') * 144)
.notConsumable(fluid('boron_trioxide') * 720)
.notConsumable(metaitem('seed_crystal.gallium_arsenide'))
.notConsumable(metaitem('crucible.boron.nitride'))
.outputs(metaitem('ingotGalliumArsenide') * 2)
.duration(240)
.EUt(VA[LV])
.buildAndRegister()

ZONE_REFINER.recipeBuilder()
.inputs(metaitem('unrefined_boule.gallium_arsenide'))
.outputs(metaitem('boule.gallium_arsenide'))
.duration(120)
.EUt(VA[LV])
.buildAndRegister()

CUTTER.recipeBuilder()
        .fluidInputs(fluid('ultrapure_water') * 100)
        .inputs(metaitem('boule.gallium_arsenide'))
        .outputs(metaitem('wafer.gallium_arsenide') * 16)
        .outputs(metaitem('seed_crystal.gallium_arsenide'))
        .duration(400)
        .EUt(64)
        .buildAndRegister()
