
name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short $GITHUB_SHA)"
    - name: Install requests
      run: |
       pip install requests
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '8'
    - run: java -version
    - name: Run Build
      run: |
        python build/main.py
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.1.1
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: ${{ steps.vars.outputs.sha_short }}

          files: |
            buildOut/client.zip
            buildOut/server.zip
            buildOut/modlist.html
